### ISSUE TITLE
Generate camera entity in HA from the camera in Echo Show

### ISSUE THREAD

**Issue by holdestmade** [alandtse/alexa_media_player#1915]
**Describe the solution you'd like**
Display the camera from Echo Show in HA. It is now possible in the app to watch a feed from a camera in an Echo Show. I have a Show 5 and a new Show 8 and only the Show 8 will display it

**Additional context**
There are other Issues on here requesting this from a while ago that have been closed but now its available in the app, was wondering if it is now possible

**Screenshot**
Screenshot of app showing camera feed

![Screenshot_20230426-154529](https://user-images.githubusercontent.com/13977244/234614242-053ed59c-a870-4c22-8b1e-2727f433da95.png)

**Comment by rizz360** [comment]
No, please keep this open.

**Comment by Aaroneisele55** [comment]
Still relevant, don't close

**Comment by PaulBiod** [comment]
Hi, How did you manage to get the echo show 8 stream to HA ??
