### ISSUE TITLE
DisplayPower API implementation for Echo Dot with Clock

### ISSUE THREAD

**Issue by alexandreghez** [alandtse/alexa_media_player#2013]
**Is your feature request related to a problem? Please describe.**
A solution for implementing the on / off toggle that permit he visible / hide of clock on echo dot with clock

**Describe the solution you'd like**
A binary toogle to hide / show the clock

**Describe alternatives you've considered**
Probably send a message "alexa, tun on / off the display"

**Additional context**
Hello,

is it possible to integrate a switch for echo dot with clock.
I have found the undocumented API.

You can have a look here : 
https://github.com/Apollon77/ioBroker.alexa2/issues/356

Or Here : 
https://github.com/sigalou/jeedom_alexaapi/issues/35

the URL to call is : 
/api/v1/devices/A0XXXXXXXUI/settings/displayPower 

With payload {"value":""ON""} or {"value":""OFF""}

**Comment by alandtse** [comment]
Thanks. Happy to take a PR to add this.

**Comment by alandtse** [comment]
If the API doesn't provide state back it may need to be a button.

**Comment by alexandreghez** [comment]
Hello
If i remember correctly, calling the url with GET http verb give you the current status.
