### ISSUE TITLE
adjusting configuring without yaml?

### ISSUE THREAD

**Issue by xip0rt** [alandtse/alexa_media_player#2060]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

after configuring login with the UI, there's no way to go back to the original Configuration window (where you entered username, password, inclusion, exclusion)

**To Reproduce**

1. setup an account.
2. navigate to config/integrations/integration/alexa_media
3. clicking "configure" only gives you three options: wait to queue, public URL, connected devices to echo

**Expected behavior**

seeing all of the options available during original setup

**System details**

- Home-assistant (version): 2023.10.1
- alexa_media (version from `const.py` or HA startup): 4.7.6
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/custom-components/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : yes

**Additional context**

why is this needed? i was trying to setup an inclusion list, then an exclusion list, and had to recreate an account connection every time i wanted to make a change

**Comment by xip0rt** [comment]
as a result of my back and forth reconfiguring yesterday, I am now seeing this:
![2023-10-05 (2)](https://github.com/custom-components/alexa_media_player/assets/107813314/f382c8ad-840f-4002-b6c5-cff8d5adca6e)

I removed all of the authentications for those on my 2fa. clicking reconfigure only pulls up the login information popup, but there's nowhere to tell it to delete the account

**Comment by alandtse** [comment]
Will take a PR to add an option to edit. Otherwise you just have to remove and readd.

**Comment by Ludy87** [comment]
This is not common practice and should not be there.
There is no integration that I know of that allows this, as there is a mechanism that checks whether the information entered for the login is correct. This means it is not necessary to provide an option to change the login information.

**Comment by alandtse** [comment]
I'd agree on changing login stuff, but if it's about the other options like include/exclude, then I'd be ok with this as an enhancement.
