### ISSUE TITLE
After update today notify.alexa_media no longer shows or works in HA

### ISSUE THREAD

**Issue by thorrrr** [alandtse/alexa_media_player#2117]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/custom-components/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**
I have several automation's using notify.alexa_media but after an update it no longer shows or works in HA
The service is no longer showing  so this part of my automation's no longer work 

Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:1783
First occurred: 16:42:05 (2 occurrences)
Last logged: 16:47:07

websocket_api script: Error executing script. Service not found for call_service at pos 1: Unable to find service notify.alexa_media

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:268
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 16:42:05 (2 occurrences)
Last logged: 16:47:07

[139756669377344] Error handling message: Unable to find service notify.alexa_media (unknown_error) Dale from 192.168.23.34 (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36)

![image](https://github.com/custom-components/alexa_media_player/assets/8170673/278a25b6-97fb-48ef-9e54-7e024551dc1a)

**Comment by svenht** [comment]
Same problem here :-(

**Comment by GunnarMitter** [comment]
Same here

**Comment by VictoriousCupid** [comment]
For me it works half the time.

**Comment by MidnightLink** [comment]
I'm wondering it they were having issues on the API's end as these all happened near the same time

`This error originated from a custom integration.

Logger: custom_components.alexa_media
Source: helpers/update_coordinator.py:322
Integration: Alexa Media Player (documentation, issues)
First occurred: 10:38:04 AM (1 occurrences)
Last logged: 10:38:04 AM

Error fetching alexa_media data: Error communicating with API:`

`Logger: alexapy.helpers
Source: runner.py:188
First occurred: 10:38:04 AM (4 occurrences)
Last logged: 10:38:04 AM

alexaapi.get_devices((<alexapy.alexalogin.AlexaLogin object at 0x7f8651eefe10>,), {}): Timeout error occurred accessing AlexaAPI: An exception of type CancelledError occurred. Arguments: ()
alexaapi.get_bluetooth((<alexapy.alexalogin.AlexaLogin object at 0x7f8651eefe10>,), {}): Timeout error occurred accessing AlexaAPI: An exception of type CancelledError occurred. Arguments: ()
alexaapi.get_device_preferences((<alexapy.alexalogin.AlexaLogin object at 0x7f8651eefe10>,), {}): Timeout error occurred accessing AlexaAPI: An exception of type CancelledError occurred. Arguments: ()
alexaapi.get_dnd_state((<alexapy.alexalogin.AlexaLogin object at 0x7f8651eefe10>,), {}): Timeout error occurred accessing AlexaAPI: An exception of type CancelledError occurred. Arguments: ()`


`Logger: homeassistant.components.alexa.state_report
Source: components/alexa/state_report.py:376
Integration: Amazon Alexa (documentation, issues)
First occurred: 10:37:57 AM (2 occurrences)
Last logged: 10:38:11 AM

Timeout sending report to Alexa for sensor.temperature_humidity_sensor_library_attic_air_temperature
Timeout sending report to Alexa for sensor.temperature_humidity_sensor_top_attic_air_temperature`

**Comment by alandtse** [comment]
Please fill out the full template. You're not providing all the required info.

**Comment by edzards** [comment]
same for me

**Comment by andregoncalvespires** [comment]
I already use the alexa_media.update_last_caled service in all scripts, but I can't understand why some echos don't have last_called and the last_called_timestamp and last_called_summary attributes updated. I believe this is the reason why it is not working correctly.

![image](https://github.com/alandtse/alexa_media_player/assets/98660995/f3fffdec-ff44-428f-8c6d-cab6c036f3fd)

**Comment by mrai64** [comment]
A week ago also for me. Was my ALL notify.* on HA...

**Comment by Gheben** [comment]
Until a few days ago it worked intermittently, now it doesn't work anymore. Alexa's notify.* service isn't working.

**Comment by Gheben** [comment]
This from the log:

Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.alexa_media
Source: helpers/update_coordinator.py:345
Integration: Alexa Media Player (documentation, issues)
First occurred: 24 febbraio 2024 alle ore 07:41:27 (3 occurrences)
Last logged: 08:08:35

Error fetching alexa_media data: Error communicating with API: Too Many Requests

**Comment by daxxio** [comment]
maybe a coinicidence, but just wanted to add that for me it worked after commenting these lines:
```
alexa:
  smart_home:
    locale: de-DE
    **#endpoint: 
    #client_id: 
    #client_secret:** 
```

**Comment by shamimrahim** [comment]
I updated to latest version of Homeassistant yesterday and the notify.alexa services had disappeared. I restored to an older version and they came back. I checked for @daxxio and @Gheben's fixes but they did not work for me.

**Comment by makgiber1984** [comment]
Same problem here, for two weeks the notify.alexa_media_xxx services have been randomly disappearing, sometimes they recover when restarting, but it has not been recovered for days. Any idea?
<img width="1480" alt="Capture de pantalla 2024-04-23 a las 18 55 36" src="https://github.com/alandtse/alexa_media_player/assets/58627957/664c020b-bd29-464d-a902-0b06d7d66d78"> <img width="1064" alt="Captura de pantalla 2024-04-23 a las 18 56 33" src="https://github.com/alandtse/alexa_media_player/assets/58627957/cdff4dd5-a803-43be-87e4-9309e3291a78">

**Comment by mirlorojiblanco** [comment]
The same here :-(. What is the solution?

**Comment by johntdyer** [comment]
Same issue for me....

**Comment by WLammert** [comment]
> maybe a coinicidence, but just wanted to add that for me it worked after commenting these lines and ass Gheben mentioned, the media_player:
> 
> ```
> alexa:
>   smart_home:
>     locale: de-DE
>     #endpoint: 
>     #client_id: 
>     #client_secret:
> ```

Thank you @daxxio -> you saved my life! So after having the same issue after every update I just edited the missing locale as you described (which by the way is only optional in the documentation) and everything is now working as intended!

**Comment by danielbrunt57** [comment]
For everyone's information, this `alexa_media` custom component has **_absolutely_** nothing to do with the [Amazon Alexa Smart Home Skill](https://www.home-assistant.io/integrations/alexa.smart_home/) which makes HA entities appear in the Amazon Alexa app when you say "Alexa, discover devices".  The `alexa:` block in configuration.yaml is only required when you manually configure the Smart Home Skill instead of using Nabu Casa Cloud and is how I have my Smart Home skill set up:
```
alexa:
  smart_home:
    locale: en-CA
    endpoint: https://api.amazonalexa.com/v3/events
    client_id: amzn1.application-oa2-client.9cef<redacted>f4cd
    client_secret: amzn1.oa2-cs.v1.56b0<redacted>ee0548
    filter:
      include_domains:
        - light
        - cover
        - lock
...etc.
```
To reiterate: That smart home skill integration is completely separate and unrelated to this integration!
Also,
`media_player` is only used for the [Universal Media Player](https://www.home-assistant.io/integrations/universal/) integration.
`api:`  is only used for the [Home Assistant API](https://www.home-assistant.io/integrations/api/) which exposes a RESTful API.

The legacy YAML setup documentation for this integration is:
> Configuration.yaml
> While this still works, it will be deprecated in the future. Please use [Integrations](https://github.com/alandtse/alexa_media_player/wiki/Configuration#integrations-page). 
> Once the files are downloaded, you’ll need to update your config to include the following under the alexa_media domain:
> While this still works, it will be deprecated in the future. Please use [Integrations](https://github.com/alandtse/alexa_media_player/wiki/Configuration#integrations-page). 
> Once the files are downloaded, you’ll need to update your config to include the following under the alexa_media domain:

```
alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.com
```
