### ISSUE TITLE
Renamed echo device doesn't rename the entity name

### ISSUE THREAD

**Issue by heffneil** [alandtse/alexa_media_player#2127]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

If you rename a device (echo show) in the alexa app it will continue to be named the original name in Home Assistant

**To Reproduce**
Add echo device, rename device in Alexa App, Name is changed in HA but its home assistant device name media_player.XXXX is the original name.

If you go to integrations and show all devices.  Once you go to the new device it will show you the device and if you look at the entity name it will show it as the old one.

**Expected behavior**

If you rename the device the HA device name should also be replaced with the new name, or be able to delete and rsync

**Screenshots**

N/A

**System details**

- Home-assistant (version): Latest
- alexa_media (version from `const.py` or HA startup): Latest
- alexapy (version from `pip show alexapy` or HA startup): Latest
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). y

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).
I have no logs to demonstrate this
**Additional context**
No more context. I think this is pretty straight forward.

**Comment by danielbrunt57** [comment]
You can rename your entities in HA however you like.  The link between an HA entity and an Amazon device is NOT the Amazon visual device name.  It's an internal hexadecimal GUID that Amazon assigns to the device when it is adopted and has nothing whatsoever to do with the graphical name you give it in the Alexa app.  The same goes for the entity_id in HA and changing that does not change the underlying link between the integration and Amazon.  The integration has no way of knowing that you changed the name in Alexa.

**Comment by roger-** [comment]
I have a similar issue. In my case I moved and renamed an Alexa device from "basement" to "kitchen" but confusingly I have to use the old service name `notify.alexa_media_basement_echo_dot`. 

Maybe the service names should be based on a persistent, unique ID or something ("notify.alexa_0x123ABC")?
