### ISSUE TITLE
Transition lights slowly

### ISSUE THREAD

**Issue by KTibow** [alandtse/alexa_media_player#2139]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
In the Alexa app, you can ramp a light up/down over time. But you can't do that in HA.

**Describe the solution you'd like**
It would be nice if lights brought in to HA could be transitioned in the same way.

**Describe alternatives you've considered**
Manually make an automation that mimics this, or use a custom routine

**Additional context**
N/A

**Comment by KTibow** [comment]
Nope

**Comment by broyuken** [comment]
are you talking about lights connected to alexa or connected to HA? In HA you can use the transition when you do a light.turn_on service.

**Comment by KTibow** [comment]
Lights brought in to HA. Eg Echo Glow. This didn't work last time I checked.
