### ISSUE TITLE
Only works it the Echo Dot isn't in idle mode

### ISSUE THREAD

**Issue by epicbenz** [alandtse/alexa_media_player#2141]
**Describe the bug**

So I'll explain it in a little more detail to clarify all possible questions in advance: 
I created an app on the Spotify Developer page and added it to the Spotify integration (https://www.home-assistant.io/integrations/spotify/) on my Home Assistant using Client ID and Client Secret.  

This allows me to control my Echo Dot and play the playlist there. 
However, I have already noticed that this only works properly when the Echo Dot is not in standby mode. Otherwise, nothing happens when I select my Echo Dot as the source in the Spotify integration tile. If I then try this several times, the Echo Dot is apparently woken up and then it works so far. 

I then added the integration of the alexa_media_player and logged in with my Amazon account (2FA activated) and can also see my connected Amazon devices such as the Echo Dot in the integration. 

Then I built the following automation (only the actions listed):

1. 
service: media_player.select_source
target:
  entity_id: media_player.andreas_2_echo_dot
data:
  source: andreas_2_echo_dot

2. 
service: media_player.volume_set
target:
  entity_id: media_player.andreas_2_echo_dot
data:
  volume_level: 0.35

3. 
service: media_player.play_media
target:
  device_id: []
  area_id: []
  entity_id: media_player.spotify_spotifybad
data:
  media_content_id: https://open.spotify.com/playlist/01Vmn16TNw7s5tYBEpKLOc?si=8fca1cf3f8424505
  media_content_type: playlist

The problem is that the automation only works when the Echo Dot is not in sleep mode. As soon as the Echo Dot is in standby, the automation only runs up to the 2nd step and at the 3rd step I get the following error message:

Stopped because an error was encountered at December 12, 2023 at 12:33:59 (runtime: 2.01 seconds)

- Entity media_player.spotify_spotifybad does not support this service.

**Expected behavior**

The Volume of the Echo Dot should change and a playlist from Spotify should be playing. 

**Screenshots**

**System details**

- Home-assistant (version): 
Core
2023.11.3
Supervisor
2023.11.6
Operating System
11.2
Frontend
20231030.2

- alexa_media (version from `const.py` or HA startup):
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). y

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by KC-inDomus** [comment]
+1

**Comment by meluvalli** [comment]
Also have this problem.
