### ISSUE TITLE
Timer current state stops reporting after unknown timeframe

### ISSUE THREAD

**Issue by 7ooL** [alandtse/alexa_media_player#2145]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

After an unspecified period, the timers on the Amazon Echo devices stop updating in Home Assistant. The timers do not reflect the current time or status correctly. Often, I notice that even after timers are deleted the last status remains.

**To Reproduce**

1) set a timer on an echo device
2) observer the timer in home assistant
3) come back after timer is gone and see that it remains set. 

using the following card setup for observing timers. 
```
type: custom:auto-entities
filter:
  include:
    - domain: sensor
      entity_id: sensor.*echo*_next_timer
  exclude:
    - state: unknown
    - attributes:
        total_active: 0
sort:
  method: state
  ignore_case: true
  numeric: false
  reverse: false
show_empty: false
card:
  type: custom:timer-bar-card
  bar_foreground: '#eee'
  bar_direction: rtl
  bar_background: 'var(--mdc-theme-primary, #6200ee)'
  start_time:
    attribute: process_timestamp
  end_time:
    attribute: prior_value
  bar_width: 35%
  guess_mode: true
  filter: false
  debug: false
```

**Expected behavior**

The timers on the Amazon Echo devices should consistently update in real-time within Home Assistant, reflecting the correct time and status at all times.

**Screenshots**

**System details**

- Home-assistant (version):
Core 2023.12.3
Supervisor 2023.12.0
Operating System 11.2
Frontend 20231208.2
- alexa_media (version from `const.py` or HA startup):
{
  "domain": "alexa_media",
  "name": "Alexa Media Player",
  "codeowners": ["@alandtse", "@keatontaylor"],
  "config_flow": true,
  "dependencies": ["persistent_notification", "http"],
  "documentation": "https://github.com/alandtse/alexa_media_player/wiki",
  "iot_class": "cloud_polling",
  "issue_tracker": "https://github.com/alandtse/alexa_media_player/issues",
  "loggers": ["alexapy", "authcaptureproxy"],
  "requirements": ["alexapy==1.27.10", "packaging>=20.3", "wrapt>=1.14.0"],
  "version": "4.8.1"
}
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). Yes

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

Workaround:
Currently, the only way to restore accurate timer reporting is to reload the Amazon Echo integration in Home Assistant. This temporarily resolves the issue until it reoccurs after some time.

**Comment by xip0rt** [comment]
been having this issue off/on for months (years?). used to be about 50/50 whether it would go away after the timer expired, but lately it doesn't go away unless I reload the integration as mentioned in the post above.

I see that the state of `sensor.*_next_alarm` contains a date/time, and ideally when that time passes by the entity state should reset to a zero-value, which does not seem to occur anymore.
State: `2024-01-12T01:22:54+00:00`
Attributes:
```
recurrence: Never Repeat
process_timestamp: 2024-01-11T20:22:54.381702-05:00
prior_value: 2024-01-11T20:22:54-05:00
total_active: 1
total_all: 1
sorted_active: [redacted]
sorted_all: [redacted]
status: ON
dismissed: null
device_class: timestamp
icon: mdi:timer-outline
```

using basically the same card as OP, but without custom card
```
  - type: entity-filter
    show_empty: false
    entities:
      - sensor.echo_dot_next_alarm
      - sensor.echo_dot_next_timer
    state_filter:
      - operator: not in
        value:
          - unknown
          - unavailable
```
(Card value says "3 hours ago")

**Comment by TomN7** [comment]
I'm also having this issue. I'm using the next alarm entity as part of an automation to trigger an artificial sunrise, and eventually the entity will stop updating.

**Comment by fpfuetsch** [comment]
> I'm also having this issue. I'm using the next alarm entity as part of an automation to trigger an artificial sunrise, and eventually the entity will stop updating.

Can confirm, reloading the integration fixes it for some time but then it stops syncing again.
