### ISSUE TITLE
Unable to add integration

### ISSUE THREAD

**Issue by ChrisL79** [alandtse/alexa_media_player#2160]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

On adding integration, i never get to the setup screen. I have an error that says Config flow could not be loaded: 504 Gateway Time-out.

**To Reproduce**

1. Add the Alexa integration

**Expected behavior**

For it to work and make happy shiny rainbow time.

**Screenshots**

**System details**
Rpi4
Supervisor 2023.12.0
OS 11.2
Frontend 20240103.3
- Home-assistant (version):2024.1.0
- alexa_media (version from `const.py` or HA startup):4.9.0
- alexapy (version from `pip show alexapy` or HA startup):?
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : Yes.

**Logs**
Unable as integration never loads

**Additional context**

**Comment by ChrisL79** [comment]
Anyone???

**Comment by Ludy87** [comment]
Hi @ChrisL79, my guess for "504 Gateway Time-out" is that either the server is overloaded or you have an incorrect forwarding (proxy or the same).

I would restart HA and re-download the integration.

**Comment by ChrisL79** [comment]
> Hi @ChrisL79, my guess for "504 Gateway Time-out" is that either the server is overloaded or you have an incorrect forwarding (proxy or the same).
> 
> I would restart HA and re-download the integration.

Hello there. Running it on a rpi, load never above 5%. I have tried redownloading many times also restarting.

I had the integration running fine 3 months ago, then i updated HA and it would not work, so i deleted Alexa, also the Alexa files in the custim folder and thought it would be easy to start from the beginning, but now i can not even load the integration to get to the setup screen. 
The only thing i can think of is there must be some old file somewhere from before that needs to be deleted, but i can not see it anywhere.

**Comment by Ludy87** [comment]
The 504 error is not your fault, but rather the provider of the remote site

**Comment by ChrisL79** [comment]
> The 504 error is not your fault, but rather the provider of the remote site

Understood, so am i right in thinking there is a problem with the code or this integration is dead?

**Comment by Ludy87** [comment]
Apparently you have no idea what you are writing.
The code is just an interface that communicates to Amazon's server.
And how do you come to the conclusion that integration is dead? The integration is constantly being developed further.

**Comment by ChrisL79** [comment]
I am here for help fella. I am asking why i can never get to the setup screen. If i had an idea what was wrong, i would not be asking here for help would i.
If you have no idea how to help, why bother replying?

**Comment by sameeraakbar** [comment]
I am facing this issue more or less. It either ends up in 500 internal server error server got itself in trouble OR a long URL which does not load.

**Comment by ChrisL79** [comment]
> I am facing this issue more or less. It either ends up in 500 internal server error server got itself in trouble OR a long URL which does not load.

I run PfSense/Snort as my firewall. Doing a traffic capture on my HA ip address i managed to figure out the firewall was blocking traffic to a 186 xxx ip address. This is needed for it to work.  The integration setup screen loaded after i did this, then i got the internal server error which was just a case of enabling 2fa in your Amazon account. Everything is working now. 

Hope this helps you.
