### ISSUE TITLE
Alexa media player installed but not showing on media area

### ISSUE THREAD

**Issue by munimpatel** [alandtse/alexa_media_player#2162]
After installing alexa media successfully All my alexa devices appeared on the Alexa media player integration (see attached file). However when going into the media tab on home assistant none of my alexa devices are present and so I am unable to get alexa to work with my unifi g4 doorbell. 
[Doc1.docx](https://github.com/alandtse/alexa_media_player/files/13832092/Doc1.docx)

- Home-assistant (version):
- alexa_media (version from `const.py` or HA startup):
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :

**Comment by Pietrogramma** [comment]
I also have a similar problem, I installed the component from HACS, it recognized all my Alexa devices, but if I click on the entities they are all unavailable (see attached photo). There is a solution?
Thanks and ciao
![image](https://github.com/alandtse/alexa_media_player/assets/11855652/02f619ab-cb50-4921-a809-9fb87e1ac112)

**Comment by Btomy81** [comment]
Hi all,
I managed to install the media player but I can't see my devices at all. Any Ideas?
Thanks for your help.

**Comment by Citek86** [comment]
> I also have a similar problem, I installed the component from HACS, it recognized all my Alexa devices, but if I click on the entities they are all unavailable (see attached photo). There is a solution? munimpatel your entity are available? Thanks and ciao ![image](https://private-user-images.githubusercontent.com/11855652/294704827-02f619ab-cb50-4921-a809-9fb87e1ac112.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMzI5NDYsIm5iZiI6MTcwNTEzMjY0NiwicGF0aCI6Ii8xMTg1NTY1Mi8yOTQ3MDQ4MjctMDJmNjE5YWItY2I1MC00OTIxLWE4MDktOWZiODdlMWFjMTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDA3NTcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjOTgxMTdiYzFiODQzYmYwN2EwMWZhNzc4MDk3Y2NkYzdkNGNlMzNiZjRmOWZkYWJhNzVlMGFlN2Q5Y2IxN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-SsRtL6Z4TbPHQjj5r8FMgFHaYJmMFBRWXJaXCXZL6A)

same issue, added integration successfully, however after doing so all entities appear as unavailable.

**Comment by munimpatel** [comment]
My devices are also unavailable

**Comment by ctve** [comment]
Same problem here : after installing alexa media successfully, my alexa device appeared on the Alexa media player integration, however when going into the media tab on home assistant it's not present.

**Comment by munimpatel** [comment]
Ive tried what you have suggested and still does not appear under media

**Comment by Citek86** [comment]
> Hi everyone, I solved the problem by indicating amazon.com and not amazon.it (where I am registered being Italian), when I installed the hacs integration. Immediately afterwards he redirected me to an Amazon page, and I followed the instructions for 2FA authentication and everything worked well. Now, finally, I can use my Echo Dot devices as media players.
> 
> I hope this indication can be useful to someone and bye

Tried the same with no luck as well.

**Comment by RafikiHome** [comment]
> Hi everyone, I solved the problem by indicating amazon.com and not amazon.it (where I am registered being Italian), when I installed the hacs integration. Immediately afterwards he redirected me to an Amazon page, and I followed the instructions for 2FA authentication and everything worked well. Now, finally, I can use my Echo Dot devices as media players.
> 
> I hope this indication can be useful to someone and bye

I have the same problem _(ie After installing alexa media successfully All my alexa devices appeared on the Alexa media player integration. However when going into the media tab on home assistant none of my alexa devices are present_ ). Tried it with both local and .COM Amazon account and neither worked. Alexa devices are registered in my local (.AE) account.

**Comment by liquid-motion** [comment]
I have exactly the same problem. All my Alexa devices are "NOT AVAILABLE" (red exclamation mark).

**Comment by miguelillo84** [comment]
Same problem.

**Comment by miguelillo84** [comment]
> Same problem.

Solved rebooting the HA server.
