### ISSUE TITLE
500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by jcarlier** [alandtse/alexa_media_player#2165]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**
aalways  the title of the message 

**To Reproduce**

1. Go to hacs
2. Click on restart download
3. new integration 'alexa media player)  ( v 4.9.0
4. fill integration 

**Do I have to use double authentication**??? 2fa

see:

(https://community.home-assistant.io/t/alexa-configuration-500-internal-server-error/671246)

**Expected behavior**

**Screenshots**

**System details**

- Home-assistant (version): 2024.1.2
- alexa_media (version from `const.py` or HA startup):
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by matteo289** [comment]
HI
I also have the same error. If I install Alexa Media Player, both with public IP address and local IP address, I get the error

500 Internal Server Error Server got itself in trouble

How can it be solved?

Core --> 2024.1.2
Supervisor --> 2023.12.0
Alexa --> 4.9.0

Thank you

**Comment by jcarlier** [comment]
maybe the solution is on:

https://github.com/alandtse/alexa_media_player/wiki/Configuration

i am also looking for.. the solution



Le ven. 12 janv. 2024 à 15:39, matteo289 ***@***.***> a
écrit :
