### ISSUE TITLE
Send alexa command in french and Alexa translate in english

### ISSUE THREAD

**Issue by Frazou1** [alandtse/alexa_media_player#2171]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

**To Reproduce**

I have a automation where i send a command to alexa in french and alexa translate in english

```service: media_player.play_media
target:
  entity_id: media_player.alexa_chambre
data:
  media_content_id: "'Ferme fan parent'"
  media_content_type: custom
```

**Expected behavior**

**Screenshots**

**System details**

- Home-assistant (version):
- alexa_media (version from `const.py` or HA startup):
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by alandtse** [comment]
That's controlled by Amazon. We don't do any translation.
