### ISSUE TITLE
Update Amazon Thermostat temperature value more frequently

### ISSUE THREAD

**Issue by inger147** [alandtse/alexa_media_player#2172]
**Is your feature request related to a problem? Please describe.**
I have noticed that the temperature value from the Amazon Thermostat updates infrequently in Home Assistant, i.e there is a delay in showing the actual temperature.  

**Describe the solution you'd like**
Since I have created automations that work best if the temperature is updated frequently, it would be beneficial if the thermostat's refresh rate can be increased.  In the Alexa app I have noticed that the thermostat's temperature value does update frequently, so this should be possible.

**Describe alternatives you've considered**
I can create routines through the Alexa app based on the thermostat temperature, but the options there are less robust, so I would much prefer to create my automations in Home Assistant.

**Comment by inger147** [comment]
This issue has not been fixed yet - please do not close it.

**Comment by alandtse** [comment]
No, you can trigger manual refreshes using HA already. We already have enough people getting 429 errors, #2177 so increasing load on Amazon will not be done officially.

**Comment by danielbrunt57** [comment]
> No, you can trigger manual refreshes using HA already. We already have enough people getting 429 errors, #2177 so increasing load on Amazon will not be done officially.

@alandtse I certainly concur about 429 errors and the need to avoid more frequent polling however, I'm not aware of how one might trigger a **_manual refresh_** in HA even if you wanted to knowing the risks.  All we have for services are `update_last_called` and `force_logout`.  Can you explain how to initiate a manual poll for an update?
```
  "services": {
    "force_logout": {
      "name": "Force Logout",
      "description": "Force account to logout. Used mainly for debugging.",
      "fields": {
        "email": {
          "name": "Email address",
          "description": "Accounts to clear. Empty will clear all."
        }
      }
    },
    "update_last_called": {
      "name": "Update Last Called Sensor",
      "description": "Forces update of last_called echo device for each Alexa account.",
      "fields": {
        "email": {
          "name": "Email address",
          "description": "List of Alexa accounts to update. If empty, will update all known accounts."
        }
      }
    }
```
