### ISSUE TITLE
Alexa Household Account - Next Alarm, Reminder and Timer not working

### ISSUE THREAD

**Issue by Milinator** [alandtse/alexa_media_player#2173]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**
I have four Echo Dots in my household. Three are registered in my Amazon account and one in my girlfriend's account because she wants to play her Spotify playlist in the shower. Thanks to the "Amazon Household" function, I can access and use my girlfriend's Echo as normal via the Alexa Media Player integration. So the most important things work. 

Yesterday, however, I noticed that the three entities for "Next Alarm", "Next Reminder" and "Next Timer" are always "Unknown" on my girlfriend's Echo Dot. On all my other Echos it works without any problems.

**To Reproduce**
1. Add someone to your amazon household (https://www.amazon.com/myh/households) 
2. Log in with an Echo to the account you just added
3. Look at the entities "Next Alarm", "Next Reminder" and "Next Timer" for this Echo and try to set an alarm clock

**Expected behavior**
"Next Alarm", "Next Reminder" and "Next Timer" should also work for the Household account Echo.

**Screenshots**
![grafik](https://github.com/alandtse/alexa_media_player/assets/67156976/701f7f03-559f-40ed-9a63-2fab20aa4b86)

**System details**

- Home-assistant (version): 2024.1.5
- alexa_media (version from `const.py` or HA startup): 4.9.0
- alexapy (version from `pip show alexapy` or HA startup): 1.27.10
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). Yes

**Logs**
```
2024-01-25 13:13:21.552 DEBUG (MainThread) [custom_components.alexa_media] Updating mediaplayer notifications: {'dopplerId': {'deviceSerialNumber': 'G************CPC', 'deviceType': 'A1RABVCI4QCIKC'}, 'notificationId': 'f0bf3fc8-c4f0-3e22-bbb7-0e34be81b02d', 'notificationVersion': 3, 'eventType': 'UPDATE', 'destinationUserId': 'A**********41O'}
2024-01-25 13:13:21.559 DEBUG (SyncWorker_1) [custom_components.alexa_media.sensor] Updating sensor <entity sensor.anna_lenas_echo_dot_next_alarm=unknown>
2024-01-25 13:13:21.559 DEBUG (SyncWorker_4) [custom_components.alexa_media.sensor] Updating sensor <entity sensor.anna_lenas_echo_dot_next_timer=unknown>
2024-01-25 13:13:21.559 DEBUG (SyncWorker_4) [custom_components.alexa_media.sensor] Updating sensor <entity sensor.anna_lenas_echo_dot_next_reminder=unknown>
```

**Additional context**
If you need anything more, feel free to let me know. I really love this integration btw :)

**Comment by eugeneniemand** [comment]
I have 10+ echos, all on my account. They all say unknown same as the post above shows

**Comment by alandtse** [comment]
Those only populate when there is an alarm or notification set. That is a ha limitation. Filter them out when unknown.

**Comment by Milinator** [comment]
Hello Alandtse,

Thanks for your reply.
Please read my issue again. They do in fact populate when I set them on my regular echos. But if I set an alarm on the household echo (different acc) it doesn't get populated. No matter what.

**Comment by alandtse** [comment]
Can you see the timers in the app for the household echo? If household accounts do not expose that, there's nothing we can see. Historically, we have advised people to use multiple accounts and only include echos that they have primary control over since shared echos have less access.

**Comment by Milinator** [comment]
> Can you see the timers in the app for the household echo? If household accounts do not expose that, there's nothing we can see. Historically, we have advised people to use multiple accounts and only include echos that they have primary control over since shared echos have less access.

Yes, I can see the timers etc. in the alexa app. ![Screenshot_20240326_123636.jpg](https://github.com/alandtse/alexa_media_player/assets/67156976/a71212f0-2fd1-4c17-b8d7-29736930f03e)
