### ISSUE TITLE
TTS Audio not working

### ISSUE THREAD

**Issue by spezzuti** [alandtse/alexa_media_player#2174]
**Describe the bug**

When attempting to play local audio file (in this case, cuckoo clock sound since the Cuckoo Clock script is what made me notice) Alexa no longer plays the audio. Instead states "to play TTS, please set announcement equals true. Music cannot be played this way"

**Expected behavior**

Should play local audio sound 

**Other**

I noticed this version yesterday (1/27)

**Comment by ajithprabhakar** [comment]
Same issue for me as well, I am getting an error saying Simon say skill is not available

**Comment by TimLisemer** [comment]
Same for me

**Comment by yangg1224** [comment]
can i ask how did you fix it?
