### ISSUE TITLE
Warning deprecated supported features in log after update to core 2024.1.5

### ISSUE THREAD

**Issue by jocamane** [alandtse/alexa_media_player#2176]
**Describe the bug**

after update to core 2024.1.5 apear in log a warning message that inform  deprecated supported features

**To Reproduce**

install the core 2024.1.5

**Expected behavior**

no log error

**System details**

Core 2024.1.5
Supervisor 2023.12.1
Operating System 11.2
Frontend 20240104.0

- alexa_media (version from `const.py` or HA startup): __version__ = "4.8.1"
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : YES

**Logs**
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1524
First occurred: 14:14:53 (5 occurrences)
Last logged: 14:14:53

Entity None (<class 'custom_components.alexa_media.media_player.AlexaClient'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.PAUSE|VOLUME_SET|VOLUME_MUTE|PREVIOUS_TRACK|NEXT_TRACK|TURN_ON|TURN_OFF|PLAY_MEDIA|SELECT_SOURCE|STOP|PLAY|SHUFFLE_SET: 56253>, please create a bug report at https://github.com/alandtse/alexa_media_player/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by Snuffy2** [comment]
These look to all be fixed in version 4.9.0
