### ISSUE TITLE
This does not show up in HACS anymore

### ISSUE THREAD

**Issue by bkr1969** [alandtse/alexa_media_player#2181]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Go to HACS, search alexa.  Nothing

**To Reproduce**

How to install this?

![image](https://github.com/alandtse/alexa_media_player/assets/42385989/f97b514f-5093-425b-9f5f-e6a324c2b802)

**System details**

- Home-assistant (version):
- alexa_media (version from `const.py` or HA startup):
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by glasoline** [comment]
Integration broke after update yesterday.

Logger: alexapy.helpers
Source: runner.py:188
First occurred: 09:06:34 (1 occurrences)
Last logged: 09:06:34

alexaapi.get_devices((<alexapy.alexalogin.AlexaLogin object at 0x7f511f3fc750>,), {}): A connection error occurred: An exception of type KeyError occurred. Arguments: ('xx@xx.org',)

**Comment by r0bb10** [comment]
i can confirm does not work anymore

```2024-02-05 18:08:43.143 ERROR (MainThread) [alexapy.alexaapi] Giving up _static_request(...) after 5 tries (alexapy.errors.AlexapyTooManyRequestsError: Too Many Requests)
2024-02-05 18:08:43.143 WARNING (MainThread) [alexapy.helpers] alexaapi.get_customer_history_records((<alexapy.alexalogin.AlexaLogin object at 0x7f8a984f50>,), {'max_record_size': 10}): An error occurred accessing AlexaAPI: An exception of type AlexapyTooManyRequestsError occurred. Arguments:
2024-02-05 18:08:43.144 WARNING (MainThread) [alexapy.helpers] alexaapi.get_last_device_serial((<alexapy.alexalogin.AlexaLogin object at 0x7f8a984f50>,), {}): An error occurred accessing AlexaAPI: An exception of type AlexapyTooManyRequestsError occurred. Arguments:

**Comment by alandtse** [comment]
Issues with hacs need to be reported there.
