### ISSUE TITLE
alexa connected lights no longer work

### ISSUE THREAD

**Issue by lsellens** [alandtse/alexa_media_player#2185]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

After updating to v4.9.1 my son's echo glow is no longer available in home assistant. Says the entity is no longer provided. I tried removing and reinstalling the integration to no luck. Rolled back to v4.9.0 and his light was back.

![Screenshot at 2024-02-12 07-44-31](https://github.com/alandtse/alexa_media_player/assets/561979/b7d5c1b3-7229-4f7a-a96a-893551aa5405) 

**System details**

- Home-assistant (version): 2024.2.1
- alexa_media (version from `const.py` or HA startup): 4.9.1
- alexapy (version from `pip show alexapy` or HA startup): 1.27.10
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : no

**Logs**

I can provide a full log if needed but I think this is the only relevant error.
```
Logger: homeassistant.components.light
Source: helpers/entity_platform.py:344
Integration: Light (documentation, issues)
First occurred: 7:42:17 AM (1 occurrences)
Last logged: 7:42:17 AM

Error while setting up alexa_media platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/alexa_media/light.py", line 98, in async_setup_entry
    return await async_setup_platform(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/light.py", line 78, in async_setup_platform
    light = AlexaLight(coordinator, account_dict["login_obj"], light_entity)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/light.py", line 135, in __init__
    self._attr_supported_color_modes = color_modes(details)
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/light.py", line 118, in color_modes
    return [ColorMode.HS_COLOR]
            ^^^^^^^^^^^^^^^^^^
AttributeError: type object 'ColorMode' has no attribute 'HS_COLOR'
```

**Comment by lsellens** [comment]
I think ColorMode.HS_COLOR should be ColorMode.HS
https://github.com/home-assistant/core/blob/dev/homeassistant/components/light/__init__.py
I'll test and send a PR if it fixes it

**Comment by Scope666** [comment]
Same here, noticed all lights were unavailable.  Deleted and re-added integration, made sure 'Include devices connected via Echo' was checked ... not picking up any light entities.

**Comment by lsellens** [comment]
@martymart8864 can you test my PR #2186
If youre running hassos just open terminal and run these commands
```
cd config/custom_components/alexa_media/
mv light.py light.py.bak
wget https://raw.githubusercontent.com/lsellens/alexa_media_player/lights/custom_components/alexa_media/light.py
```
then just restart home assistant and test

**Comment by Scope666** [comment]
> wget https://raw.githubusercontent.com/lsellens/alexa_media_player/lights/custom_components/alexa_media/light.py

That fixed it ... thanks!!!   Guessing a breaking change in 2024.2 ?

**Comment by martymart8864** [comment]
> > wget https://raw.githubusercontent.com/lsellens/alexa_media_player/lights/custom_components/alexa_media/light.py
> 
> That fixed it ... thanks!!! Guessing a breaking change in 2024.2 ?

Fixed as well! Thanks!!

**Comment by lsellens** [comment]
> > wget https://raw.githubusercontent.com/lsellens/alexa_media_player/lights/custom_components/alexa_media/light.py
> 
> That fixed it ... thanks!!! Guessing a breaking change in 2024.2 ?

not a breaking change it was just referenced by the wrong name in #2183

**Comment by listlesslife** [comment]
I'm having the same issue. The posted fix doesn't work for me. The wget command returns a 404 error with the given URL.

**Comment by lsellens** [comment]
> I'm having the same issue. The posted fix doesn't work for me. The wget command returns a 404 error with the given URL.

Unless you are still on a really old version it shouldn't be related to this. This PR got merged a while ago. Do you have any error logs? Probably need to make a new issue report with the errors you're getting.

**Comment by lsellens** [comment]
@listlesslife I just double checked and my son's Glow isnt working anymore either. Not really getting anything in the logs and I don't have time to mess with it at the moment. I would suggest you turn on debug logs and try switching the light state and posting a bug report with logs to alexa integration.
