### ISSUE TITLE
Missing support for Danfoss Thermostats

### ISSUE THREAD

**Issue by Lemming16** [alandtse/alexa_media_player#2192]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
When adding my account to the integration, all my room thermostats (Actual/setpoint) are not appearing in the device list.

**Describe the solution you'd like**
Add support for Danfoss Thermostats, as they are working fine in Alexa App.

Debug log:
[home-assistant_alexa_media_2024-02-18T13-17-34.849Z.log](https://github.com/alandtse/alexa_media_player/files/14322980/home-assistant_alexa_media_2024-02-18T13-17-34.849Z.log)

**Comment by laus2** [comment]
I have the same problem with the Danfoss devices.
It working fine in the Alexa app.
some screen dump attached..
[Alexa-Danfoss.pdf](https://github.com/alandtse/alexa_media_player/files/14436971/Alexa-Danfoss.pdf)
