### ISSUE TITLE
Detected that custom integration 'alexa_media' accesses hass.components.group

### ISSUE THREAD

**Issue by holdestmade** [alandtse/alexa_media_player#2203]
**Describe the bug**

Detected that custom integration 'alexa_media' accesses hass.components.group. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from group directly at custom_components/alexa_media/notify.py

**To Reproduce**

Install 2024.3.0b5

**Expected behavior**

NA

**Screenshots**

NA>

**System details**

- Home-assistant (version): 2024.3.0b5
- alexa_media (version from `const.py` or HA startup): 4.9.2
- alexapy (version from `pip show alexapy` or HA startup): 4.9.2
- Amazon [2FA is enabled]: Yes

**Logs**
```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:156
First occurred: 4:51:57 pm (1 occurrences)
Last logged: 4:51:57 pm

Detected that custom integration 'alexa_media' accesses hass.components.group. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from group directly at custom_components/alexa_media/notify.py, line 240: entities.extend(self.hass.components.group.expand_entity_ids(entities)), please create a bug report at https://github.com/alandtse/alexa_media_player/issues
```
**Additional context**

**Comment by alandtse** [comment]
Thanks!

**Comment by Bikervossibaer** [comment]
I also get the identical error message "Detected that custom integration...".

I also receive another error message:

Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:358
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 16:19:40 (1 Vorkommnisse)
Zuletzt protokolliert: 16:19:40

Error while setting up alexa_media platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 358, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 630, in async_add_entities
    or not any(entity.should_poll for entity in entities)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 630, in <genexpr>
    or not any(entity.should_poll for entity in entities)
               ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/sensor.py", line 591, in should_poll
    return not (self.hass.data[DATA_ALEXAMEDIA]["accounts"][self._account]["http2"])
                ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by andyktaylor** [comment]
Same issue. Does rolling back HA version work?

**Comment by say1897** [comment]
Not in my case

**Comment by drizuid** [comment]
> Same issue. Does rolling back HA version work?

it is just a warning, it still works. if yours isn't working, it's likely another issue.
