### ISSUE TITLE
For each echo device and music group, the "..._repeat_switch" and "..._shuffle_switch" entities are unavailable

### ISSUE THREAD

**Issue by ColinKlayer** [alandtse/alexa_media_player#2214]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Each echo device is showing the status of "..._repeat_switch" and "..._shuffle_switch" entities as unavailable

**To Reproduce**

1. Go to Settings>Integrations>Alexa Media Player
2. Click on [#count] entities to see all entities
3. Scroll down to view list of all related entites
4. See error saying unavailable next to every switch is a repeat_switch or shuffle_switch

**Expected behavior**

The "..._repeat_switch" and "..._shuffle_switch" entities as unavailable for each device. 

**Screenshots**

![image](https://github.com/alandtse/alexa_media_player/assets/3522673/8f13e83e-c7ec-4d31-8ee5-3aaa2eb854b7)
![image](https://github.com/alandtse/alexa_media_player/assets/3522673/8a828fa7-c424-4b2e-a1bd-d1b795df011c)
![image](https://github.com/alandtse/alexa_media_player/assets/3522673/3afc8977-f1a8-4c29-8aa7-f48723ae3f78)

**System details**

- Home-assistant (version): 2024.3.1
- alexa_media (version from `const.py` or HA startup): 4.9.2
- alexapy (version from `pip show alexapy` or HA startup): 1.27.10
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) Yes

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).
[cleaned_home-assistant_alexa_media.log](https://github.com/alandtse/alexa_media_player/files/14654437/cleaned_home-assistant_alexa_media.log)

**Additional context**

This is true for brand name echo devices, echo speaker groups, and third-party echo devices (Polk Audio Sound bar). From my individual perspective, I am fine with these entity types being deprecated if it comes to that.

**Comment by alandtse** [comment]
They're only enabled when playing supported media.

**Comment by ColinKlayer** [comment]
Okay. That makes sense. Thanks.
