### ISSUE TITLE
Issue with template forwarding

### ISSUE THREAD

**Issue by Krispkiwi** [alandtse/alexa_media_player#2217]
**Describe the bug**

Kia ora, there appears to be a problem with the way templates are handed with this integration. It's not processing the template before sending the notification. This doesn't have any real life consequences that I've noticed but it does trigger an error in the logs. See https://github.com/home-assistant/core/issues/72287 

**To Reproduce**

1. Create a template sensor in helper'
2. Reference this template in a notify message
3. Check logs

**Expected behavior**

No error should occur in the logs for every notification

**Screenshots**

![image](https://github.com/alandtse/alexa_media_player/assets/72541572/70b2ed54-3118-45f4-a63e-368744006962)

**System details**

- Home-assistant version: 2023.3.1
- alexa_media player version: 4.9.2
- Amazon [2FA is enabled]: Yes

**Comment by alandtse** [comment]
This is a ha warning that you can't use templates in the future in notifications. I'll mark this as an enhancement request if anyone cares about templates and wants to figure out the alternatives.
