### ISSUE TITLE
this device sensors not update when I create a timer or an alarm on my phone

### ISSUE THREAD

**Issue by multinet33** [alandtse/alexa_media_player#2218]
Alexa integration creates "this_device" (for the phone app) sensors for next_reminder, next_alarm, next_timer and do not disturb and media_palyer :all is OK for that

I create on my phone an alarm and a reminder and a timer but nothing is updated on "this_device" sensors.

If i create the same on my echo dot : I got the sensors updated

**System details**

- Home-assistant (version):
Home Assistant :
Core 2024.3.0
Supervisor 2024.03.0
Operating System 12.1
Interface utilisateur 20240306.0

HACS Alexa media player v4.9.2 @alandtse @keatontaylor
---> Amazon 2FA fully enabled

Any idea ?

Thank you

**Comment by alandtse** [comment]
Do not randomly ping people. This is your only warning.
