### ISSUE TITLE
500 Internal Server Error - when adding Alexa integration without 2FA

### ISSUE THREAD

**Issue by nomukaiki** [alandtse/alexa_media_player#2222]
**Describe the bug**

Alexa media player stopped working for a few days.

Adding Alexa integration from scratch throws a server error after the code challenge from the amazon autthorization proxy page.

**To Reproduce**

1. Start a new installation of the Alexa integration
2. Follow the HA Alexa login form (skip the optional 2FA built in codes) and open the proxy
3. Sign up with the Amazon credentials and complete the code challenges
4. See error on: https://the.ha.domain:8123/auth/alexamedia/proxy/verify

**Expected behavior**

If this always throws a 500 Internal Server error, it would be ideal to make the Built-in 2FA codes field to be mandatory.

**Screenshots**

![image](https://github.com/alandtse/alexa_media_player/assets/6306289/6bdccc85-1d0d-4f46-9573-16fedaa1235d)

**System details**

- Home-assistant (version): all versions since 2024.2 up to 2024.3.4
- alexa_media (version from `const.py` or HA startup): [4.9.2]
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). : N

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

![Screenshot 2024-03-27 at 18 52 48](https://github.com/alandtse/alexa_media_player/assets/6306289/7ef1efe9-915d-4336-9b3e-a6f03c72c1b0)

**Additional context**

Versions of HA back from 2024.2 still have the same issue.

**Comment by allthepies** [comment]
Exactly the same issue for me.

**Comment by exilon** [comment]
Me too

**Comment by eldemo78** [comment]
Same error here. Any solution?

**Comment by cyhyryiys** [comment]
Same here.

**Comment by Francky0666** [comment]
Same here.

**Comment by TomOElpatron** [comment]
Same here iv tried everything cant get it to work. 
reinstalled HA
changed browser
readded 2fa app about ten times 
tried local url for home assistant access and nabu casa
turned off any add blockers or anti virus and pop up blockers
all i get is 500 internal server error on captcha 

Anyone have any other ideas

**Comment by nomukaiki** [comment]
> Same here iv tried everything cant get it to work. reinstalled HA changed browser readded 2fa app about ten times tried local url for home assistant access and nabu casa turned off any add blockers or anti virus and pop up blockers tried turning off ipv6 as i saw this work for some all i get is 500 internal server error on captcha
> 
> Anyone have any other ideas

Make sure that you fill in the `Built-in 2FA codes` field with your Amazon generated authenticator keys. It's no 6 digits, it's a long value.

**Comment by TomOElpatron** [comment]
Yup add an extra app in the 2fa amazon page and then past the long key in. That part works it’s when we then pop up and log in and when you put the captcha in it always says 500 internal server error

**Comment by allthepies** [comment]
I got this working!  Turns out I was using the wrong Amazon password to login (oops!).  With the correct password supplied I get the authenticator code screen presented rather than the captcha.  Enter the code form the authenticator app and the add-in was installed successfully.

**Comment by apbarratt** [comment]
Yep, same here, turns out this is the error you get when the wrong password is used and Amazon doesn't tell you you've got the wrong password, just shows the captcha screen then you get redirected back to HA to find the 500 error.

**Comment by TomOElpatron** [comment]
Hey 

Thanks for the reply, I'll try reset the password and see if it works. Will let everyone know

**Comment by TomOElpatron** [comment]
You are champions , thanks so much that was the problem. I reset the password and all worked

**Comment by alandtse** [comment]
2FA is mandatory. There is no way to log in without 2FA. If it works for you great. Otherwise, it's proceed at your own risk.

**Comment by nomukaiki** [comment]
You could at least accept the suggestion that I raised because many people
fall I. The trap of the 500 error.
Just make the field of the authenticator key mandatory and that will help a
lot of people.

Thanks
Joao
