### ISSUE TITLE
Deprecation warning custom integration alexa_media calls async_add_job

### ISSUE THREAD

**Issue by fwmarcel** [alandtse/alexa_media_player#2225]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Home Assistant issues the following warning

> Detected that custom integration 'alexa_media' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://
> developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/alexa_media/__init__.py, line 625: hass.async_add_job

**System details**

- Home-assistant (version): 2024.4.0
- alexa_media (version from `const.py` or HA startup): v4.9.2

**Comment by micium** [comment]
The message is also reported for media_player.py:

Detected that custom integration 'alexa_media' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/alexa_media/media_player.py, line 188: hass.async_add_job(, please create a bug report at https://github.com/alandtse/alexa_media_player/issues

**Comment by danielgoepp** [comment]
Same issue, but I didn't find this right away due to the lack of details in the subject. Who can edit subject here to make it a bit more descriptive and spelled correctly? Perhaps something like: 

Deprecation warning custom integration alexa_media calls async_add_job

This will avoid confusion with other related issues like #2229

**Comment by hcassus** [comment]
Does it make sense to only change `custom_components/alexa_media/media_player.py:188` to `async_create_task` and we'd already be fine?

**Comment by Marcoletto** [comment]
I could think that we will find a new firmware with that problem fixed?

'''
Registratore: homeassistant.helpers.frame
Fonte: helpers/frame.py:188
Prima occorrenza: 12 aprile 2024, 20:56:14 (4 occorrenze)
Ultima registrazione: 12 aprile 2024, 20:58:46

Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'alexa_media' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/alexa_media/__init__.py, line 625: hass.async_add_job(, please create a bug report at https://github.com/alandtse/alexa_media_player/issues
Detected that custom integration 'alexa_media' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/alexa_media/media_player.py, line 188: hass.async_add_job(, please create a bug report at https://github.com/alandtse/alexa_media_player/issues
Detected that custom integration 'alexa_media' accesses hass.components.group. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from group directly at custom_components/alexa_media/notify.py, line 240: entities.extend(self.hass.components.group.expand_entity_ids(entities)), please create a bug report at https://github.com/alandtse/alexa_media_player/issues
'''

**Comment by Marcoletto** [comment]
Some news?
I've a several numbers of different issues with this integration.

Consider that it's a main integration in HA...
