### ISSUE TITLE
Deprecation warning  custom integration 'alexa_media' accesses hass.components.cloud

### ISSUE THREAD

**Issue by philbring** [alandtse/alexa_media_player#2229]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Home Assistant issues the following warning

> Detected that custom integration 'alexa_media' accesses hass.components.cloud. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from cloud directly at custom_components/alexa_media/config_flow.py, line 141: hass_url: str = get_url(self.hass, prefer_external=True), please create a bug report at https://github.com/alandtse/alexa_media_player/issues

**System details**

- Home-assistant (version): 2024.4.1
- alexa_media (version from `const.py` or HA startup): 4.9.2

**Comment by patrickgmail** [comment]
Same for me today:
`2024-04-14 20:56:11.596 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'alexa_media' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/alexa_media/__init__.py, line 625: hass.async_add_job(, please create a bug report at https://github.com/alandtse/alexa_media_player/issues`

**Comment by javiges** [comment]
Will there be a solution?

**Comment by bernardesarthur** [comment]
I don't think so to soon.

**Comment by Petro31** [comment]
@alandtse This was fixed upstream.  Close please.
