### ISSUE TITLE
Add Integration for Alexa Alarms REST API to Manage Alarms

### ISSUE THREAD

**Issue by arielwulkan** [alandtse/alexa_media_player#2232]
### Is your feature request related to a problem? Please describe.
I frequently find myself needing to manage my Alexa alarms directly from Home Assistant, but currently, the "alexa_media_player" integration lacks the functionality to interact with Alexa alarms. This means every time I need to set or edit alarms, I have to switch to the Amazon Alexa app, which is inconvenient and disrupts the workflow of managing all smart home components from a single interface.

### Describe the solution you'd like
I would like the "alexa_media_player" integration to include support for managing Alexa alarms via the Alexa Alarms REST API. This integration should allow users to create, update, delete, and query Alexa alarms directly from Home Assistant. This would provide a seamless experience and fully integrate Alexa's alarm functionality into the Home Assistant ecosystem, enhancing the usability and functionality of both platforms.

### Describe alternatives you've considered
As an alternative, I have considered using other automation tools within Home Assistant to trigger events that simulate alarm behaviors, but these do not integrate with the actual Alexa alarms and lack the native functionality and ease of use that direct integration would provide. Additionally, using voice commands through Alexa-enabled devices is another workaround, but it lacks the automation and scheduling capabilities that could be achieved through API integration.

### Additional context
This feature would replicate the functionality available in the Amazon Alexa app, where users can manage their alarms. Including this in the "alexa_media_player" would align with the project's goal of mirroring the app's capabilities within Home Assistant. Here is the link to the official Alexa Alarms REST API documentation for reference: [Alexa Alarms REST API](https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/avs-rest-alarms.html).

**Comment by Geek-MD** [comment]
I really need it too, please

**Comment by danielbrunt57** [comment]
The [Alexa Alarms REST API](https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/avs-rest-alarms.html) link no longer works.

![image](https://github.com/user-attachments/assets/76dac54a-44ec-4aac-a47e-76f9a04d20b8)

**Comment by danielbrunt57** [comment]
The only API operation I can find now is:
![image](https://github.com/user-attachments/assets/7531d768-dad2-44cd-9691-5071dedc0498)
which is not terribly useful...
