### ISSUE TITLE
Add text only notifications for devices with a screen

### ISSUE THREAD

**Issue by Geek-MD** [alandtse/alexa_media_player#2238]
**Is your feature request related to a problem? Please describe.**
I love sending TTS notifications to my Alexa devices, but sometimes it would be nice to have a text only notification for devices with a screen, like Echo Show 5, Echo Show 8 or Echo Show 10.

**Describe the solution you'd like**
A text only notification, that you have to dismiss to get rid of it. This can be useful to trigger other automations or actions in Home Assistant (HA).

**Describe alternatives you've considered**
What I'm trying to do is get rid of Alexa Alarms, because they can´t be configured only on work days, so I want to create my alarms in HA, use media_player service to play a sound until the text notification is dismissed.

**Additional context**
No additional context.

**Comment by alandtse** [comment]
Does the Alexa all allow this?

**Comment by Geek-MD** [comment]
Yep, TTS and announcements are managed as sound and text in devices with a screen. I don't know how to check Alexa API documentation, and I'm not a programmer. If it's possible I will be grateful, if it's not possible I'll be grateful anyway.

**Comment by alandtse** [comment]
Yes I'm aware that you can send audio and text via the component. https://github.com/alandtse/alexa_media_player/wiki/Configuration%3A-Notification-Component.  I was asking if they added functionality to only send text in the app. If it doesn't exist in the app, we can't do it.
