### ISSUE TITLE
Missing `hide_serial()` while output `serial` into log

### ISSUE THREAD

**Issue by nevercodecorrect** [alandtse/alexa_media_player#2255]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

The serial in this line of [code](https://github.com/alandtse/alexa_media_player/blob/969c00b84600c01dcb7d8285908266a59f6c04ee/custom_components/alexa_media/__init__.py#L1101) is directly output to log without being sanitized by `hide_serial()` function

**To Reproduce**

N/A

**Expected behavior**

The serial should be obfuscated like other log statements.

**Screenshots**

N/A

**System details**

N/A

**Logs**
N/A

**Additional context**

N/A

**Comment by alandtse** [comment]
Thanks for catching that.
