### ISSUE TITLE
All Notify.alexa_device_name entities have disappeared 

### ISSUE THREAD

**Issue by 21Development** [alandtse/alexa_media_player#2259]
**Describe the bug**

All of my notify.echo.device entities have disappeared since I upgraded HA Supervisor. 

**To Reproduce**

Goto Settings / Entities and no longer see listing for notify.name.of.alexa.devices and all automations that use the service show an error.

Going to dev tools / service I can choose the notify service for a Alexa device, but when running it throws an error of “ Failed to call service notify.alexa_media_s_echo_dot_g4. expected dict for dictionary value @ data['data']. Got None

**System details**

- Home-assistant (version): 2024.5.2
- alexa_media (version from `const.py` or HA startup): 4.10.0
- alexapy (version from `pip show alexapy` or HA startup): 1.27.10
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

A few days ago, my notifications started repeating the announcement twice. If I ran the automation manually (which calls a notify.alexa_media service), it correctly played, but when automated, it played twice.

**Comment by wunderbaum** [comment]
Same here. Pity.

**Comment by alandtse** [comment]
Please enable logs or there's no way for anyone to work on this. I'll add labels once it's clear there's something we can do.

**Comment by zibous** [comment]
@alandtse 
Thanks, no a fresh installation Homeassistant (latest) on Docker, no other components only alexa_media.
Used amazon.de, 2fa enabled.

Same as in my production Homeassistant. Can't switch on/off any Alexa devices.

Here is the startup log :
[home-assistant_alexa_media_2024-05-10T11-25-29.204Z.log.zip](https://github.com/alandtse/alexa_media_player/files/15274542/home-assistant_alexa_media_2024-05-10T11-25-29.204Z.log.zip)

**Comment by Krispkiwi** [comment]
Same here. I just redownloaded from hacs and they appear to be back

**Comment by ravilares** [comment]
I just restarted the service and it started working again.

**Comment by Nebur692** [comment]
Same error and:


Este error se originó a partir de una integración personalizada.

Registrador: custom_components.alexa_media
Fuente: helpers/update_coordinator.py:347
integración: Alexa Media Player (documentación, problemas)
Ocurrió por primera vez: 14:41:29 (1 ocurrencias)
Último inicio de sesión: 14:41:29

Error fetching alexa_media data: Error communicating with API: Too Many Requests

**Comment by Harway2007** [comment]
gibt es eine Lösung ???

**Comment by apfelklaus** [comment]
Same on my side - also after reboot the Integration failed to setup/load

**Comment by danielbrunt57** [comment]
> Same on my side - also after reboot the Integration failed to setup/load

Is this related to #2288?
Does if load if you select reload integration?

**Comment by CitizenRacer** [comment]
Yes. I added an automation to reload after restart. Sent from my mobileOn Jul 4, 2024, at 9:16 AM, Daniel ***@***.***> wrote:﻿

Same on my side - also after reboot the Integration failed to setup/load

Is this related to #2288?
Does if load if you select reload integration?

**Comment by danielbrunt57** [comment]
@alandtse Please close this.
