### ISSUE TITLE
'alexa_media' calls async_fire from a thread at custom_components/alexa_media/sensor.py

### ISSUE THREAD

**Issue by Marcoletto** [alandtse/alexa_media_player#2264]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Registratore: homeassistant.helpers.frame
Fonte: helpers/frame.py:190
Prima occorrenza: 13:35:17 (1 occorrenze)
Ultima registrazione: 13:35:17

Detected that custom integration 'alexa_media' calls async_fire from a thread at custom_components/alexa_media/sensor.py, line 433: self.hass.bus.async_fire(, please report it to the author of the 'alexa_media' custom integration

**System details**

- Home-assistant (version):
Core
2024.5.3
Supervisor
2024.05.1
Operating System
12.3
Frontend
20240501.1

Alexa Media Player 4.10.0 (last update yesterday)

**Comment by Marcoletto** [comment]
Registratore: homeassistant
Fonte: helpers/frame.py:203
Prima occorrenza: 20:03:00 (2 occorrenze)
Ultima registrazione: 20:50:00

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/sensor.py", line 433, in _trigger_event
    self.hass.bus.async_fire(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1508, in async_fire
    self._hass.verify_event_loop_thread("async_fire")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'alexa_media' calls async_fire from a thread at custom_components/alexa_media/sensor.py, line 433: self.hass.bus.async_fire(. Please report it to the author of the 'alexa_media' custom integration.

**Comment by AlexW75** [comment]
Same here - if you need some info I can provide.

Logger: homeassistant.helpers.frame
Quelle: helpers/frame.py:190
Erstmals aufgetreten: 07:00:00 (4 Vorkommnisse)
Zuletzt protokolliert: 07:45:00

Detected that custom integration 'alexa_media' calls async_fire from a thread at custom_components/alexa_media/sensor.py, line 433: self.hass.bus.async_fire(, please report it to the author of the 'alexa_media' custom integration

**Comment by daknightuk** [comment]
Same here on version  Alexa Media Player 4.10.1
RuntimeError: Detected that custom integration 'alexa_media' calls hass.bus.async_fire from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#hassbusasync_fire at custom_components/alexa_media/sensor.py, line 433: self.hass.bus.async_fire(. Please report it to the author of the 'alexa_media' custom integration.

Home Assistant

    Core 2024.6.1
    Supervisor 2024.06.0
    Operating System 12.3
    Frontend 20240605.0

**Comment by nima-1102** [comment]
+1

Alexa Media Player: v4.10.3

Core: 2024.6.4
Supervisor: 2024.06.2
Operating System:12.4
Frontend: 20240610.1

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184
First occurred: 15:46:34 (1 occurrences)
Last logged: 15:46:34

Detected that custom integration 'alexa_media' calls hass.bus.async_fire from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#hassbusasync_fire at custom_components/alexa_media/sensor.py, line 433: self.hass.bus.async_fire(, please report it to the author of the 'alexa_media' custom integration
```

```
Logger: homeassistant
Source: helpers/frame.py:197
First occurred: 15:46:34 (1 occurrences)
Last logged: 15:46:34

Error doing job: Future exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/sensor.py", line 433, in _trigger_event
    self.hass.bus.async_fire(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1500, in async_fire
    self._hass.verify_event_loop_thread("hass.bus.async_fire")
  File "/usr/src/homeassistant/homeassistant/core.py", line 447, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 159, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 197, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'alexa_media' calls hass.bus.async_fire from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#hassbusasync_fire at custom_components/alexa_media/sensor.py, line 433: self.hass.bus.async_fire(. Please report it to the author of the 'alexa_media' custom integration.
```

**Comment by jocamane** [comment]
+1

Core 2024.6.4
Supervisor 2024.06.2
Operating System 12.2
Frontend 20240610.1

Alexa media player: 4.10.2


THIS WARNING:
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184
First occurred: July 4, 2024 at 20:35:09 (1 occurrences)
Last logged: July 4, 2024 at 20:35:09

Detected that custom integration 'alexa_media' calls hass.bus.async_fire from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#hassbusasync_fire at custom_components/alexa_media/sensor.py, line 433: self.hass.bus.async_fire(, please report it to the author of the 'alexa_media' custom integration

AND THIS ERROR:
Logger: homeassistant
Source: helpers/frame.py:197
First occurred: July 4, 2024 at 20:35:09 (1 occurrences)
Last logged: July 4, 2024 at 20:35:09

Error doing job: Future exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/sensor.py", line 433, in _trigger_event
    self.hass.bus.async_fire(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1500, in async_fire
    self._hass.verify_event_loop_thread("hass.bus.async_fire")
  File "/usr/src/homeassistant/homeassistant/core.py", line 447, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 159, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 197, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'alexa_media' calls hass.bus.async_fire from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#hassbusasync_fire at custom_components/alexa_media/sensor.py, line 433: self.hass.bus.async_fire(. Please report it to the author of the 'alexa_media' custom integration.

**Comment by danielbrunt57** [comment]
Why am I not seeing this error on my system???

**Comment by jocamane** [comment]
> Why have I never seen this error on my system???
> 
> * Are you on HA 2024.7.3 now?
> * * If Yes, Have you upgraded to AMP 4.11.5?
> * * * If Yes, are you still seeing this error??

in my case i have the 2024.6.4 yet.
in this week i install the new version

**Comment by nima-1102** [comment]
> Why have I never seen this error on my system???
> 
> * Are you on HA 2024.7.3 now?
> * * If Yes, Have you upgraded to AMP 4.11.5?
> * * * If Yes, are you still seeing this error??

I use HA 2024.7.3 with AMP 4.11.5, so far (13 hours) I haven't received any error messages. If that changes, I'll report it here.  :+1:

**Comment by danielbrunt57** [comment]
@alandtse @Petro31 
The section of code HA is complaining about in `sensor.py` appears to be related to alarm events (dismissed/snoozed?):

```
    def _process_raw_notifications(self):
        self._all = (
            list(map(self._fix_alarm_date_time, self._n_dict.items()))
            if self._n_dict
            else []
        )
        self._all = list(map(self._update_recurring_alarm, self._all))
        self._all = sorted(self._all, key=lambda x: x[1][self._sensor_property])
        self._prior_value = self._next if self._active else None
        self._active = (
            list(filter(lambda x: x[1]["status"] in ("ON", "SNOOZED"), self._all))
            if self._all
            else []
        )
        self._next = self._active[0][1] if self._active else None
        alarm = next(
            (alarm[1] for alarm in self._all if alarm[1].get("id") == self._amz_id),
            None,
        )
        if alarm_just_dismissed(alarm, self._status, self._version):
            self._dismissed = dt.now().isoformat()
        self._attr_native_value = self._process_state(self._next)
        self._status = self._next.get("status", "OFF") if self._next else "OFF"
        self._version = self._next.get("version", "0") if self._next else None
        self._amz_id = self._next.get("id") if self._next else None

        if self._attr_native_value is None or self._next != self._prior_value:
            # cancel any event triggers
            if self._tracker:
                _LOGGER.debug(
                    "%s: Cancelling old event",
                    self,
                )
                self._tracker()
            if self._attr_native_value is not None and self._status != "SNOOZED":
                _LOGGER.debug(
                    "%s: Scheduling event in %s",
                    self,
                    dt.as_utc(self._attr_native_value) - dt.utcnow(),
                )
                self._tracker = async_track_point_in_utc_time(
                    self.hass,
                    self._trigger_event,
                    dt.as_utc(self._attr_native_value),
                )

    @callback
    def _trigger_event(self, time_date) -> None:
        _LOGGER.debug(
            "%s:Firing %s at %s",
            self,
            "alexa_media_notification_event",
            dt.as_local(time_date),
        )
        self.hass.bus.async_fire(
            "alexa_media_notification_event",
            event_data={
                "email": hide_email(self._account),
                "device": {"name": self.name, "entity_id": self.entity_id},
                "event": self._active[0],
            },
        )
```

I'm not sure if the correct fix is the addition of `@callback`:

```
    @callback
    def _trigger_event(self, time_date) -> None:
        _LOGGER.debug(
            "%s:Firing %s at %s",
            self,
            "alexa_media_notification_event",
            dt.as_local(time_date),
        )
        self.hass.bus.async_fire(
            "alexa_media_notification_event",
            event_data={
                "email": hide_email(self._account),
                "device": {"name": self.name, "entity_id": self.entity_id},
                "event": self._active[0],
            },
        )
```

or changing `self.hass.bus.async_fire` to `self.hass.bus.fire`:

```
    def _trigger_event(self, time_date) -> None:
        _LOGGER.debug(
            "%s:Firing %s at %s",
            self,
            "alexa_media_notification_event",
            dt.as_local(time_date),
        )
        self.hass.bus.fire(
            "alexa_media_notification_event",
            event_data={
                "email": hide_email(self._account),
                "device": {"name": self.name, "entity_id": self.entity_id},
                "event": self._active[0],
            },
        )
```

I'll try to debug it but I need to figure out how to trigger the error on my system...

**Comment by danielbrunt57** [comment]
I just set an alarm for 1 minute from now.  When it occurred I snoozed it and I got the error:
```
Logger: homeassistant
Source: helpers/frame.py:197
First occurred: 10:28:00 PM (1 occurrences)
Last logged: 10:28:00 PM

Error doing job: Future exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/sensor.py", line 434, in _trigger_event
    self.hass.bus.async_fire(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1505, in async_fire
    frame.report_non_thread_safe_operation("hass.bus.async_fire")
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 225, in report_non_thread_safe_operation
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 159, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 197, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'alexa_media' calls hass.bus.async_fire from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#hassbusasync_fire at custom_components/alexa_media/sensor.py, line 434: self.hass.bus.async_fire(. Please report it to the author of the 'alexa_media' custom integration.
```
Let me retry it with the addition of @callback...

**Comment by danielbrunt57** [comment]
I re-ran my test with snoozing an alarm and the error did not occur so I think `@callback` is the correct fix for it.

**Comment by danielbrunt57** [comment]
> > Why have I never seen this error on my system???
> > 
> > * Are you on HA 2024.7.3 now?
> > * * If Yes, Have you upgraded to AMP 4.11.5?
> > * * * If Yes, are you still seeing this error??
> 
> I use HA 2024.7.3 with AMP 4.11.5, so far (13 hours) I haven't received any error messages. If that changes, I'll report it here. 👍

Try dismissing/snoozing an alarm!
