### ISSUE TITLE
Stereo Speaker Pair - incorrect volume_level

### ISSUE THREAD

**Issue by nima-1102** [alandtse/alexa_media_player#2265]
**Describe the bug**

When using Alexa Stereo Speaker Pair (Not multiroom, important), the `volume_level` reported is incorrect. While it is possible to control the volume, initially it shows the correct volume level for both members of the pair. However, after a few seconds, it changes to 0.5. Additionally, the Speaker Pair entity, which consolidates the two members, consistently report a `volume_level` of 0.5 without any changes.

**To Reproduce**

1. Set up an Alexa Stereo Speaker Pair. (In iOS app: Devices -> Add -> Combine speakers -> Stereo pair)
2. Attempt to adjust the volume for the Speaker Pair Entity in HA.
3. Observe the initial correct volume level reported for both members.
4. After a few seconds, notice the volume level report change to 0.5. (Only the reported value changes, the volume itself does not.)
5. Check the Speaker Pair entity, which consistently shows a volume level of 0.5.

**Expected behavior**

The reported "volume_level" should accurately reflect the adjusted volume level of the stereo speaker pair.

**System details**

- Home-assistant (version): 2024.5.3
- alexa_media (version from `const.py` or HA startup): 4.10.0
- alexapy (version from `pip show alexapy` or HA startup): 1.27.10
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n): yes

**Logs**
[home-assistant_alexa_media_2024-05-14T21-25-12.405Z.log](https://github.com/alandtse/alexa_media_player/files/15313957/home-assistant_alexa_media_2024-05-14T21-25-12.405Z.log)

**Additional context**

Created Stereo Speaker Pair (media_player.alexa_pool) - Member Devices:
- media_player.alexa_swimmingpool
- media_player.alexa_unterstand

**Comment by danielbrunt57** [comment]
I have several speaker pairs and I do not see a volume level for the pair, only the individual speakers...

![image](https://github.com/alandtse/alexa_media_player/assets/49846893/3466a267-34a2-477d-86d1-8e750a33dcd9)

**Comment by danielbrunt57** [comment]
@alantse Please close this as a non-issue.

**Comment by nima-1102** [comment]
> I have several speaker pairs and I do not see a volume level for the pair, only the individual speakers...
> 
> 
> 
> ![image](https://github.com/alandtse/alexa_media_player/assets/49846893/3466a267-34a2-477d-86d1-8e750a33dcd9)
> 
> 

You have to play music as an example, only then there is a "volume_level" attribute for the speaker pair entity.

**Comment by danielbrunt57** [comment]
Okay, so I started playing music on my Office pair and the entity in HA updated with volume_level: 0.5:
![image](https://github.com/user-attachments/assets/183ba596-736c-41ad-b494-d035bcfd2f6b)

> Expected behavior
>
> The reported "volume_level" should accurately reflect the adjusted volume level of the stereo speaker pair.

This is not generated by HA, it is pushed from Amazon to HA and we have no control over what Amazon pushes to us.
Your issue is with Amazon, not this integration.  Good luck!

**Comment by danielbrunt57** [comment]
@alandtse Please close this as an Amazon issue, thanks.
