### ISSUE TITLE
Alexa media player integration - installation does not complete

### ISSUE THREAD

**Issue by richard-phil** [alandtse/alexa_media_player#2272]
Hi Everyone,

**IMPORTANT: Please search the issues, including closed issues, and the [FAQ] Checked - nothing Found

**Describe the bug**

during Installation of the a priori last (V4.10.0) version, the installation ( done by UI) send a final error after message "loading next step for alexa media player"
**[u]A BIG THANK YOU[/u]** to those who can direct me towards a solution/track
(I can't find anything on the forum :-()
I must have slag somewhere from an old installation (which worked but which I deleted several months ago because it requires periodic identification keys)
I follow the various updates a priori.
the only big changes since the time it worked:
switching from a Raspberry to a dedicated NUC (with backup upload)
subscription to NabuCasa for external access via https (previously duckdns) or ZeroTier

I would just like to restore this integration to make voice announcements on my DOTS...

**To Reproduce**

I have installed the integration by HACS, (and it is present in custom-components-
to then configure the integration, I go through the UI and enter my amazon.fr identifiers, and the URL to access HA, then the application key (I activated 2FA and retrieved the application key 2FA). {I also tried without the key but same problem}
Amazon verification pages then open which run correctly then I arrive at the message box  "loading next step for alexa media player"
but after several minutes it finish with and message box "Error" 

**Expected behavior**
It should then end up with the list of the Alexa contriolled devices but I got an error

**Screenshots**
all seems ok up to that message box: 
![image](https://github.com/alandtse/alexa_media_player/assets/34893831/695d93ce-d428-4d6e-b1b7-7850f0d73d2d)
which ends after sevral minutes with that error message box:
![image](https://github.com/alandtse/alexa_media_player/assets/34893831/1e998a4f-d0af-4860-8079-bafa414ee29f)

**System details**

- Home-assistant (version):core-2024.5.5
- alexa_media (version from `const.py` or HA startup):"4.10.0"
- alexapy (version from `pip show alexapy` or HA startup): ??? I haven't find it 
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). Yes :

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).
[home-assistant-alexa.log](https://github.com/alandtse/alexa_media_player/files/15471674/home-assistant-alexa.log)

**Additional context**

**Comment by Smooth1337** [comment]
I got the same issue.

**Comment by alandtse** [comment]
Disable IPv6 in HA while installing and see if that helps. You can reenable after.

**Comment by Smooth1337** [comment]
> Disable IPv6 in HA while installing and see if that helps. You can reenable after.

Thank you. That did the trick.
