### ISSUE TITLE
Echo Spot Support

### ISSUE THREAD

**Issue by fabianluque** [alandtse/alexa_media_player#2308]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
Add support for the new Echo Spot device (https://www.amazon.com/All-new-Amazon-Echo-Spot-2024-release-Smart-alarm-clock-with-vibrant-sound-Alexa-Black/dp/B0BFC7WQ6R)

**Describe the solution you'd like**
Currently is not being properly identified, media player entity is missing and manufacturer/model are not populated for the device

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Momentum6890** [comment]
My Echo Spot works after restarting HA.

![Spot 1](https://github.com/user-attachments/assets/aeef9634-b0f5-4d0f-ad2f-6efaedf8d97d)
![Spot 2](https://github.com/user-attachments/assets/96014da6-fa27-4727-98d9-654d8335297f)

**Comment by danielbrunt57** [comment]
@alandtse Please close this
