### ISSUE TITLE
How to play local files or radio streams

### ISSUE THREAD

**Issue by StefanoGiu** [alandtse/alexa_media_player#2321]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
I would like to play:
1) Local files mp3 accessible with local url from the web server
2) Radio stream accessible from the internet: e.g. http://ice07.fluidstream.net:8080/KissKiss.mp3

**Describe the solution you'd like**
Implement the media content type

**Comment by danielbrunt57** [comment]
AMP is only sending commands to the Alexa App in Amazon so what you are requesting is feasibly impossible for this integration to do.  Amazon can't play files from your local web/media server or radio streams from internet (unless there's an Alexa skill for it)...

**Comment by danielbrunt57** [comment]
@alandtse I think this feature request can be closed as "not possible"?  Please review my answer. Thanks!
