### ISSUE TITLE
hass.components.persistent_notification - deprecated in 2024.9

### ISSUE THREAD

**Issue by gavinpbennett** [alandtse/alexa_media_player#2326]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184
First occurred: 10:44:04 (1 occurrences)
Last logged: 10:44:04

Detected that custom integration 'alexa_media' accesses hass.components.persistent_notification. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from persistent_notification directly at custom_components/alexa_media/__init__.py, line 1291: hass.components.persistent_notification.async_dismiss(, please create a bug report at https://github.com/alandtse/alexa_media_player/issues

**Comment by danielbrunt57** [comment]
Thanks for the heads up.  I'm already aware of this and it will rectified soon!
