### ISSUE TITLE
AQM integration seems to be broken since 4.11.*

### ISSUE THREAD

**Issue by TeubyDE** [alandtse/alexa_media_player#2352]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**
When setting up any version of alexa_media_player integration of 4.11.* even with checked "Add with ECHO connected devices" no AQM Entities will be available.

**To Reproduce**
1. Setup HA
2. Install via HACS any version of alexa_media_player with 4.11.*
3. Do the setup process of alexa_media_player
4. check the "Add with ECHO connected devices" checkbox
5. reload it
6. See all Alexa devices with their entities appear in HA
7. No AQM Entities available
8. 

**Expected behavior**
Some AQM  Entities available after checking "Add with ECHO connected devices"

**Screenshots**
I cant to screenshot something that's not there ;)

**System details**
- Home-assistant (version): 2024.7.3
- alexa_media (version from `const.py` or HA startup): any 4.11.*
- alexapy (version from `pip show alexapy` or HA startup): no idear how to check tbh
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n): y

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).:
i am searchign for 30min now. i have no idear how to enable the debug and pull some logs.

**Additional context**
I tested all from the HACS installation available versions (4.11.1, 4.11.2, 4.11.3 and 4.11.4).
Sadly, I am unable to select any version of 4.10 in the installation. But inside [this ](https://community.home-assistant.io/t/integrate-amazon-smart-air-quality-monitor/435717/9) thread, the user "sud" provided the following information on 20.07.2024:
> If someone having issues connecting Amazon AQM with trying all the steps above downgrade Alexa Media Player to the version to v4.10.1 , i was trying everything with v4.11.1 , didn’t work for me , in v4.10.1 all AQM sensors showed up !.

**Comment by SConaway** [comment]
This is being tracked here too: https://github.com/alandtse/alexa_media_player/issues/2344

**Comment by danielbrunt57** [comment]
This should be fixed now in v4.11.5

**Comment by danielbrunt57** [comment]
@alandtse Please close this as a dup of #2344

**Comment by TeubyDE** [comment]
Just installed 4.11.5 - no AQM Entities visible

**Comment by TeubyDE** [comment]
@alandtse would you please reopen this issue?

**Comment by Moxser** [comment]
> @alandtse would you please reopen this issue?

I had the same problem as you, have you enabled the inclusion of devices via echo?

![image](https://github.com/user-attachments/assets/a4f0659a-0a71-4907-adba-93512a2a938c)

**Comment by SConaway** [comment]
@TeubyDE and @Moxser, You might need to turn the option on and off a few times to get it to work too, I had to.

**Comment by Moxser** [comment]
> @TeubyDE and @Moxser, You might need to turn the option on and off a few times to get it to work too, I had to. 

For me now all works well.

**Comment by TeubyDE** [comment]
Okay just tryed @SConaway and it worked after 4th time ^^

Thanks guys!
