### ISSUE TITLE
New Contributor

### ISSUE THREAD

**Issue by alandtse** [alandtse/alexa_media_player#2358]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
Managing issues

**Describe the solution you'd like**
@danielbrunt57 to be able to close.

**Describe alternatives you've considered**

**Additional context**
FYI, added your as a contributor, please use the power responsibly for issue control. For PRs, let's do a 1 week response period. If you don't hear back from me within 1 week of a PR after pinging me, you can move forward. I suggest you take a look at how we've merged them in the past.

@danielbrunt57 Go ahead and close this once you've seen it.

**Comment by danielbrunt57** [comment]
Confirmed,
