### ISSUE TITLE
Temperature No Longer Reported

### ISSUE THREAD

**Issue by 7uAip6** [alandtse/alexa_media_player#2360]
**Describe the bug**

Echo devices that used to support temperature sensor measurements are now being reported as unavailable.  Alexa app is still providing the data.

**To Reproduce**

Constant issue

**Expected behavior**

Temperature should be provided.

**System details**

- Home-assistant (version):  2024.7.0
- alexa_media (version from `const.py` or HA startup):  4.11.5
- alexapy (version from `pip show alexapy` or HA startup): 1.27.10
- Amazon [2FA is enabled]:  Yes

**Comment by danielbrunt57** [comment]
Mine was showing since 2nd last restart...

![image](https://github.com/user-attachments/assets/2215aaae-1c62-4b48-a9d7-cdacfe2cc107)

I just restarted at 3:55:55 am and AMP finished initializing about 3:47 am at which point the sensor was `unavailable`.
Then it popped up at 4:07 so I'll need to get my head inside the code and figure out why it's unavailable until the first poll takes place, which is 10 minutes on my system: `if http2push is connected then poll every scan_interval * 10` - my scan_interval is 60s and http2push is connected.

**Comment by danielbrunt57** [comment]
I'm looking for testers for my current: `[__init__.py.zip](https://github.com/user-attachments/files/16397905/__init__.py.zip)`

**  Note - it is still a WIP but it currently seems to address:

- Extended entities are `unavailable` for the first `10 * scan_interval` seconds if hhtp2push is true until the first poll occurs.
- Error "Too many requests"

**Comment by vjbalex** [comment]
Daniel,
I tried swapping the new file into /config/custom_components/alexa_media, reloaded the Alexa Media integratiom and it would not load. I got an error Notification that the configuration was invalid (Error below). Deleting the Integration entry failed. Tried several times with same results. I restored from a full backup so I'm back to 4.11.5 as released a few days ago.

Error:
Logger: homeassistant.setup
Source: setup.py:322
First occurred: 4:39:59 AM (1 occurrences)
Last logged: 4:39:59 AM

Setup failed for custom integration 'alexa_media': Unable to import component: No module named 'custom_components.alexa_media.exceptions'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 322, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 82, in <module>
    from .exceptions import TimeoutException
ModuleNotFoundError: No module named 'custom_components.alexa_media.exceptions'

**Comment by danielbrunt57** [comment]
Ah, my bad!  I forgot I added the exceptions.py file.  Let's do it this way...
Here is my entire custom_components/alexa_media/ folder: [alexa_media.zip](https://github.com/user-attachments/files/16399083/alexa_media.zip)
If you have any issues with it, rather than restoring from backup, you can just redownload the custom component in HACS which will overwrite custom_components/alexa_media with v4.11.5, and then restart HA..
Thanks.

**Comment by vjbalex** [comment]
OK, did that. Temp sensors did not come back after HA restart. Deleted the Integration entry, set it up, anf NO sensors were available, Waited a couple if minutes and no change. Restarted the integration and all sensors came back except Temp sensors. Deleted the Integration entry, re-configured and all enabled sensors incliding Temps were available. Temp sensors becane Unavailable a few minutes later. Went though the process again and it's been stable for about an hour. I hope I don't have to restart HA anytime soon LOL! Will monitor this and the other fixes as I can and report any further issues.

**Comment by vjbalex** [comment]
Temp sensors available for 2 days qith your beta fix but always become unavailavle upon HA restart requoring deleting the Integration entity and re-configure. I did not find any Too Many Requests or alexa_media fie...errors. I do not have an Echo Glow device to test with. Two Alexa Media player updates in 1 day and neither of them addreses the these issues. You probably have not yet incorporated your fixes in either, I understand that,, just saying too be complete.

**Comment by nobbilie** [comment]
Hello, I also have the problem that my temperature sensors from my Echo Dot 5 are no longer available. I have also tried the registration process on Amazon again, but unfortunately this has not been successful.
![TempSens](https://github.com/user-attachments/assets/ec8306f1-1498-4bf5-a510-4732f97f9ae9)

**Comment by Groening91** [comment]
Hello, I had the same problem. You just have to check the box and it will work as usual again


![Screenshot 2024-07-31 171028](https://github.com/user-attachments/assets/3439ab5d-194a-4f6a-ab88-c5a9c94e448e)

**Comment by Werner7272** [comment]
> Hallo, ich hatte das gleiche Problem. Sie müssen nur das Kontrollkästchen aktivieren und es funktioniert wieder wie gewohnt
> 
> ![Screenshot 2024-07-31 171028](https://private-user-images.githubusercontent.com/170741726/353886112-3439ab5d-194a-4f6a-ab88-c5a9c94e448e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDgzNzMsIm5iZiI6MTcyMjQ0ODA3MywicGF0aCI6Ii8xNzA3NDE3MjYvMzUzODg2MTEyLTM0MzlhYjVkLTE5NGEtNGY2YS1hYjg4LWM1YTljOTRlNDQ4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQxNzQ3NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjk1NjkyYjk3MGY4YzczOTI2MzNiMDY3OTlmZWJiYzU3ZDYxYjM0YTdiNjMwYWQ4N2E4YThlN2Y3ODQ4ZTRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cuxbV7nlnN_zbyY8yvU9agS7xzwYkOEBkyKx19Hra04)

Vielen Dank, endlich geht es wieder.

**Comment by cfillyaw** [comment]
> Vielen Dank, endlich geht es wieder.

That seems to get mine working again.  fingers crossed.

**Comment by vjbalex** [comment]
That does not work for me very often. It never brings the Temp sensors back and most times I get the error shown in this pic.
![error](https://github.com/user-attachments/assets/93f3f980-3f22-425d-8581-6c383ec6ea20)

**Comment by nobbilie** [comment]
> Hello, I had the same problem. You just have to check the box and it will work as usual again
> 
> ![Screenshot 2024-07-31 171028](https://private-user-images.githubusercontent.com/170741726/353886112-3439ab5d-194a-4f6a-ab88-c5a9c94e448e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTEwMzcsIm5iZiI6MTcyMjQ5MDczNywicGF0aCI6Ii8xNzA3NDE3MjYvMzUzODg2MTEyLTM0MzlhYjVkLTE5NGEtNGY2YS1hYjg4LWM1YTljOTRlNDQ4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQwNTM4NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjYwMGMwMzVkY2RkZTI1YzExNTc1MmE0NzM0MWJkYTUyMGViYzQ2NjRlYjI3NzQ0N2IwZWQ1NTkyNWRmZDA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EFOeoFMXghwFUiE-LJf0KpeLesn1JK-a8xfhNv0Y_GQ)

Great, that worked.
Thank you very much

**Comment by danielbrunt57** [comment]
> That does not work for me very often. It never brings the Temp sensors back and most times I get the error shown in this pic. ![error](https://private-user-images.githubusercontent.com/176462595/353979114-93f3f980-3f22-425d-8581-6c383ec6ea20.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTM2NjcsIm5iZiI6MTcyMjQ5MzM2NywicGF0aCI6Ii8xNzY0NjI1OTUvMzUzOTc5MTE0LTkzZjNmOTgwLTNmMjItNDI1ZC04NTgxLTZjMzgzZWM2ZWEyMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQwNjIyNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzU1ZmFkMGU4ZWE3MmEzOWIxYTc4YzkzYzQxYzYzNjVjMmI5MTJjYzc2OTE1OTBmYzdjN2RhODRmMTQ0YTlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KZHfRv7JN4G4wIELI7cAClzL-STEoYL4O8bm1_RbV7o)

I've never encountered that error!  Are you on v4.12.1?

**Comment by vjbalex** [comment]
No. I am on 4.11.5 with your patch from earilier in this thread. I never found or recived a repatch compatible with 4.12.1.
For what it is worth the error in the screen shot started after the Temp Sensor and Too Many quests, problems but to be honest I never tried to re-configure before I started having those problems. 
The issues do co-incide with the configuration settings never surviving an HA  restart. which is why I started having to re-config. I have not neen able to connect circumstances about why I get the error most times but not every time when doing the re-config.

**Comment by 7uAip6** [comment]
Why is this marked as resolved?

**Comment by danielbrunt57** [comment]
Please try v4.12.5...

**Comment by vjbalex** [comment]
Tried 4.12.5 fussing with it all day. It's unfortunate that the Integration entity STILL does not survive an HA  restart which forces me to have to reconfigure EVERY time. I have deleted and reconfigured so many times Amazon locked me out for 24hrs due to too many OTP requests. I'm also seeing the same new problems with 4.12.5 and HA 2024..8.0 others have already reported.

**Comment by eduardokabello** [comment]
After update HA to 2024.08 and integration Alexa Media Player to 4.12.6, the temperature sensor is gone.

**Comment by eduardokabello** [comment]
> > After update HA to 2024.08 and integration Alexa Media Player to 4.12.6, the temperature sensor is gone.
> 
> Everything is broken after 2024.08 update. There is another thread that tells how to tweak one line in a file to correct.

Are you talking about manifest.json file? ("requirements": ["alexapy==1.28.2", "packaging>=20.3", "wrapt>=1.14.0"],)

If so, I've already made the changes.

**Comment by cfillyaw** [comment]
> > > After update HA to 2024.08 and integration Alexa Media Player to 4.12.6, the temperature sensor is gone.
> > 
> > 
> > Everything is broken after 2024.08 update. There is another thread that tells how to tweak one line in a file to correct.
> 
> Are you talking about manifest.json file? ("requirements": ["alexapy==1.28.2", "packaging>=20.3", "wrapt>=1.14.0"],)
> 
> If so, I've already made the changes.

Yes, that is what I was referring to.  I made that change and my integration loaded successfully and the temp sensors are working for the time being.

**Comment by 7uAip6** [comment]
Hello.  Why was this closed?  The temperature issue still persists.

**Comment by danielbrunt57** [comment]
> Hello. Why was this closed? The temperature issue still persists.

The issue was closed as the temperature sensors of echo devices do show once you've enabled the `Include devices connected via Echo` option.

![Screenshot_20240808_155054_Home Assistant](https://github.com/user-attachments/assets/7378c3f8-6669-42b8-b867-21cd915a0233)

![Screenshot_20240808_155054_Home Assistant](https://github.com/user-attachments/assets/f948518d-436d-4071-8798-ffab69f866f3)

![Screenshot_20240808_153642_Home Assistant](https://github.com/user-attachments/assets/2d675ebb-3a75-4895-bc4b-e089bf4ebf12)

![Screenshot_20240808_153734_Home Assistant](https://github.com/user-attachments/assets/fc1ed74e-09c4-47eb-bc9c-c4a4bf083224)

**Comment by vjbalex** [comment]
I know to check the Include devices connected via Echo box. However, the temperatures still do not show, are unavailable unless I delete the Integration entity and reset it up. Trying the reconfig option and checking the box results in a string error in the Include and exclude fields. IMHO it is still broken.
  

  

  

  
  
  
  
  
>

**Comment by godbouy** [comment]
The issue may be closed but the problem is not fixed. My Amazon Air Quality Monitor works fine with the Alexa app but it does not appear in the Alexa HA integration. It was working fine a month or so ago but then just quit. I have tried to uninstall and re-install with no luck. I have followed all instructions including ticking the Echo device box but I get no joy. It's a shame since it was fine before but just went away...

**Comment by danielbrunt57** [comment]
> The issue may be closed but the problem is not fixed. My Amazon Air Quality Monitor works fine with the Alexa app but it does not appear in the Alexa HA integration. It was working fine a month or so ago but then just quit. I have tried to uninstall and re-install with no luck. I have followed all instructions including ticking the Echo device box but I get no joy. It's a shame since it was fine before but just went away...

This issue was for `Echo devices that used to support temperature sensor measurements are now being reported as unavailable` and _Amazon Air Quality Monitor_ devices are not _Echo_ devices with temperature sensor.

**Comment by godbouy** [comment]
I am sorry that I am in the wrong area, my issue is not with an Echo device but with an Amazon Air Quality Monitor. It used to work but no more.

**Comment by klingklang76** [comment]
I have the same issue (temperature sensor of echo dot 5 shows for a few minutes/hours and then disappears until configuration is reloaded), so I figured out a workaround that's been working for a few days now: a simple automation that, as soon as the temperature sensor goes unavailable, automatically reloads the integration. Works for me!

`alias: Refresh echo dot temperature sensor
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.echo_dot_xxxxxx_temperature
    to: unknown
  - platform: state
    entity_id:
      - sensor.echo_dot_xxxxxx_temperature
    to: unavailable
condition: []
action:
  - action: homeassistant.reload_config_entry
    target:
      entity_id: sensor.echo_dot_xxxxxx_temperature
    data: {}
mode: single`
