### ISSUE TITLE
[Regression] TTS broken when using service tts.speak

### ISSUE THREAD

**Issue by qJake** [alandtse/alexa_media_player#2369]
**Describe the bug**

When using service `tts.speak`, Alexa responds with the following:

> To send TTS, set public url in integration configuration.

I have removed and reconfigured my AMP integration and confirmed my public URL is in fact set.

**To Reproduce**

1. Use a custom TTS provider, such as OpenAI TTS.
2. Create a service call:  
    ```yaml
    service: tts.speak
    data:
      cache: true
      media_player_entity_id: media_player.sample_alexa_device
      message: This is a sample TTS voice.
    target:
      entity_id: tts.openai_alloy
    ```
3. Call the service.
4. Alexa says "To send TTS, ..."

**Expected behavior**

Prior to the regression, the TTS audio would play correctly from the TTS service. It no longer does.

**Screenshots**

![image](https://github.com/user-attachments/assets/ecc35d71-10de-4b27-a6e8-b6d12cdbb9a7)

**System details**

- Home-assistant (version): 2024.7.3
- alexa_media (version from `const.py` or HA startup): 4.11.5
- alexapy (version from `pip show alexapy` or HA startup): N/A - Default (Installed with HACS, not manually managed)
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account): Yes

**Logs**

```
Logger: custom_components.alexa_media.media_player
Source: custom_components/alexa_media/media_player.py:1423
integration: Alexa Media Player ([documentation](https://github.com/alandtse/alexa_media_player/wiki), [issues](https://github.com/alandtse/alexa_media_player/issues))
First occurred: July 27, 2024 at 4:17:57 PM (18 occurrences)
Last logged: 8:33:58 PM

To send TTS, set public url in integration configuration Please see the alexa_media wiki for details.https://github.com/alandtse/alexa_media_player/wiki/Configuration%3A-Notification-Component#use-the-notifyalexa_media-service
```

**Additional context**

This used to work recently (within 1 week ago), but I'm not sure when it broke - if it was an upgrade to the AMP component or to Home Assistant itself.

**Comment by danielbrunt57** [comment]
> To send TTS, set public url in integration configuration

Let me re-examine this aspect of the integration. I may have inadvertently broken it 🥺

**Comment by Zylazy** [comment]
The same problem here

**Comment by Morpheus2018** [comment]
the same."To send TTS, .." problem answer when sending tts

**Comment by MJHeijster** [comment]
Ah, and here I was trying to figure this out for over half an hour. Glad it's being addressed :)

**Comment by Dare2Code** [comment]
Thanks for that temporary workaround. I hope next hotfix address this.

**Comment by qJake** [comment]
> Here is a temporary work around until the fix is in:
> 
> ```
> 
> # Edit custom_components/alexa_media/const.py make the following edit and restart home assistant
> 
> 
> 
> DEFAULT_PUBLIC_URL = "https://<your_url>/"
> 
> ```
> 
> ![image](https://github.com/user-attachments/assets/421f991a-9bfd-45cd-8c82-6879f4a34d97)
> 
> 
> 
> I noticed some updates from "public_url" to "hass_url" in #2319 , but it looks like not all logic was updated to read the new config option. I didn't have time to dig deeper because I'm on a tight deadline for another project, so this might not be the full picture.

Thanks for this - if I edit this right now, will it just get replaced/fixed when the next HACS release installs? I just don't want to break anything in HACS if I edit this manually.

**Comment by pippo73** [comment]
> Here is a temporary work around until the fix is in:
> 
> ```
> # Edit custom_components/alexa_media/const.py make the following edit and restart home assistant
> 
> DEFAULT_PUBLIC_URL = "https://<your_url>/"
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/16408070/353436634-421f991a-9bfd-45cd-8c82-6879f4a34d97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNjM3MjUsIm5iZiI6MTcyMjM2MzQyNSwicGF0aCI6Ii8xNjQwODA3MC8zNTM0MzY2MzQtNDIxZjk5MWEtOWJmZC00NWNkLThjODItNjg3OWY0YTM0ZDk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE4MTcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZDkwNmUyZWY3MmVhMjhjNjA1YjU2NGU4NmRmY2QxOTYwZWRmNTZhN2MwMzFmNjEyYTFlOTJjMzA2NjQ5ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4EAfcJPMb7z8DZPDGyTCdhu6CUWjNHnmRrYts1iXM6E)
> 
> I noticed some updates from "public_url" to "hass_url" in #2319 , but it looks like not all logic was updated to read the new config option. I didn't have time to dig deeper because I'm on a tight deadline for another project, so this might not be the full picture.

I would like to thank @cw-cdz for the temporary hack. Hope @alandtse will take in concideration this "solution" to fix the problem with the next release of this integration.

@qJake I hope the developer will consider this for the next release ;-)

**Comment by qJake** [comment]
Okay, so I made that code update, but I'm getting a different error - Alexa now says:

> *Sorry, I'm having trouble accessing your Simon Says NA skill right now.*

I may have removed it at one point from my account since I didn't recognize it. I've already tried removing/re-setting up my Alexa integration but that didn't work.

Does anyone have a link to this "Simon Says NA" skill, or a screenshot of their Alexa app with this installed so I can see the icon / skill name / publisher, so I can re-add it to my account? If I look for "Simon Says NA", I don't get any results, but if I just look for "Simon Says", too many different variations come up.

**Comment by qJake** [comment]
Nevermind, found it in the source code:

https://gitlab.com/keatontaylor/alexapy/-/blob/dev/alexapy/alexaapi.py?ref_type=heads#L879

> amzn1.ask.1p.saysomething

Stand by... 😁

**Comment by qJake** [comment]
Another quick update - this service call produces the same result ("Sorry...").

```yaml
service: notify.alexa_media_my_alexa_device
data:
  target: platform specific
  data:
    type: tts
  message: >-
    <audio src='___REDACTED___-_tts.openai_tts_alloy_output.mp3'/>
```

**Comment by danielbrunt57** [comment]
> Here is a temporary work around until the fix is in:
> 
> ```
> # Edit custom_components/alexa_media/const.py make the following edit and restart home assistant
> 
> DEFAULT_PUBLIC_URL = "https://<your_url>/"
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/16408070/353436634-421f991a-9bfd-45cd-8c82-6879f4a34d97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NjgzNTgsIm5iZiI6MTcyMjQ2ODA1OCwicGF0aCI6Ii8xNjQwODA3MC8zNTM0MzY2MzQtNDIxZjk5MWEtOWJmZC00NWNkLThjODItNjg3OWY0YTM0ZDk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDIzMjA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlYTFjZjk4NGRiZDQ2MzQ2ZGI2MjIyODE2YzhmODRhZjI0NjNkNTU3Njg1MDMwMzI0MDNiYjEyZDI4MmY4MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._ZqAKzwp4MWrhsQ6qCgAhTvkRnbPemnHSaB9Vw_RnN0)
> 
> I noticed some updates from "public_url" to "hass_url" in #2319 , but it looks like not all logic was updated to read the new config option. I didn't have time to dig deeper because I'm on a tight deadline for another project, so this might not be the full picture.

I think you've hit the nail on the head!  I've download the old 4.10.3 zip file and will do a file-by-file comparison with 4.12.1 of what's different and where and what I screwed up later this evening...

**Comment by qJake** [comment]
Thank you for fixing this quickly! 🎉

**Comment by kristoficko** [comment]
Am I the only one who still has this issue with 4.12.4?

**Comment by kristoficko** [comment]
Thanks Brian,

figured that could be the issue, just now I'm struggling to obtain a working verison, as the latest one 4.12.4 is giving me the "Unknown Error" as seen in #2393

**Comment by kristoficko** [comment]
That's a little bit tricky, as I don't have the URL field visible in the Configure dialog on an already deployed integration (Just the Excluded/Included devices and the time parameters). 
Need to remove and add the integration from scratch? Or am I missing something here?

**Comment by kristoficko** [comment]
Sorry Brian, I didn't realize the field Public URL is version dependent. To recap what I did:

- manually download version 4.11.5 from github = successfully authenticated
- use HACS to download the latest 4.12.4 version = Configure - Public URL field is now available from the UI
- manually download the latest files from github and write over 4.12.4 = overcome issue #2402 🗡️ 

My AMP is working again, thank you so much for your support today!
