### ISSUE TITLE
Latest Update (4.12.1) Lost My Bose Speakers

### ISSUE THREAD

**Issue by BobMac57** [alandtse/alexa_media_player#2370]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Mt 2 Bose speakers (500) now show as unavailable in both Alexa and Third Party

**To Reproduce**

there are no steps...

**Expected behavior**

**Screenshots**

**System details**

- Home-assistant (version):
- alexa_media (4.12.1):
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). Yes, it's enabled

**Logs**
Please provide [logs]nothing in the logs indicating an error or issue

**Additional context**

Disappeared when updated to latest version this morning.

**Comment by BobMac57** [comment]
Deleting and reinstalling seems for now to have fixed this but, I shouldn't have had to do this.

**Comment by danielbrunt57** [comment]
> **Logs**
> Please provide [logs]nothing in the logs indicating an error or issue
