### ISSUE TITLE
deprecated "hass.components.persistent_notification"

### ISSUE THREAD

**Issue by ChristophCaina** [alandtse/alexa_media_player#2382]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**
With HA 2024.8.0b0 I am getting the following deprication warning in the Logs.

```
Detected that custom integration 'alexa_media' accesses hass.components.persistent_notification. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from persistent_notification directly at custom_components/alexa_media/__init__.py, line 1390: hass.components.persistent_notification.async_create(, please create a bug report at https://github.com/alandtse/alexa_media_player/issues
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**

- Home-assistant (version):
- alexa_media (version from `const.py` or HA startup):
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by ChristophCaina** [comment]
as per example on the dev blog from HomeAssistant:

## New example

```
from homeassistant.core import HomeAssistant
from homeassistant.components.persistent_notification import async_create

async def async_setup(hass: HomeAssistant, config):
    """Set up the component."""
    async_create(
        hass, 
        "You're already using the latest version!", 
        title='Important notification'
    )
```

## Old example
```
from homeassistant.core import HomeAssistant

async def async_setup(hass: HomeAssistant, config):
    """Set up the component."""
    hass.components.persistent_notification.async_create(
        "You're already using the latest version!", 
        title='Important notification'
    )
```

**Comment by acburnett** [comment]
Line 30 of init py has a typo, should be async_create instead of async_creat. Integration won't load on new release. Thank you for this integration and all your work!

**Comment by ChristophCaina** [comment]
unfortunately, there are far more issues :-(

fixing the typo let to another error... fixing this to the next one... :-(
I'll try to fix the whole chain now... Sorry...
