### ISSUE TITLE
4.12.4 throwing another error

### ISSUE THREAD

**Issue by ChristophCaina** [alandtse/alexa_media_player#2392]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**
installed 4.12.4 now, but getting the following error:

```
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 9:01:04 AM (1 occurrences)
Last logged: 9:01:04 AM

Error setting up entry christoph@caina.de - amazon.de for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 360, in async_setup_entry
    if await test_login_status(hass, config_entry, login):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 1396, in test_login_status
    async_create_persistent_notification(
TypeError: async_create() missing 1 required positional argument: 'hass'
```

This is due to the change in init.py at line 1396:

```
    async_create_persistent_notification(
        title="Alexa Media Reauthentication Required",
        message=message,
        notification_id=f"alexa_media_{slugify(login.email)}{slugify(login.url[7:])}",
    )
```

it should be something like:
```
    async_create_persistent_notification(
        hass,
        title="Alexa Media Reauthentication Required",
        message=message,
        notification_id=f"alexa_media_{slugify(login.email)}{slugify(login.url[7:])}",
    )
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**

- Home-assistant (version):
- alexa_media (version from `const.py` or HA startup):
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by ChristophCaina** [comment]
after adding the "hass" in my source files, the following error will be logged:

```
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 9:08:28 AM (1 occurrences)
Last logged: 9:08:28 AM

Error setting up entry christoph@caina.de - amazon.de for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 360, in async_setup_entry
    if await test_login_status(hass, config_entry, login):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 1420, in test_login_status
    ] = await hass.config_entries.flow.async_init(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1293, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1323, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/config_flow.py", line 569, in async_step_reauth
    reauth_schema = self._update_schema_defaults()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/config_flow.py", line 807, in _update_schema_defaults
    CONF_HASS_URL, default=self.config.get(CONF_HASS_URL, hass_url)
                                                          ^^^^^^^^
NameError: name 'hass_url' is not defined
```

this is, why i finally reverted my previous changes back completely.... :) with pr #2386

**Comment by ChristophCaina** [comment]
even if the exception is throwing the error for config_flow.py line 807, I think, the initial issue is the definition of the var in this block at line 151 - 155

```
        try:
            hass_url: str = get_url(self.hass, prefer_external=True)
        except NoURLAvailableError:
            hass_url = ""
        DEFAULT_PUBLIC_URL = hass_url
```

fo rme, it looks like the definition will be done in the TRY block, but the integration is already going into the exception block, where only an empty string will be assigned to the var, which is then not defined.

I am not quite sure at the moment, but the definition of the variable will be done in line 151 - 155

```
    async def async_step_user(self, user_input=None):
        # pylint: disable=too-many-branches
        """Provide a proxy for login."""
        self._save_user_input_to_config(user_input=user_input)
        try:
            hass_url = get_url(self.hass, prefer_external=True)
        except NoURLAvailableError:
            hass_url = ""
        DEFAULT_PUBLIC_URL = hass_url
```

I've tried to debug this part of code - moved the variable definition out of the try block and put some logging at that place, but it seems, that this area of code won't be used at all.

Also the whole "init block"
```
    def __init__(self):
        """Initialize the config flow."""
        if self.hass and not self.hass.data.get(DATA_ALEXAMEDIA):
            _LOGGER.info(STARTUP)
            _LOGGER.info("Loaded alexapy==%s", alexapy_version)
```

will not be called, since I don't even have the "STARTUP" log line

but this is way above my experience - and therefore I stopped debugging this further.
In my opinion, the deprication changes should be completely reverted back - to the state of 4.12.1

It should work for most users - except those who are on 2024.8. ...
and the deprication will hit in 2024.9 ...

this is, where we are at the moment... :-(

**Comment by ChristophCaina** [comment]
update:

I tried to debug this further and replaced the "hass_url" in config_flow.py directly with the external URL of my HA installation:

line 810:
```
                vol.Required(
                    CONF_HASS_URL, default=self.config.get(CONF_HASS_URL, "https://h********/")
                ): str,
```
The error is gone, which validates, that getting the Variable from the config / constants or from where ever is not working correctly.

anyway - the integration is still not working (on my setup with HA 2024.8.0b1 - but it should not be an issue with the changes anymore.

BUT:
Now, that this is working, I can still see the following deprication warning in my log:
```
2024-08-03 11:10:33.498 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'alexa_media' accesses hass.components.persistent_notification. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from persistent_notification directly at custom_components/alexa_media/config_flow.py, line 693: self.hass.components.persistent_notification.async_dismiss(, please create a bug report at https://github.com/alandtse/alexa_media_player/issues
```

so the initial reason for the PR is still open and not solved.

```
            self.hass.components.persistent_notification.async_dismiss(
                f"alexa_media_{slugify(email)}{slugify(login.url[7:])}"
            )
```
and the changes from the init file also needs to be considered in the config_flow.py

**Comment by ChristophCaina** [comment]
the next error after trying to fix the deprication from the last comment led to the following exception:

```
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 11:24:42 AM (1 occurrences)
Last logged: 11:24:42 AM

Error setting up entry christoph@caina.de - amazon.de for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 360, in async_setup_entry
    if await test_login_status(hass, config_entry, login):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 1420, in test_login_status
    ] = await hass.config_entries.flow.async_init(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1293, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1323, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/config_flow.py", line 607, in async_step_reauth
    return await self.async_step_user_legacy(self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/config_flow.py", line 497, in async_step_user_legacy
    return await self._test_login()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/config_flow.py", line 698, in _test_login
    self.async_dismiss_persistent_notification(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AlexaMediaFlowHandler' object has no attribute 'async_dismiss_persistent_notification'
```

I think, the easiest way would be a complete refacturing in the end...

And we're finally again at that point, where I gave up to fix that initial deprication.
But - maybe, I am just wrong with my initial attempts to fix this ...

**Comment by danielbrunt57** [comment]
My Hydro is still out so I can't dig into this and the ETA to repair is noon which is 5 hours away...

**Comment by danielbrunt57** [comment]
I think I only modified init so it looks like config_flow needs the same fix?

**Comment by ChristophCaina** [comment]
Hi, I've loaded the changes from the PR #2396 to my installation.
Unfortunately, it is just the same chain of errors as I described above in the comments.

after the changes in the current PR, this is the next issue:

```
Logger: homeassistant.config_entries
Quelle: config_entries.py:604
Erstmals aufgetreten: 10:33:47 (1 Vorkommnisse)
Zuletzt protokolliert: 10:33:47

Error setting up entry christoph@caina.de - amazon.de for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 361, in async_setup_entry
    if await test_login_status(hass, config_entry, login):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 1421, in test_login_status
    ] = await hass.config_entries.flow.async_init(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1293, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1323, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/config_flow.py", line 574, in async_step_reauth
    reauth_schema = self._update_schema_defaults()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/config_flow.py", line 812, in _update_schema_defaults
    CONF_HASS_URL, default=self.config.get(CONF_HASS_URL, hass_url)
                                                          ^^^^^^^^
NameError: name 'hass_url' is not defined
```

**Comment by danielbrunt57** [comment]
I'm working on it but trying to balance the release version with uncommitted PR's and my ongoing edits is a difficult balancing act!  I have my system working again with my edits but, I now have to try and incorporate those changes into a PR to dev via a new PR and that seems to be a mind provoking challenge when it really shouldn't be!  I'm probably doing this PR stuff all wrong!

I've determined that I've modified `__init__.py`, `config_flow.py` & `const.py` plus added a new `exceptions.py` just to complicate my life!!  Here are my current files which you should be to overlay atop a fresh 4.12.4...
[my_alexa_media_changed_files.zip](https://github.com/user-attachments/files/16487192/my_alexa_media_changed_files.zip)

BTW, I've found a nice file compare program called WinMerge that I'm finding helpful in this endeavor, at least with the way that I've been doing it anyway...

**Comment by danielbrunt57** [comment]
And by the way, I *think* the __pycache__ folder has been adding a wrinkle into my mix as I finally noticed that with the way I'm doing this stuff, the compiled binaries are not updating when I replace files so I've recently learned to just delete that folder before I restart HA.  The clue was inconsistent line numbers in HA error messages following a restart!!!

**Comment by ChristophCaina** [comment]
Hi, all right.
I will give it a try and I can then maybe create a PR with the recent changes if it is working on my system... if you want :)

**Comment by danielbrunt57** [comment]
Thanks but I think I would like to do it.  Just let me know if it's working or not...

**Comment by ChristophCaina** [comment]
unfortunately, not really... :-(

the whole chain of exceptions are still showing up.

1. it was the missing "hass" in block 1403-1408 of init.py
2. after adding this, the next error was the undefined "hass_url" in config_flow.py ...

**Comment by danielbrunt57** [comment]
I just added a tweak to strings.json (& translations/en.json)...

**Comment by ChristophCaina** [comment]
can you share the latest changes from strings.json and en.json?
But from the errors I am getting, these should not change anything.

As mentioned, the issue seems to be in the way hass_url will be defined in the config_flow.py

If I am not wrong, this (line 154 to 157) should define the variable hass_url
```
        try:
            hass_url: str = get_url(self.hass, allow_external=False)
        except NoURLAvailableError:
            hass_url = DEFAULT_HASS_URL
```

the problem here in my opinion is, that the hass_url will be defined as string within the try block.
In the except block, we will just fill the hass_url variable with the DEFAULT_HASS_URL...

this is all within the `async def async_step_user()` block of `__init__(self)`
but during my tests - i've added some debug logs here - the whole block was not called.

So as far as I understand, the hass_url variable won't be defined at all.

**Comment by danielbrunt57** [comment]
Here are my current files again which I just now successfully installed & reconfigured the integration with...
[my_current_files.zip](https://github.com/user-attachments/files/16487377/my_current_files.zip)

**Comment by danielbrunt57** [comment]
> If I am not wrong, this (line 154 to 157) should define the variable hass_url
> 
> ```
>         try:
>             hass_url: str = get_url(self.hass, allow_external=False)
>         except NoURLAvailableError:
>             hass_url = DEFAULT_HASS_URL
> ```

My latest files are forcing that to the internal URL and the public URL to the the external URL.  Check my latest files.
I think the other zip was wrong for some reason (too many beers at 4:00 am???)

**Comment by ChristophCaina** [comment]
ok, that:

> now successfully installed & reconfigured

does meet with my thoughts...
It might be, that it really depends on the state of the integration where exactly it is failing.

It could be, that - if you just install the integration - you are not getting into issues that are caused if you try to load an existing configuration - or reconfigure an existing configuration.

**Comment by danielbrunt57** [comment]
With these files, a reconfigure on existing setup should work (I think!).
Like I said, I think the first zip was old somehow as when I looked at it i said WTF?, that's not what I thought I had! and I then overlayed it with my saved files and proceeded with successful config & reconfig.  I suspect that when I removed the integration and restarted, it pulled a fresh copy of 4.12.4, which I wouldn't have expected it to do...

**Comment by danielbrunt57** [comment]
Either that or, one too many beer...

**Comment by danielbrunt57** [comment]
BTW, what time zone are you in/what time is it there?

**Comment by danielbrunt57** [comment]
I committed my last 2 PR's (contributor privilege - I hope Alan doesn't object!) so I can proceed with the next, and hopefully final PR on this, once you confirm my files are okay...

**Comment by ChristophCaina** [comment]
Timezone: Europa/Berlin

1. I just installed a new HomeAssistant VM on 2024.7.x with your recent files.
1.2 I added Alexa_media completely new - and configured it, which is working as expected.

2. I removed alexa_media from my other production system
2.1 and added a fresh version to it.
2.2 I've tried to install the 4.12.4 from HACS again and during the initial config, I got new errors - which are proving issues with aiohttp

```
Logger: aiohttp.server
Quelle: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:426
Erstmals aufgetreten: 14:19:12 (1 Vorkommnisse)
Zuletzt protokolliert: 14:19:12

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 456, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 366, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 413, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/config_flow.py", line 344, in async_step_user
    return await self.async_step_start_proxy(user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/config_flow.py", line 358, in async_step_start_proxy
    str(URL(self.config.get(CONF_HASS_URL)).with_path(AUTH_PROXY_PATH)),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/yarl/_url.py", line 179, in __new__
    raise TypeError("Constructor parameter should be str")
TypeError: Constructor parameter should be str
```
and
```
Logger: homeassistant
Quelle: runner.py:148
Erstmals aufgetreten: 14:19:24 (1 Vorkommnisse)
Zuletzt protokolliert: 14:19:24

Error doing job: Unclosed client session (None)
```

2.3 I replaced the fresh 4.12.4 files with the new files you have provided.
But I am still unable to set the integration up on 2024.8.0

3 I've create a clone of my other test-installation where Alexa_media was working
3.2 and just updated this to 2024.8.0b1
3.3 which is - leading to the SAME errors I've reported earlier.

So ... it is clear now:
The recent changes are working on 2024.7.x but the whole integration will fail with the error chain I've reported with 2024.8.

**Comment by danielbrunt57** [comment]
Ah, 2024.8.x woes...

**Comment by danielbrunt57** [comment]
I guess it's time for me to do battle with it.  But I need some shuteye first...
