### ISSUE TITLE
Echo Temperature not available 2024.8.0

### ISSUE THREAD

**Issue by R1200G** [alandtse/alexa_media_player#2440]
Since the last core update the temperature of my echo devices is not available anymore.

**Comment by danielbrunt57** [comment]
![Screenshot_20240808_153642_Home Assistant](https://github.com/user-attachments/assets/ce39d5f0-789b-43ff-9fac-43de05802336)

![Screenshot_20240808_153734_Home Assistant](https://github.com/user-attachments/assets/d1d2dd20-6c86-46dd-af55-b7db06554e93)

**Comment by R1200G** [comment]
Thank you very much!

**Comment by rosicenko** [comment]
Again not working since mid of September
