### ISSUE TITLE
Air quality sensor not available anymore

### ISSUE THREAD

**Issue by sharkyy** [alandtse/alexa_media_player#2445]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

The air quality monitor reports unavailable for all sensors.

**To Reproduce**

Check existing sensors for the air quality sensor

**Expected behavior**

Air quality sensors should be shown

**Screenshots**

![image](https://github.com/user-attachments/assets/ce8f98cd-77cc-46a7-b8e8-2347d0729e18)

**System details**

- Home-assistant (version): 
Core 2024.8.0
Supervisor 2024.08.0
Operating System 13.0.rc2

- alexa_media (version from `const.py` or HA startup): 4.12.7
- alexapy (version from `pip show alexapy` or HA startup): 1.28.2
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). y

**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by RoP09** [comment]
Probably the same root cause as everyone else has, AMP is not working anymore at all out of the box with the latest HA update.

**Comment by sharkyy** [comment]
Just found solution in https://github.com/alandtse/alexa_media_player/issues/2360
