### ISSUE TITLE
All devices and entities unavailable

### ISSUE THREAD

**Issue by qfina** [alandtse/alexa_media_player#2447]
**Describe the bug**

I have deleted, restarted, and re-added. I am using amazon.com although I am in Spain (amazon.es), because logs showed it expected .com (see below), with 2FA, which works and adds devices, but all devices and entities show as unavailable.

**To Reproduce**

Add Integration
Confirm credentials
Check Device or Entitity
Shows as Unavailable

**Expected behavior**

Devices and entities to be available

**Screenshots**

**System details**

HA 2024.8.0
Alexa Media 4.12.7
Alexapy
2FA is enabled

**Logs**
2024-08-09 14:34:44.592 DEBUG (MainThread) [alexapy.alexalogin] Logged in as s******g@q*******m to amazon.com with id: A3O5I7Y6F1GE4Q
2024-08-09 14:34:44.906 DEBUG (MainThread) [alexapy.alexalogin] Domain amazon.com matches reported account domain: amazon.com

More logs:
[home-assistant_alexa_media_2024-08-09T12-24-07.507Z.log](https://github.com/user-attachments/files/16561322/home-assistant_alexa_media_2024-08-09T12-24-07.507Z.log)

**Additional context**

**Comment by Rappoman** [comment]
Check the closed issue #2433 as the workaround for that may work for you too.

**Comment by qfina** [comment]
Thank you @Rappoman , I had == instead of >=

Resolved!
