### ISSUE TITLE
Add-On Missing Alexa Groups after update

### ISSUE THREAD

**Issue by deano120** [alandtse/alexa_media_player#2449]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Since the most recent update which fixed an authentication error - the add-on now is no longer finding any of my Alexa groups. It also appears that the Amazon API for this is exposing the entities a little differently as they all now have what appears to be a new naming structure.

**To Reproduce**

I reconfigured the add-on after suffering from an auth error after the most recent HA update. Then after the most recent addon update, I was able to re-auth the addon. Since then however, none of my Alexa groups have been found.

I'm unable to actively re-produce the issue - It's just there.

**Expected behaviour**

To see all of my Alexa groups (I have about 5 of them)

**Screenshots**

N/A

**System details**

Core
2024.8.0
Supervisor
2024.08.0
Operating System
12.4
Frontend
20240806.1

- alexa_media (version from `const.py` or HA startup): Which ever is the latest updated new version (08/08/24)
- alexapy (version from `pip show alexapy` or HA startup): Same as above
- Amazon [2FA is enabled] - Yes (https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :

**Comment by deano120** [comment]
Some additional logs I've found:

Logger: homeassistant.components.media_player
Source: helpers/entity_platform.py:364
integration: Media Player ([documentation](https://www.home-assistant.io/integrations/media_player), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+media_player%22))
First occurred: 09:32:39 (1 occurrences)
Last logged: 09:32:39

Error while setting up alexa_media platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/alexa_media/media_player.py", line 155, in async_setup_entry
    if await async_setup_platform(
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/media_player.py", line 123, in async_setup_platform
    await alexa_client.init(device)
  File "/config/custom_components/alexa_media/media_player.py", line 265, in init
    await self.refresh(device, skip_api=True)
  File "/config/custom_components/alexa_media/helpers.py", line 158, in _catch_login_errors
    result = await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/media_player.py", line 570, in refresh
    self._set_authentication_details(device["auth_info"])
  File "/config/custom_components/alexa_media/media_player.py", line 531, in _set_authentication_details
    self._authenticated = auth["authenticated"]
                          ~~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
---------------------------------------------------------------------
Logger: homeassistant.config_entries
Source: config_entries.py:819
First occurred: 11:37:40 (1 occurrences)
Last logged: 11:37:40

Error unloading entry ####@s#####ub.co.uk - amazon.co.uk for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 819, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 1296, in async_unload_entry
    await notify_async_unload_entry(hass, entry)
  File "/config/custom_components/alexa_media/notify.py", line 64, in async_unload_entry
    for account, account_dict in hass.data[DATA_ALEXAMEDIA]["accounts"].items():
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'accounts'

**Comment by deano120** [comment]
More logs:
`Logger: homeassistant.config_entries
Source: config_entries.py:819
First occurred: 09:32:29 (15 occurrences)
Last logged: 15:07:32

Error unloading entry ####@s#######co.uk - amazon.com for alarm_control_panel
Error unloading entry ####@sm#######uk - amazon.com for light
Error unloading entry #####n@sm#########k - amazon.com for binary_sensor
Error unloading entry ######n@s########## - amazon.co.uk for notify
Error unloading entry ######@s######### - amazon.co.uk for notify
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 819, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/notify/__init__.py", line 135, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!`

**Comment by jossada** [comment]
All my alexa devices disappeared after the HA 2024-8 update, how I solved it:
- I went back to the last backup;
- Updated again to 2024-8;
- Updated Alexa integration to 4.12.7;
- I clicked on reconfigure Alexa.
Now everything is working.
![image](https://github.com/user-attachments/assets/cd02f3c8-8522-489d-9208-7bba8a734cc1)
![image](https://github.com/user-attachments/assets/a6423b7e-5564-4d04-a912-789b148d7574)

**Comment by propi62** [comment]
i have the same problem. i have about 30 automations with action: notify.alexa_media_
atm i try to update them to mediaplayer without success.

**Comment by steppi13** [comment]
I had the same problem.
I Updated Alexa integration to 4.12.7 (Like "jossada" said) and started HA new.
Than the integration works.

Thank You @jossada 🙂

**Comment by kchiem** [comment]
On 4.12.7 and 2024.8.0, everything is working except that my AQM devices are now missing.

**Comment by fbnksr** [comment]
I updated to version 4.12.7 of the integration while running Home Assistant 2024.8, but the issue persisted for me. I had to manually apply the hass_url reference fix from #2408 to resolve the problem. However, even after this, not all of my devices are showing up. Has anyone else experienced missing devices after applying the fix, or is there an additional step I might have overlooked?

**Comment by vix66** [comment]
![Cattura](https://github.com/user-attachments/assets/6e4ddb6f-12e4-4d2d-bac6-1f11ef806984)

**Comment by chrisvblemos** [comment]
> I updated to version 4.12.7 of the integration while running Home Assistant 2024.8, but the issue persisted for me. I had to manually apply the hass_url reference fix from #2408 to resolve the problem. However, even after this, not all of my devices are showing up. Has anyone else experienced missing devices after applying the fix, or is there an additional step I might have overlooked?

4.12.7 should have the fix already. What did you change?

**Comment by fbnksr** [comment]
> > I updated to version 4.12.7 of the integration while running Home Assistant 2024.8, but the issue persisted for me. I had to manually apply the hass_url reference fix from #2408 to resolve the problem. However, even after this, not all of my devices are showing up. Has anyone else experienced missing devices after applying the fix, or is there an additional step I might have overlooked?
> 
> 
> 
> 4.12.7 should have the fix already. What did you change?

My issue was that after updating to the latest version (4.12.7) of the Alexa Media Player integration while using Home Assistant 2024.8, the problem was that the configuration failed. I had to manually fix the reference in the config_flow.py line 815 from `public_url`to `hass_url` to get things working. However, even with this fix, not all of my Alexa devices are showing up in Home Assistant.

**Comment by vix66** [comment]
Upgrade to 2024.8.1 and now all work well

**Comment by deano120** [comment]
Just an update for everyone. Most likely un related but very coincidental, after the most recent add on update (the one that broke it)... the reason why my grouped devices were not showing up... the groups had GONE from my alexa app... re-adding them brought them back in HA. Had to redo all my automation again though. 

Spotify Connect had a field day trying to work and process everything today when I realised.
