### ISSUE TITLE
Amazon Air Quality Monitor no longer working after most recent update

### ISSUE THREAD

**Issue by wildfire305** [alandtse/alexa_media_player#2450]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

After most recent update, AQM entities no longer report. Deleted integration and added again with same result.

**To Reproduce**
Existing AQM that was functional became non-functional.
**System details**

- Home-assistant (version): 2024.08.0
- alexa_media (version from `const.py` or HA startup): need help providing this
- alexapy (version from `pip show alexapy` or HA startup): need help providing this
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). Yes
**Logs**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).
It's turned on, but I don't know where they live to provide them.

**Comment by danielbrunt57** [comment]
Have you enabled the option "Include devices connected via Echo"?

**Comment by emby1** [comment]
I have exactly the same problem. I recently upgraded to HA 2024.8.0 and AMP 4.12.7. Unfortunately after the update, all my Amazon Air Quality Monitors are no longer shown in the AMP devices list (although all other Amazon devices, like Alexa and Echo and a couple of tablets are present).
The "Include devices connected via Echo" is selected.

**Comment by chrisvblemos** [comment]
To get the log, just turn off the debug logging. It will auto download the log file.

[Read here for my info.](https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging)

**Comment by wildfire305** [comment]
> Have you enabled the option "Include devices connected via Echo"?

This resolved my issue. The AQM is the only Amazon device I own so I’m not too familiar with their ecosystem. I bought that one because it’s the most affordable CO monitoring device on the market. Everything else measures CO2. I have it next to a wood stove that backdrafts occasionally and this notifies me long before the carbon monoxide detector goes off.
