### ISSUE TITLE
Can't find anymore AMD in HACS

### ISSUE THREAD

**Issue by pbranly** [alandtse/alexa_media_player#2464]
Hi
I would like to reinstall AMD but can't find it anymore in HACS.
What do I make wrong ?
Phil

**Comment by danielbrunt57** [comment]
You need to fix your HACS.
Try removing and reinstalling HACS...

**Comment by pbranly** [comment]
Hi
I did it and succeeded 
I also had to change Amazon.com to amazon.fr robb by make it work for me 
Alexa media player is back !
Thanks 
Phil
