### ISSUE TITLE
Error on Alexa Text To Speach

### ISSUE THREAD

**Issue by Cippo2019** [alandtse/alexa_media_player#2474]
Hi
I have update Alexa to version 4.12.9 (I was on 2024.7 in HA)
it worked perfectly as usual

I hava so update to 2024.8.2 directly (after some time just to testin 4.12.9)
I was on 4.12.8 always without any problems

now Alexa start and i can control alexa ecodot and so on(volume , play), but if I run automation where i can send to Echodot test to speach i get this

Registratore: alexapy.helpers
Fonte: runner.py:190
Prima occorrenza: 23:20:20 (3 occorrenze)
Ultima registrazione: 23:20:20

> alexaapi.run_behavior((<alexapy.alexaapi.AlexaAPI object at 0x7f7eadabdfa0>, {'@type': 'com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode', 'type': 'Alexa.Speak', 'operationPayload': {'deviceType': 'A1RABVCCIKC', 'deviceSerialNumber': 'G6WV', 'locale': 'it-it', 'customerId': 'AYWX', 'textToSpeak': 'Matteo è ora che spegni cazzo', 'target': {'customerId': 'AYWX', 'devices': [{'deviceSerialNumber': 'G6WV', 'deviceTypeId': 'A1RABI4QCIKC'}]}, 'skillId': 'amzn1.ask.1p.saysomething'}}), {'queue_delay': 1.5}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments: ('Login error detected; not contacting API',)

> alexaapi.send_sequence((<alexapy.alexaapi.AlexaAPI object at 0x7f7eadabdfa0>, 'Alexa.Speak'), {'customer_id': 'A2T0A7LNEYWX', 'textToSpeak': 'Matteo è ora che spegni cazzo', 'target': {'customerId': 'AYWX', 'devices': [{'deviceSerialNumber': 'G******6WV', 'deviceTypeId': 'A1RABVCCIKC'}]}, 'skillId': 'amzn1.ask.1p.saysomething', 'queue_delay': 1.5}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments: ('Login error detected; not contacting API',)

> alexaapi.send_tts((<alexapy.alexaapi.AlexaAPI object at 0x7f7eadabdfa0>, 'Matteo è ora che spegni '), {'customer_id': 'A2T0ABNEYWX', 'queue_delay': 1.5}): An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments: ('Login error detected; not contacting API',)

To Reproduce

1. Go to Automation
2. Click on 'my text to speach automation
3. going fo log viewer
4. collect errror

Expected behavior

before update I can hear audio

System details

- Home-assistant (version): 2024.8.2
- alexa_media (version from `const.py` or HA startup): 4.12.9
- alexapy (version from `pip show alexapy` or HA startup):
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n). :   YES ENABLE

thanks a lot

**Comment by Cippo2019** [comment]
I have also saw now into log other erros and that one

Registratore: custom_components.alexa_media
Fonte: custom_components/alexa_media/__init__.py:1345
Integrazione: Alexa Media Player (documentazione, problemi)
Prima occorrenza: 23:32:11 (2 occorrenze)
Ultima registrazione: 23:37:29

Could not remove cookiefile: /config/.storage/alexa_media.anacletot@gmail.com.pickle. Please manually delete the file.

looking into the path I have the file, but before to do something I prefer ask :-)

thanks again

**Comment by 1242scooter** [comment]
Same here

**Comment by danielbrunt57** [comment]
Do as instructed: `Please manually delete the file.`

**Comment by 1242scooter** [comment]
AMP? Then what? Re-install and re-do my fifty entries?

**Comment by 1242scooter** [comment]
Yes, I have 25 Reolink cameras that announce (text-to-speech) on several
Alexa’s, person or vehicle. That is the sole and only purpose of my HA. It
sends a text also. So you see why this is important to me. I wonder if
staying on 7.2 will work in the long term. I have read some have
reinstalled AMP will no luck. Frustrated.

**Comment by danielbrunt57** [comment]
Same error using TTS as #[2448](https://github.com/alandtse/alexa_media_player/issues/2448)
> An error occurred accessing AlexaAPI: An exception of type AlexapyLoginError occurred. Arguments: ('Login error detected; not contacting API',)

**Comment by danielbrunt57** [comment]
> Yes, I have 25 Reolink cameras that announce (text-to-speech) on several Alexa’s, person or vehicle. That is the sole and only purpose of my HA. It sends a text also. So you see why this is important to me. I wonder if staying on 7.2 will work in the long term. I have read some have reinstalled AMP will no luck. Frustrated.

If assigning areas to 50 devices is absolutely a requirement for your system to function, and since AMP's issues with 2024.8.x have not been fully worked out to everyone's satisfaction, I recommend staying put on 2024.7.2.  For how long you might ask?  No idea.  But Python v3.13 is scheduled for release Q4 2024...

**Comment by 1242scooter** [comment]
Thank you

**Comment by Cippo2019** [comment]
> Do as instructed: `Please manually delete the file.`

Hi 
just delete file and I have to reload AMP, or restart HA , or it is not needed ? 

wbr

**Comment by danielbrunt57** [comment]
The warning is only issued when you've deleted the AMP config entry.  It's then that you should delete the pickle file before re-adding the integration again.  No HA restart is necessary.  The file is used by AMP to store cookies in and if it doesn't exist when AMP starts or is reloaded, it recreates it.  But problems can occur if there are incorrect cookies in the file from a previous session.

**Comment by Cippo2019** [comment]
ok thanks
can i delete just the file and stop to that or it is mandatory to remove and redo all steps related to AMP (to be honest i prefer to avoid because i read a lot of comments that not solve also that list of steps)
i have disable polling and now seems to work Text to speech without errors (at least for now)
:-)

**Comment by Cippo2019** [comment]
@danielbrunt57 did you see last comment ? :-) thanks

**Comment by danielbrunt57** [comment]
> ok thanks can i delete just the file and stop to that or it is mandatory to remove and redo all steps related to AMP ? (to be honest i prefer to avoid because i read a lot of comments that not solve also that list of steps) i have disable polling and now seems to work Text to speech without errors (at least for now) :-)

Thinking about what I've come to know, I think it's best to delete AMP, delete the .pickle file then re-add AMP.
You can try deleting the pickle file and just reloading AMP but I don't recall ever having done that.
If things are worse, try restarting HA (since alexapy is always at work in the background).
If still not right, delete AMP, delete the .pickle file and re-add AMP.

**Comment by Cippo2019** [comment]
ok thanks
if i delete AMP and put it back i will have to reconfigure all the entities as before i guess?
i mean like names etc..
