### ISSUE TITLE
Included device (comma separated)/Excluded device (comma separated) are not working as expected

### ISSUE THREAD

**Issue by danielbrunt57** [alandtse/alexa_media_player#2477]
**Describe the bug**

Exclude Devices is excluding more than just the device I want excluded. 
I.e. specifying "Echo Auto" excludes not only "Echo Auto" but also "Echo" since device name "Echo" is in the _string_ "Bedroom,Daniel's Fire,Echo Auto,Mach-E SYNC,Living Room,Main floor,Norton Court,Office,This Device"

**To Reproduce**

Amazon device names  with the issue:  "Echo" and "Echo Auto"
Exclude Devices _string_: "Bedroom,Daniel's Fire,Echo Auto,Mach-E SYNC,Living Room,Main floor,Norton Court,Office,This Device"
I tried `Echo Auto`, `Echo%20Auto` and `Echo\ Auto` but none of these worked.

**Expected behavior**

Only exclude device "Echo Auto" but not device "Echo"

**System details**

- Home-assistant (version): 2024.8.2
- alexa_media (version from `const.py` or HA startup): 4.12.10
- alexapy (version from `pip show alexapy` or HA startup): 1.29.0
- Amazon [2FA/2SV is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n): Y

**Logs**
> 024-08-20 00:13:30.345 DEBUG (MainThread) [custom_components.alexa_media] d****l@b******a: Existing: [] New: ['Garage Echo Dot', 'Living Room Echo Dot Right', 'Office Echo Dot Left', 'Office Echo Dot Right', 'Bedroom Echo Dot Left', 'Kitchen Echo Dot', 'Bedroom Echo Dot Right', 'Echo Show 8', 'Living Room Echo Dot Left']; Filtered out by not being in include: [] or in exclude: ['Echo', 'Echo Auto', 'Office', 'Main floor', 'Mach-E SYNC', 'Bedroom', 'Norton Court', 'Living Room', "Daniel's Fire", 'This Device']

**Comment by MrPiket** [comment]
Something that I also notice in those fields when you do the configuration via the UI is that you cannot leave that field empty. When you click on submit, it doesn't delete the value of that field it goes back with what you have before.
