### ISSUE TITLE
Integration no more loaded after reinstallation: `KeyError: 'public_url'`

### ISSUE THREAD

**Issue by protege323** [alandtse/alexa_media_player#2479]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

Alexa integration will be not loaded after installation

**To Reproduce**

**Expected behavior**

<img width="158" alt="image" src="https://github.com/user-attachments/assets/fd384179-a182-42b3-b27f-b12bc07376aa">

**System details**

- Home-assistant (version): 2024.8.2
- alexa_media (version from `const.py` or HA startup): 4.12.10
- alexapy (version from `pip show alexapy` or HA startup): 1.28.2
- Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n).: yes

**Logs**
Logger: homeassistant.setup
Source: setup.py:416
First occurred: 7:28:08 AM (1 occurrences)
Last logged: 7:28:08 AM

Error during setup of component alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 188, in async_setup
    CONF_PUBLIC_URL: account[CONF_PUBLIC_URL],
                     ~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'public_url'

Who can help?

Thanks

**Comment by 1242scooter** [comment]
following

**Comment by danielbrunt57** [comment]
Did you just upgrade Alexa Media Player?  If so, from what version?

Can you view `/config/.storage/core.config_entries`, search for `alexa_media` and post the contents of that config_entry?
It looks like this:
```
      {
        "created_at": "2024-08-21T08:21:34.897280+00:00",
        "data": {
          "otp_secret": "<redacted>",
          "email": "<redacted>",
          "password": "<redacted>",
          "url": "amazon.com",
          "public_url": " ",
          "scan_interval": 60,
          "queue_delay": 1.5,
          "include_devices": "",
          "exclude_devices": "Bedroom,Daniel's Fire,Echo Auto,Mach-E SYNC,Living Room,Main floor,Norton Court,Office,This Device",
          "extended_entity_discovery": true,
          "debug": false,
          "oauth": {
            "access_token": "<redacted>
            "refresh_token": "<redacted>
            "expires_in": 1724232095.47634,
            "mac_dms": {
              "device_private_key": "<redacted>
              "adp_token": "{enc:<redacted>
            },
            "code_verifier": "-<redacted>",
            "authorization_code": "<redacted>"
          }
        },
        "disabled_by": null,
        "domain": "alexa_media",
        "entry_id": "01J5T0DSHHWJKKTDCZCD375A49",
        "minor_version": 1,
        "modified_at": "2024-08-21T08:21:45.985888+00:00",
        "options": {},
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "title": "<redacted>- amazon.com",
        "unique_id": "<redacted>- amazon.com",
        "version": 1
      }
```

**Comment by protege323** [comment]
I think the version which was running before was 4.12.6 or .7 

Yes Internet URL is configured --> Nabu Casa

` "created_at": "2024-08-21T05:24:29.884934+00:00",
        "data": {
          "otp_secret": "< redacted>",
          "email": "< redacted>",
          "password": "< redacted>",
          "url": "amazon.de",
          "public_url": "< redacted>",
          "scan_interval": 60,
          "queue_delay": 1.5,
          "include_devices": "",
          "exclude_devices": "",
          "extended_entity_discovery": false,
          "debug": false,
          "oauth": {
            "access_token": "< redacted>",
            "refresh_token": "< redacted>",
            "expires_in": 1724221467.591467,
            "mac_dms": {
              "device_private_key": "< redacted>",
              "adp_token": "< redacted>"
            },
            "code_verifier": "< redacted>",
            "authorization_code": "< redacted>"
          }
        },
        "disabled_by": null,
        "domain": "alexa_media",
        "entry_id": "01J5SP9HHW09ZQE3GHWN1RHNJT",
        "minor_version": 1,
        "modified_at": "2024-08-21T05:24:29.884941+00:00",
        "options": {},
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "title": "< redacted> - amazon.de",
        "unique_id": "< redacted> - amazon.de",
        "version": 1`

**Comment by emufan** [comment]
> **To Reproduce**
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> 
> <img alt="image" width="158" src="https://private-user-images.githubusercontent.com/56585967/359760172-fd384179-a182-42b3-b27f-b12bc07376aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTUwNzUsIm5iZiI6MTcyNDMxNDc3NSwicGF0aCI6Ii81NjU4NTk2Ny8zNTk3NjAxNzItZmQzODQxNzktYTE4Mi00MmIzLWIyN2YtYjEyYmMwNzM3NmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA4MTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkYWFiNmU2ZjQzMmNhZDA5MmZmZTIwNWNmYzdkNzExZDBkMmM4ZTg5NGU5Yjg5YzRmOGYxMzgyNmUzY2QyMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HX3-GfZOSqbewuVUNwWAfdQSJ9IfnuA7v2vbZhyIZrc">
> **System details**
> 
> * Home-assistant (version): 2024.8.2
> * alexa_media (version from `const.py` or HA startup): 4.12.10
> * alexapy (version from `pip show alexapy` or HA startup): 1.28.2
> * Amazon [2FA is enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) (y/n).: yes

Had this as well after updating to 2024.8.2 and AMP to 4.12.10 (coming from 4.12.7. 

I then deleted the integration to have a clean start and ended up in problem https://github.com/alandtse/alexa_media_player/issues/2469 that I wasn't able to set up the integration anymore in total.

**Comment by voyagerft** [comment]
in Italy it doesn't work, the reconfiguration pop up appears continuously
![IMG_3799](https://github.com/user-attachments/assets/e3e089bd-23d6-48d6-bc6c-088438dce4be)

**Comment by anthonyCarigny** [comment]
I confirm experiencing the same as @emufan with amazon.fr

**Comment by luizcarlosnery** [comment]
Parou aqui também...
![erroalexa](https://github.com/user-attachments/assets/d4777fdc-ab30-4839-9e9e-e8518ff34995)

**Comment by danielbrunt57** [comment]
> Parou aqui também... ![erroalexa](https://private-user-images.githubusercontent.com/31808320/361600167-d4777fdc-ab30-4839-9e9e-e8518ff34995.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NjEyMjUsIm5iZiI6MTcyNDc2MDkyNSwicGF0aCI6Ii8zMTgwODMyMC8zNjE2MDAxNjctZDQ3NzdmZGMtYWIzMC00ODM5LTllOWUtZTg1MThmZjM0OTk1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDEyMTUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNGQxMTU1OWU4ZWE0YmY0NTYzNzhlODIyNWM5MDNlODExNGM4M2EyMmI4ZDY1ZDViMzBiZWQ1ODIxMzZmOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yW0FpHeB6U99mS7sQSYBKUaGGf_RjtX09OaSRC_quTw)

Entschuldigung, ich verstehe nicht...

**Comment by danielbrunt57** [comment]
Please try editing `__init__.py` lines 151-177 and insert CONF_PUBLIC_URL as follows:
```
                    _LOGGER.debug("Updating existing entry")
                    hass.config_entries.async_update_entry(
                        entry,
                        data={
                            CONF_EMAIL: account[CONF_EMAIL],
                            CONF_PASSWORD: account[CONF_PASSWORD],
                            CONF_URL: account[CONF_URL],
                            CONF_PUBLIC_URL: account[CONF_PUBLIC_URL],
                            CONF_INCLUDE_DEVICES: account[CONF_INCLUDE_DEVICES],
                            CONF_EXCLUDE_DEVICES: account[CONF_EXCLUDE_DEVICES],
                            CONF_SCAN_INTERVAL: account[
                                CONF_SCAN_INTERVAL
                            ].total_seconds(),
                            CONF_QUEUE_DELAY: account[CONF_QUEUE_DELAY],
                            CONF_OAUTH: account.get(
                                CONF_OAUTH, entry.data.get(CONF_OAUTH, {})
                            ),
                            CONF_OTPSECRET: account.get(
                                CONF_OTPSECRET, entry.data.get(CONF_OTPSECRET, "")
                            ),
                            CONF_EXTENDED_ENTITY_DISCOVERY: account[
                                CONF_EXTENDED_ENTITY_DISCOVERY
                            ],
                            CONF_DEBUG: account[CONF_DEBUG],
                        },
                    )
                    entry_found = True
                    break
```
Then remove integration config entry, restart HA and re-add integration.

**Comment by anthonyCarigny** [comment]
Hello @danielbrunt57 
I tried what you suggested and added CONF_PUBLIC_URL: account[CONF_PUBLIC_URL], on line 158.  
But I still have the same issue as @protege323
logs still say 
```
Error during setup of component alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 189, in async_setup
    CONF_PUBLIC_URL: account[CONF_PUBLIC_URL],
                     ~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'public_url'
```
(Just now line 189 instead of 188 of course.)

**Comment by protege323** [comment]
Hi @danielbrunt57 
those lines were already represent in the __init__.py. However I've pasted your lines into mine config, removed integration, removed HACS intergration, performed a full restart of HA but issue still persist.

Logger: homeassistant.setup
Source: setup.py:416
First occurred: 4:10:58 PM (1 occurrences)
Last logged: 4:10:58 PM

Error during setup of component alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 188, in async_setup
    CONF_PUBLIC_URL: account[CONF_PUBLIC_URL],
                     ~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'public_url'

**Comment by popy2k14** [comment]
Nice find!!!!!!!!
Could you please make a PR if fix is working for others here?
This would help many others.

**Comment by danielbrunt57** [comment]
> Nice find!!!!!!!! Could you please make a PR if fix is working for others here? This would help many others.

That can't be a PR as he has hard coded his own public URL and his public URL won't work on your system!
Check if that key:value pair exists in your /config/.storage/core.config_entries in the alexa_media entry block.  If it's missing, CAREFULLY add it and restart HA.  Warning: if you induce an error in that file, HA will not start normally and will rename that file and create a new minimal one that allows it to start in recovery mode.  You can then fix the error in the renamed one, copy it back to core.config_entries and restart, but most custom edits to entities will be gone. Ask me how I know!  Safest is to backup HA core before editing it so you can do full HA core restore!  
The entry will look like:
```
        "public_url":"_your_public_url_here_",
```

**Comment by luizcarlosnery** [comment]
Exato @danielbrunt57 Aqui no meu funcionou, porém só depois de incluir minha URL público... eu uso redirecionamento via noip.com depois de fazer isto e usar a chave gerada em amazon.com tudo voltou a funcionar.

**Comment by elchanly** [comment]
> > I worked around the issue by providing a default value for account[CONF_PUBLIC_URL] on line 189. That allowed me configure and load the integration
> > ```python
> >                         CONF_PUBLIC_URL: account.get(CONF_PUBLIC_URL, 'https://my.domain/'),
> > ```
> 
> THIS WORKED, THANKS @anthonyCarigny !!!!!!!!!!!

24h later.... It crashed again

**Comment by 1242scooter** [comment]
Why is the ticket closed if it’s still not working? I tried four days ago
and it’s still not working.

**Comment by 1242scooter** [comment]
Remove and re add AMP?

Then re add all your AMP announcements too? I am assuming they are removed
when you’re removing AMP.

**Comment by danielbrunt57** [comment]
> Remove and re add AMP? Then re add all your AMP announcements too?

I'm not sure what you're actually referring to when you say announcements.  Removing Alexa Media Player in HA only removes the Alexa devices and services (notify, media_player, alexa_media) that it created. It doesn't remove any corresponding actions or entities that you have in your scripts and automations.

**Comment by 1242scooter** [comment]
I only use HA to make announcements on my echo devices from my Reolink
cameras if they detect a person or vehicle. I’m not sure if you know, but
if I removed Alexa media player and then reinstall, would I have to re-add
all my automations using AMP to my echo’s?

**Comment by danielbrunt57** [comment]
> I only use HA to make announcements on my echo devices from my Reolink cameras if they detect a person or vehicle. I’m not sure if you know, but if I removed Alexa media player and then reinstall, would I have to re-add all my automations using AMP to my echo’s?

No.  Removing AMP does not alter any code that's in automations/scripts.
The automations/scripts are unaltered and will continue to try and run while AMP is removed but they will fail and log an error that they could not find a particular service/entity/device which now does not exist.  The will resume working once AMP is reinstalled and the services/entities/devices that they reference are re-created.

**Comment by 1242scooter** [comment]
Mine does not even after uninstalling AMP and reinstalling it. ((

**Comment by domenicoCappello** [comment]
Editing line 159 of "/config/custom_components/alexa_media/init.py" with something like `CONF_PUBLIC_URL: "",` patches the issue

**Comment by 1242scooter** [comment]
I would the exact line. Not something like. It would nice if they could
just go ahead and fix it

**Comment by RNation0001** [comment]
so i tried that and it made it worse lol. then disabled AMP and rolled back to 14.13.7 and now its fine, loaded like it should have. maybe try that 1242Scooter

**Comment by danielbrunt57** [comment]
Try adding `public_url` to your yaml.
```
alexa_media:
  accounts:
    - email: "<redacted>"
      password: "<redacted>"
      url: "amazon.ca"
      public_url: "https://<redacted>"
      otp_secret: "<redacted>"
      include_devices: ""
      exclude_devices: 
        - "Nightstand Lamp 1"
        - "Nightstand Lamp 2"
        - "Bedroom"
        - "Daniel's Fire"
        - "Echo Auto"
        - "Main floor"
        - "Mach-E SYNC"
        - "Norton Court"
        - "Office"
        - "Living Room"
        - "This Device"
      queue_delay: 1.5
      scan_interval: 120
      extended_entity_discovery: true
      debug: true
```

**Comment by 1242scooter** [comment]
I don’t do anything that technical. I’m just hoping somebody will just come
out with a simple fix that I can apply or fix the apps themselves.

**Comment by danielbrunt57** [comment]
> I don’t do anything that technical. I’m just hoping somebody will just come out with a simple fix that I can apply or fix the apps themselves.

Are you or are you not using the legacy method of AMP initial setup?

For now, skip AMP 4.13.8 and just use 4.13.7.
There was nothing else is 4.13.8 except changes to `public_url` to try and fix issue when using the legacy yaml method, which I hope to deprecate soon anyway in favor of the newer UI driven integration config flow setup since it complicates code changes.

**Comment by 1242scooter** [comment]
New HA green 6 months ago. Installed HACS, AMP, and Reolink cameras. That’s
all I use HA for is to announce persons on my echos. On HA 7.2., AMP
 4.13.8. That works still. Hoping some day a HA update will work with AMP.

**Comment by danielbrunt57** [comment]
> On HA 7.2., AMP 4.13.8. That works still. Hoping some day a HA update will work with AMP.

So are you saying 4.13.8 is or is not working for you?

**Comment by 1242scooter** [comment]
It is with HA 7.2.

If I update HA past 7.2, AMP does not work.

**Comment by danielbrunt57** [comment]
AMP 4.13.7 works fine for me on HA 2024.11.1 using UI integration setup.
Legacy yaml setup had public url issues in AMP <=4.13.7 but 4.13.8 broke more than it tried to fix.

**Comment by 1242scooter** [comment]
Could you take a moment and explain the difference between:

using UI integration setup and legacy yaml setup?

How can I tell which one I am using?

**Comment by danielbrunt57** [comment]
> Could you take a moment and explain the difference between: using UI integration setup and legacy yaml setup? How can I tell which one I am using?

This would be legacy yaml setup...
`configuration.yaml`
```
alexa_media:
  accounts:
    - email: "<redacted>"
      password: "<redacted>"
      url: "amazon.ca"
      public_url: "<redacted>"
      otp_secret: "<redacted>"
      include_devices: ""
      exclude_devices: 
        - "Nightstand Lamp 1"
        - "Nightstand Lamp 2"
        - "Bedroom"
        - "Daniel's Fire"
        - "Echo Auto"
        - "Main floor"
        - "Mach-E SYNC"
        - "Norton Court"
        - "Office"
        - "Living Room"
        - "This Device"
      queue_delay: 1.5
      scan_interval: 60
      extended_entity_discovery: true
      debug: true
```

This is UI...
![image](https://github.com/user-attachments/assets/2afb0d8e-33f1-4550-851c-11e5faeab903)

![image](https://github.com/user-attachments/assets/df647381-22df-4c14-826c-995641123e84)

![image](https://github.com/user-attachments/assets/bc51ca71-8d9a-480f-bc5c-05e383a04d35)

**Comment by irizzant** [comment]
I manually removed all the existing configuration and did it from scratch, then it worked

**Comment by 1242scooter** [comment]
Would you mind telling me how you manually removed it?

I really want to work with an updated HA but Don’t wanna screw it up so if
you don’t mind, give me a step-by-step instruction, it would be very much
appreciated

**Comment by danielbrunt57** [comment]
For everyone's information, YAML configuration is being deprecated so you should start using UI config instead.
A new WARNING will soon be issued:
> YAML configuration of Alexa Media Player is deprecated and will be removed in version 4.14.0. There will be no automatic import of this. Please remove it from your configuration, restart Home Assistant and use the UI to configure it instead. Settings > Devices and services > Integrations > ADD INTEGRATION

Also, do not use v4.13.8.  Use v4.13.7 until v4.13.9 is released.
