### ISSUE TITLE
Notification to Everywhere not working

### ISSUE THREAD

**Issue by madner81** [alandtse/alexa_media_player#2484]
**Describe the bug**

Notification to Everywhere does not work

**To Reproduce**

1. Go to _Developer Settings_/_Actions_
2. Create an action of type _Notification: send a notification via alexa_media_alexa_everywhere_
3. Fill the _message_ field with any text
4. Fill the _data_  field with _type: announce_

**Expected behavior**

The text set in the _message_ field is reproduced by all the devices belonging to the intergration

**System details**

- Home Assistant version: Core 2024.8.2, Supervisor 2024.08.0, Operating System 13.1, Frontend 20240809.0
- alexa_media version (from `const.py`): 4.12.11
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): cannot find it
- Is Amazon 2FA enabled (y/n): y
- Amazon Domain: amazon.it

**Additional context**

The same actions works fine if it's invoked to a specific target device

**Comment by PJLLB** [comment]
I'm seeing this too. I first noticed it in automations I have that are supposed to announce.  It's not just to the Everywhere group, it's also to some individual Echo devices.  I tested using the Developer Tool Actions function and there works sometimes, sometimes not.  Reliable execution is very intermittent.

Some Echo devices are working reliably (the Echo and Echo Flex play the announcements reliably, and some Echo Show 8s and 5s play the announcement and show it on the screen), but others either do not show or play the announcement (both some Echo Show 5s and some Echo Show 8s).  Yesterday 8/23/2024 everything was fine.  I have updated to the latest Alexa Media Player integration, and Home Assistant is up to date.

**Comment by metalmarco** [comment]
I'm in Italy.
For me it stopped working 2 days ago.
After rebooting Home Assistant, it worked for 10 minutes and then asked for reconfiguration.
Yesterday it worked non-stop for 6 hours, but not it's broken again.

**Comment by danielbrunt57** [comment]
> I'm in Italy. For me it stopped working 2 days ago. After rebooting Home Assistant, it worked for 10 minutes and then asked for reconfiguration. Yesterday it worked non-stop for 6 hours, but not it's broken again.

This certainly sounds like it might be a case  of  Amazon dynamically throttling requests based on server demand/workloads, in which case there's nothing I can think of doing to compensate.......

**Comment by metalmarco** [comment]
> > I'm in Italy. For me it stopped working 2 days ago. After rebooting Home Assistant, it worked for 10 minutes and then asked for reconfiguration. Yesterday it worked non-stop for 6 hours, but not it's broken again.
> 
> 
> 
> This certainly sounds like it might be a case  of  Amazon dynamically throttling requests based on server demand/workloads, in which case there's nothing I can think of doing to compensate.......

Just an update. It looks like it's working now. I've not being having issue in the last 10 hours... 🤞

**Comment by maxpoz1** [comment]
Hi, I'm in Italy, until 10 days ago everything was working, it stopped working when I installed the latest HA updates (I hadn't updated for 2 months)

**Comment by federicotravaini** [comment]
Hi, I'm in Italy and I can't use `notify.alexa_media` at all anymore.

**Comment by danielbrunt57** [comment]
> Hi, I'm in Italy, until 10 days ago everything was working, it stopped working when I installed the latest HA updates (I hadn't updated for 2 months)

The last time AMP and HA played well together was HA core 2024.6.2. Issue #2288 started with HA core 2024.6.3.

**Comment by PJLLB** [comment]
I really think this is an Amazon issue, not Home Assistant.  I had updated everything in Home Assistant several days before the issue started and all Alexa Media notifications for the Everywhere group worked fine, so I don't think it is the recent Home Assistant update.  A few updates ago (to 2024.8) the Alexa Media Player did break (it didn't work at all), but the integration was quickly updated and that fixed the problem.   So to maxpoz1 and federicotravaini, I would ensure that the Alexa Media Player is current.  It's sometime easy to miss an update to a HACS custom integration like Alexa Media Player.

When this issue began, I noticed that with the Everywhere group the Echo devices (Dot, Full-sized Echo, and Flex) worked fine, but the Echo Shows and Fire TV devices did not consistently work.  The Shows and Fire TV devices reliably displayed the text of the notification, but did not play the sound.  That said, I'm now getting fairly reliable functionality (text and audio) with the Everywhere Alexa group on all of my thirteen devices.  Since, when using the Alexa Media Player in Home Assistant, you select a specific Alexa device (or group, which it seems to me to be the same thing as sending to one device versus a group as each is just a device from a Home Assistant perspective) I think this is on the Amazon side of the interface.  It's more how Amazon send things to the individual devices in the Alexa device group.

Amazon has on occasion changed how audio is sent to its Alexa devices for optimization and performance purposes (such as synchronization across multiple devices for Everywhere group playback), sometimes even breaking some functionality and then fixing it.  With regard to dynamic throttling, I could be wrong but I don't think Amazon would do this to their own services running on the Amazon Web Services platform.  I've even seen that during some period direct Alexa voice interactions are a bit slow, which to me indicates an issue that is not throttling-related but rather some system update that broke something that quickly gets fixed.

**Comment by alessandroarosio1977** [comment]
Seems to be a Integration issue because ALL type of notification by HA to Alexa devices not working. Before to update AMP to last release, issue was related to the authentication. Now the re authentication message doesn't appear more, but notification by HA automations doesn't work. I tried to notificate a message to a lot of kind devices (echo, echo show, fireTV and so on) but nothing.
Once HA restart, integration and notification go up but after 10 minutes all return to unworking.
I read on this GIT of people that tried to change integration files as workaround. I hope  to have this problem fixed without changes of files manually due I'm a newbie and I prefer to wait official patch.

**Comment by maxpoz1** [comment]
> I really think this is an Amazon issue, not Home Assistant. I had updated everything in Home Assistant several days before the issue started and all Alexa Media notifications for the Everywhere group worked fine, so I don't think it is the recent Home Assistant update. A few updates ago (to 2024.8) the Alexa Media Player did break (it didn't work at all), but the integration was quickly updated and that fixed the problem. So to maxpoz1 and federicotravaini, I would ensure that the Alexa Media Player is current. It's sometime easy to miss an update to a HACS custom integration like Alexa Media Player.
> 
> When this issue began, I noticed that with the Everywhere group the Echo devices (Dot, Full-sized Echo, and Flex) worked fine, but the Echo Shows and Fire TV devices did not consistently work. The Shows and Fire TV devices reliably displayed the text of the notification, but did not play the sound. That said, I'm now getting fairly reliable functionality (text and audio) with the Everywhere Alexa group on all of my thirteen devices. Since, when using the Alexa Media Player in Home Assistant, you select a specific Alexa device (or group, which it seems to me to be the same thing as sending to one device versus a group as each is just a device from a Home Assistant perspective) I think this is on the Amazon side of the interface. It's more how Amazon send things to the individual devices in the Alexa device group.
> 
> Amazon has on occasion changed how audio is sent to its Alexa devices for optimization and performance purposes (such as synchronization across multiple devices for Everywhere group playback), sometimes even breaking some functionality and then fixing it. With regard to dynamic throttling, I could be wrong but I don't think Amazon would do this to their own services running on the Amazon Web Services platform. I've even seen that during some period direct Alexa voice interactions are a bit slow, which to me indicates an issue that is not throttling-related but rather some system update that broke something that quickly gets fixed.

I updated from some previous version, never had any problems. At the first restart I had problems then I updated Alexa but the problem persists

**Comment by elax46** [comment]
> > I really think this is an Amazon issue, not Home Assistant. I had updated everything in Home Assistant several days before the issue started and all Alexa Media notifications for the Everywhere group worked fine, so I don't think it is the recent Home Assistant update. A few updates ago (to 2024.8) the Alexa Media Player did break (it didn't work at all), but the integration was quickly updated and that fixed the problem. So to maxpoz1 and federicotravaini, I would ensure that the Alexa Media Player is current. It's sometime easy to miss an update to a HACS custom integration like Alexa Media Player.
> > When this issue began, I noticed that with the Everywhere group the Echo devices (Dot, Full-sized Echo, and Flex) worked fine, but the Echo Shows and Fire TV devices did not consistently work. The Shows and Fire TV devices reliably displayed the text of the notification, but did not play the sound. That said, I'm now getting fairly reliable functionality (text and audio) with the Everywhere Alexa group on all of my thirteen devices. Since, when using the Alexa Media Player in Home Assistant, you select a specific Alexa device (or group, which it seems to me to be the same thing as sending to one device versus a group as each is just a device from a Home Assistant perspective) I think this is on the Amazon side of the interface. It's more how Amazon send things to the individual devices in the Alexa device group.
> > Amazon has on occasion changed how audio is sent to its Alexa devices for optimization and performance purposes (such as synchronization across multiple devices for Everywhere group playback), sometimes even breaking some functionality and then fixing it. With regard to dynamic throttling, I could be wrong but I don't think Amazon would do this to their own services running on the Amazon Web Services platform. I've even seen that during some period direct Alexa voice interactions are a bit slow, which to me indicates an issue that is not throttling-related but rather some system update that broke something that quickly gets fixed.
> 
> I updated from some previous version, never had any problems before. On the first reboot I had problems. I updated Alexa but the problem persists

I am also joining the discussion as I am also having problems with the component not working. I would like to point out that I have updated it to the latest version and that I have HA at version 2024.09.01

**Comment by PJLLB** [comment]
Audio announcement notifications are mostly working, although not always on devices that have a screen (Echo Show 5 and 8). On those the text of the announcement is usually correctly displayed but no audio announcement is made for these announcements.  This seems to happen when there are other audio events going on, for example a nearly concurrent Ring alarm ding on sensor open or another Home Assistant that also sends and audio announcement.  It's as if Alexa on the screen devices can no longer handle nearly-concurrent audio announcements even though they will usually display the test of an announcement.  And when announcements/notifications get stacked up, the sequence of play that all will be played is not predictable or reliable.  It's as if Alexa gets overwhelmed and confused, not uncommon.  She's not very smart lately.

**Comment by monxas** [comment]
I'm in the same boat, also in EU. it works sometimes. No errors, gives sucess flag when ran manually, just no message.

**Comment by elax46** [comment]
> I'm in the same boat, also in EU. it works sometimes. No errors, gives sucess flag when ran manually, just no message.

same exact condition as you I tried just today to do some tests and it does the exact same thing

**Comment by martin3000** [comment]
type: announce does not work, whereas type: tts works.

**Comment by maxpoz1** [comment]
I solved It with disable Polling function in Alexa integration. Now work

**Comment by PJLLB** [comment]
> type: announce does not work, whereas type: tts works.

Could you post your yaml code?  I can't get TTS to work.

**Comment by martin3000** [comment]
```
action: notify.alexa_media_echo_dot
data:
  message: hello
  data:
    type: tts

```

**Comment by elax46** [comment]
I use a script like this in an automation but it still doesn't work

```
sequence:
  - entity_id: script.alexa_set_volume
    action: script.turn_on
  - delay: "00:00:01"
  - data_template:
      target:
        - media_player.xxxx
        - media_player.xxx
      message: |-
     message
      data:
        type: tts
    action: notify.alexa_media
mode: single

```

**Comment by lorenzo-randisi** [comment]
> I solved It with disable Polling function in Alexa integration. Now work

Work for me !! Thank you so mouch!

**Comment by eustaquiobp** [comment]
> - data_template:

Man, I use your suggestion, in the first test with automation trigger script dont work well, to fix this issue I add a delay 10s before the actions and work better, thanks só much.

alias: happy new year msg and music
description: Ano novo msg
sequence:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ now().month == 12 and now().day == 27 }}"
        sequence:
          - delay: "00:00:10"
          - data:
              entity_id:
                - media_player.echo_dot_3
                - media_player.echo_pop
                - media_player.echo_dot_5
              volume_level: 0.2
            action: media_player.volume_set
          - data:
              message: >-
                msg...
              target:

                - media_player.echo_pop_garagem

            action: notify.alexa_media
          - delay: "00:00:33"
          - data:
              entity_id: media_player.echo_pop
              media_content_type: AMAZON_MUSIC
              media_content_id: dezesseis toneladas de Noriel Vilela 
            action: media_player.play_media
