### ISSUE TITLE
Alexa Media Player Integration Fails After HA Restart (2024.8.0+), Affecting Amazon Smart Plug in HomeKit

### ISSUE THREAD

**Issue by fbnksr** [alandtse/alexa_media_player#2488]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

I'm experiencing an issue with the Alexa Media Player integration following the Home Assistant (HA) update to version 2024.8.0 and above. Here's the situation:

- Integration Setup: I've integrated an Amazon Smart Plug into HomeKit via HomeAssistant using the Alexa Media Player integration.
- Problem: After updating to HA 2024.8.0 and beyond, the integration fails to function correctly after every HA restart. Specifically, I need to manually reload the Alexa Media Player integration each time, otherwise:
  - The integration fails to initialize properly.
  - Alexa devices still appear, but many entities are marked as unavailable or are not provided.
  - As a result, the Amazon Smart Plug (and possibly other Alexa-linked devices) appears as "Not Responding" within HomeKit.

**To Reproduce**

Steps to Reproduce:

1. Integrate an Amazon Smart Plug into HomeKit using HomeAssistant and the Alexa Media Player integration.
2. Update HomeAssistant to version 2024.8.0 or later.
3. Restart HomeAssistant.
4. Observe the failure of the Alexa Media Player integration and the subsequent issues with device availability.

**Expected behavior**

The Alexa Media Player integration should initialize correctly after a HomeAssistant restart without requiring manual reloading, and all entities should be available, allowing the Amazon Smart Plug to respond normally in HomeKit.

**Screenshots**

<img width="1183" alt="Screenshot 2024-08-27 at 20 18 32" src="https://github.com/user-attachments/assets/b098ab03-4e1c-4eb4-b38c-ee84ea60960e">

**System details**

- Home Assistant version: 2024.8.3
- alexa_media version (from `const.py` or HA startup log): v4.12.11
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): N/A
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): n
- Amazon Domain: USA

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component). N/A

**Additional context**

This issue seems to have started specifically after the 2024.8.0 update. Before this, the integration worked seamlessly without needing manual intervention after restarts.

**Comment by craggyh** [comment]
I have exactly this same issue. The integration worked flawlessly until a recent HA update and since then it requires reloading/reconfiguration after every HA restart.

**Comment by danielbrunt57** [comment]
Please check DEBUG logs for the error:
```
2024-06-18 15:11:26.699 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry d*****@*******a - amazon.com for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 335, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 328, in load_cookie
    cookies = pickle.loads(await myfile.read())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/cookies.py", line 312, in __setitem__
    raise CookieError("Invalid attribute %r" % (K,))
http.cookies.CookieError: Invalid attribute 'partitioned'
```
If so, see issue #2288

**Comment by fbnksr** [comment]
> Please check DEBUG logs for the error:
> 
> ```
> 
> 2024-06-18 15:11:26.699 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry d*****@*******a - amazon.com for alexa_media
> 
> Traceback (most recent call last):
> 
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
> 
>     result = await component.async_setup_entry(hass, self)
> 
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/config/custom_components/alexa_media/__init__.py", line 335, in async_setup_entry
> 
>     await login.login(cookies=await login.load_cookie())
> 
>                               ^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 328, in load_cookie
> 
>     cookies = pickle.loads(await myfile.read())
> 
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.12/http/cookies.py", line 312, in __setitem__
> 
>     raise CookieError("Invalid attribute %r" % (K,))
> 
> http.cookies.CookieError: Invalid attribute 'partitioned'
> 
> ```
> 
> If so, see issue #2288 

I want to clarify that my issue is not related to the Alexa Media Player integration failing to work entirely. I can manually reload the integration, and it does successfully reload without any apparent issues. However, the problem lies with the devices—more specifically, the entities associated with these devices. Even after the integration is fully loaded, many entities do not function properly, showing as "Not Responding" or "Unavailable." 

The screenshot I provided illustrates this issue: although the integration itself is loaded, the entities for the Amazon Smart Plug and other Alexa-linked devices are not. This indicates that the integration is operational, but the entities are not loading as they should after the Home Assistant restart.

**Comment by danielbrunt57** [comment]
It would take a careful review of DEBUG logs for "alexa" (which is both alexapy and alexa_media) from core startup all the way through to the point of no availability.

**Comment by fbnksr** [comment]
To resolve this, I removed the Alexa Media Player integration entirely, deleted all related files, including the cookie files, and then reinstalled the integration. After re-authenticating, the integration set up correctly, and the issue was resolved without further errors.
