### ISSUE TITLE
Please add Japanese language to the translation

### ISSUE THREAD

**Issue by yhi264** [alandtse/alexa_media_player#2489]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
I can't find Japanese language in [Lokalise page](https://lokalise.com/public/465185555eee18dd537ca6.39714580/).

**Describe the solution you'd like**
Please add Japanese language to the Lokalise.

**Describe alternatives you've considered**
Nothing.

**Additional context**
Nothing.

**Comment by jleinenbach** [comment]
I asked ChatGPT to translate the file.
[ja.json](https://github.com/user-attachments/files/16824583/ja.json)

**Comment by danielbrunt57** [comment]
I tried before to PR translation file changes and was informed that AMP only uses Lokalise to add/create translation files.
Your request will require someone taking on and creating a project in Lokalise to add Japanese language...

**Comment by alandtse** [comment]
Japanese has been added in lokalise.

**Comment by alandtse** [comment]
Please note that it's enabled in lokalise, but volunteer will have to add the language translations. Once added, they are automatically picked up during the release process.
