### ISSUE TITLE
Alexa Media Player do not download through hacs on HA version 2024.8.2

### ISSUE THREAD

**Issue by rajdey1** [alandtse/alexa_media_player#2490]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Alexa Media Player do not download through hacs on HA version 2024.8.2
**To Reproduce**

1. Go to Hacs 
2. Type on Search bar "alexa media player"
3. Alexa media player will show up
4. click on three dot on right on side of alexa media player
5. Click download.
6. The progress bar will start 
7. wait for some time 
8. Error message shows up like
The version for this integration cannot be used with HACS

**Expected behavior**

Alexa media player should download through HACS
**Screenshots**

![image](https://github.com/user-attachments/assets/a8c5c1eb-937f-486b-a41a-fdb2dd5609f4)

**System details**

- Home Assistant version:2024.8.2
- alexa_media version (from `const.py` or HA startup log): latest
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n):
- Amazon Domain:

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by danielbrunt57** [comment]
What version of AMP is HACS showing?
"Latest" is not an answer!
Please check your HACS custom repositories has the correct URL for AMP.
Update info for AMP custom component.
Failing that, remove and reinstall HACS.

**Comment by rajdey1** [comment]
@danielbrunt57  Sorry I am not sure how to check version can you help for same I am attaching screen shot if that helps
![image](https://github.com/user-attachments/assets/9ca46420-9187-4b15-a264-77e0e6e7e640)


![image](https://github.com/user-attachments/assets/519eb15d-4492-4803-92f9-1326365820b4)

**Comment by danielbrunt57** [comment]
If you click on the entry in you 2nd screenshot it should show the version:

![image](https://github.com/user-attachments/assets/c42ec896-6f3e-4e21-9492-3b70356f85b1)

**Comment by guiumb** [comment]
In your manifest alexapy version is 1.29.0 but in the repository for release 4.12.11 alexapy is 1.28.2.
Which is the correct version that we have to use?
Thks

**Comment by danielbrunt57** [comment]
@rajdey1 Any update?
