### ISSUE TITLE
Error doing job: Task exception was never retrieved (None): `Login error detected; not contacting API`

### ISSUE THREAD

**Issue by madner81** [alandtse/alexa_media_player#2493]
**Describe the bug**

Notification to devices to announce text does not work

**To Reproduce**

1. Create an Automation
2. In the Actions add an action of type "Notifications: Send a notification via _alexa_device_"
3. Add any text in the _message_ field
4. Insert _type: announce_ in the _data_ field
5. Trigger the action
6. Nothing is reproduced by the device and _Error doing job: Task exception was never retrieved (None)_ is added in the log

**Expected behavior**

The target device reproduces the text set in the message field

**System details**

- Home Assistant version: Core 2024.8.2, Supervisor 2024.08.0, Operating System 13.1, Frontend 20240809.0
- alexa_media version (from `const.py` or HA startup log): 4.12.11
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled] (y/n): y
- Amazon Domain: it

**Log entry**

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 960, in send_announcement
    await self.send_sequence(
  File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 512, in send_sequence
    await self.run_behavior(node_data, queue_delay=queue_delay)
  File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 434, in run_behavior
    await self._post_request("/api/behaviors/preview", data=data)
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 226, in _post_request
    return await self._request("post", uri, data, query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexaapi.py", line 199, in _request
    raise AlexapyLoginError("Login error detected; not contacting API")
alexapy.errors.AlexapyLoginError: Login error detected; not contacting API

**Additional context**

The notification only works for some minutes when the integration has just loaded or reloaded

**Comment by garagara93** [comment]
I have exactly the same error with the same config

**Comment by diversit** [comment]
Same issue with HA 2024.8.3 and Alexa media config v4.12.11 after I just upgraded both.
Before HA was 2024.7.x and a previous Alex media config version.

At first, after HA restart, the Alexa media integration was in error, but restarting the integration seemed to solve that. However, calling the notification service does not work anymore.
Also, running an action from the Developer Tools does not work.

**Comment by danielbrunt57** [comment]
The error `"Login error detected; not contacting API"` is the same as issue #2453. 
Please use that issue to continue discussion.
