### ISSUE TITLE
Do Mp3s still work through this integration?

### ISSUE THREAD

**Issue by Krispkiwi** [alandtse/alexa_media_player#2497]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

I used to be able to send custom Mp3s to my Alexa Media players via the following action below but now it just states "I'm having trouble with accessing your simon says skill". I've checked and everything lines up correctly as it used to. Is this another issue with everything happening lately to the integration?

**To Reproduce**

1. Developer Tools
2. Do as I've done here:
action: notify.alexa_media
metadata: {}
data:
  target: media_player.bedroom_show
  data:
    type: tts
  message: >-
    <audio
    src='https://publcip/local/audio/music/morningalarm.mp3'/>

**Expected behavior**

This should be playing the mp3 file. I use this for both morning alarms and house alarms so It's a tad important to my setup

**Screenshots**

No screenshot required

**System details**

- Home Assistant version: 2024.8.3
- alexa_media version (from `const.py` or HA startup log): 
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): 4.12.11
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): Y
- Amazon Domain: US

**Debug Logs (alexa_media & alexapy)**

[home-assistant_alexa_media_2024-08-31T10-36-39.525Z.log](https://github.com/user-attachments/files/16824349/home-assistant_alexa_media_2024-08-31T10-36-39.525Z.log)

**Additional context**

I tried both notify.alexa (which used to work) and earlier also the play.media action.

**Comment by jleinenbach** [comment]
According to your logs, you need the Python cookies.py patch.
Your alexapy version is missing. 4.12.11 is your AMP version.

Follow these instructions:
https://github.com/alandtse/alexa_media_player/issues/2469#issuecomment-2323376497

But esp. begin with this step:
https://github.com/alandtse/alexa_media_player/issues/2453#issuecomment-2297386449

**Comment by Krispkiwi** [comment]
> According to your logs, you need the Python cookies.py patch. Your alexapy version is missing. 4.12.11 is your AMP version.
> 
> Follow these instructions: [#2469 (comment)](https://github.com/alandtse/alexa_media_player/issues/2469#issuecomment-2323376497)
> 
> But esp. begin with this step: [#2453 (comment)](https://github.com/alandtse/alexa_media_player/issues/2453#issuecomment-2297386449)

Thanks for replying, I'm trying to follow the steps, so far I've done the following:
- Installed the Patch integration on hacs
- Added the files to the share folder
- Added patch information to the config file
- Installed PythonScriptPro in hacs
- Added the python info to the config file
- Reconfigured the Alexa Media Player from 60sec to 90sec

I'm struggling to understand what it wants me to do with this part:
 Upgrade Python's cookie.py and check if it was successful: https://github.com/alandtse/alexa_media_player/issues/2453#issuecomment-2317105135

**Comment by jleinenbach** [comment]
> I'm struggling to understand what it wants me to do with this part: Upgrade Python's cookie.py and check if it was successful: [#2453 (comment)](https://github.com/alandtse/alexa_media_player/issues/2453#issuecomment-2317105135)

It should only serve as an example of a discussion of how to can check if the patch was successful:
Here's my script: [check_cookies_py.sh.txt](https://github.com/user-attachments/files/16796252/check_cookies_py.sh.txt)
```mv check_cookies_py.sh.txt check_cookies_py.sh chmod +x check_cookies_py.sh```

**Comment by Krispkiwi** [comment]
> > I'm struggling to understand what it wants me to do with this part: Upgrade Python's cookie.py and check if it was successful: [#2453 (comment)](https://github.com/alandtse/alexa_media_player/issues/2453#issuecomment-2317105135)
> 
> It should only serve as an example of a discussion of how to check if the patch was successful: Here's my script: [check_cookies_py.sh.txt](https://github.com/user-attachments/files/16796252/check_cookies_py.sh.txt) `mv check_cookies_py.sh.txt check_cookies_py.sh chmod +x check_cookies_py.sh`

How do I run this? with terminal?

**Comment by jleinenbach** [comment]
> How do I run this? with terminal?
Correct.

> Could not remove ... z.pickle. Please manually delete the file. 

That means your system still uses the older alexapy version.

**Comment by Krispkiwi** [comment]
> > How do I run this? with terminal?
> > Correct.
> 
> > Could not remove ... z.pickle. Please manually delete the file.
> 
> That means your system still uses the older alexapy version.

so what are the steps now since ive added the patch etc? Do I delete the file then reload the integration?

**Comment by jleinenbach** [comment]
> so what are the steps now since ive added the patch etc? Do I delete the file then reload the integration?

This means that step 4 didn't succeed. Please check/repeat this step.
Additionally, to prevent downgrades, you can also change the manifest.json file in the alexa_media folder to:
```requirements": ["alexapy==1.29.0", "packaging>=20.3", "wrapt>=1.14.0"]```

If you do this manually, you need to shut down HA, then delete the pickle file, then boot again - because if you delete the file, then reboot, the wrong pickle file will be generated. alexapy==1.29.0 can delete the file on its own.

**Comment by Krispkiwi** [comment]
> > so what are the steps now since ive added the patch etc? Do I delete the file then reload the integration?
> 
> This means that step 4 didn't succeed. Please check/repeat this step. Additionally, to prevent downgrades, you can also change the manifest.json file in the alexa_media folder to: `requirements": ["alexapy==1.29.0", "packaging>=20.3", "wrapt>=1.14.0"]`
> 
> If you do this manually, you need to shut down HA, then delete the pickle file, then boot again - because if you delete the file, then reboot, the wrong pickle file will be generated. alexapy==1.29.0 can delete the file on its own.

I've just tried again doing the same steps without any luck.
I can't edit my home assistant at all when its shutdown sadly since its on a pi

**Comment by Krispkiwi** [comment]
resolved, this was actually due to cloudflare

**Comment by saberstop** [comment]
Hello, I'm facing the same issue. What did you do to cloudflare to fix this?

**Comment by Krispkiwi** [comment]
> Hello, I'm facing the same issue. What did you do to cloudflare to fix this?

I had filters set up to make it so only certain addresses could access my tunnel, previously alexa worked fine with this but they may have made changes on their end to change the range of IP addresses they use.

**Comment by danielbrunt57** [comment]
In my Cloudflare tunnel setup for Amazon/Alexa access. I allow a list I created:

![image](https://github.com/user-attachments/assets/98c3df37-07e6-4104-8f73-b2eff44b7bd2)
