### ISSUE TITLE
Robot Vacuum entity type integration  

### ISSUE THREAD

**Issue by kmaid** [alandtse/alexa_media_player#2506]
**Is your feature request related to a problem? Please describe.**
I cannot get the current status of my Eufy X10 vacuum cleaner which is integrated into Alexa to pause other automation while the vacuum is active.

**Describe the solution you'd like**
I want Alexa Media Player to support this entity type and expose its status to home assistants, such as switches, sensors, and devices discovered via ZigBee. 

**Describe alternatives you've considered**
I looked at the Eufy robo vacuum hacs plugin. It does not currently support the model and hasn't had a commit in some time.  The issue has been raised in https://github.com/CodeFoodPixels/robovac/issues/68 however while there is allot of interest in its support it doesn't seem to be under active development. 

**Additional context**
I think there is lots of innovation in the robot vacuum space with new machines coming out frequently. All of these new models are likely to implement the alexa abstraction and thus new models could be supported in a basic way via Alexa until specific integrations come out. 

![IMAGE 2024-09-04 21:54:33](https://github.com/user-attachments/assets/202026d5-d230-46fe-b354-8d2189a4c1e5)
![IMAGE 2024-09-04 21:54:41](https://github.com/user-attachments/assets/412184aa-89e1-4abd-95b2-b173a5826995)

**Comment by danielbrunt57** [comment]
I'm sorry but this integration is Alexa _MEDIA_ Player and it's already morphed & taxed beyond it's original intended means and robot vacuums, shopping lists, etc. aren't within it's intended scope.
You need an integration specifically for your device...
