### ISSUE TITLE
Echo devices disappeared

### ISSUE THREAD

**Issue by michaelsleen** [alandtse/alexa_media_player#2510]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**
I had several Amazon Echo devices connected to Home Assistant via Alexa Media Player. All of a sudden, none of the Echo devices are viewable in Home Assistant (entities are all gone).

**To Reproduce**

I am unclear what produced this behavior. 

**Expected behavior**

I expect to see my Echo devices in Home Assistant.

**Screenshots**

<img width="1263" alt="Screenshot 2024-09-06 at 4 42 15 PM" src="https://github.com/user-attachments/assets/ca3ef468-779c-4059-934e-103830289fb6">

**System details**

- Home Assistant version: 2024.9.1
- alexa_media version (from `const.py` or HA startup log): 4.12.12
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): Unsure
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): Y
- Amazon Domain: amazon.com

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

<img width="1263" alt="Screenshot 2024-09-06 at 4 47 18 PM" src="https://github.com/user-attachments/assets/2d51f859-bcbc-45c6-aaae-83e2faad44b7">

**Additional context**

**Comment by LordShelmchen** [comment]
same issue on my site, but Amazon domain is: amazon.de

**Comment by sippeeey** [comment]
I reconfigure the Integration and log in again, then after this all devices loads correctly and now i can also play something on the echos via media player.

**Comment by uservipul** [comment]
For me it was updating my BASE_URL 
I had an old duck dns server which I didn't use. 
It was under; Lambda>Configuration>Environment variables

Hope that helps!

**Comment by danielbrunt57** [comment]
> For me it was updating my BASE_URL I had an old duck dns server which I didn't use. It was under; Lambda > Configuration > Environment variables

Where is that?
