### ISSUE TITLE
Alexa_media.clear_history stopped working

### ISSUE THREAD

**Issue by schmuttis** [alandtse/alexa_media_player#2513]
I have an automation that nightly calls alexa_media.clear_history. For some reason about September 1st it stopped working and I get “Error: Action alexa_media.clear_history not found”. Since this error started I have installed the most recent update to Alexa media player which fixed other problems but not this. From the log file:

> Source: helpers/script.py:2026
> integration: Automation (documentation, issues)
> First occurred: 12:21:18 PM (2 occurrences)
> Last logged: 12:34:55 PM
> 
> Clear Alexa History @ 11:50 PM: Error executing script. Service not found for call_service at pos 1: Action alexa_media.clear_history not found

Does Amazon no longer permit the clearing of history or has something else changed? In other words, is there a way to get this working again?

Thanks for your help.

HA automation
> alias: Clear Alexa History @ 11:50 PM
> description: Clear Alexa History
> trigger:
>   - platform: time
>     at: "23:50:00"
> condition: []
> action:
>   - data: {}
>     action: alexa_media.clear_history
>   - delay: "00:00:09"
> mode: single

**System details**

- Home Assistant version:
![image](https://github.com/user-attachments/assets/673b7b9c-fbc2-4fb7-90d0-1493f555fd88)

- alexa_media version (from `const.py`): "4.12.12"
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): alexapy==1.28.2

- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): y
- Amazon Domain: amazon.com

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

Source: helpers/script.py:2026
integration: Automation (documentation, issues)
First occurred: 12:21:18 PM (2 occurrences)
Last logged: 12:34:55 PM

Clear Alexa History @ 11:50 PM: Error executing script. Service not found for call_service at pos 1: Action alexa_media.clear_history not found

**Additional context**

**Comment by danielbrunt57** [comment]
Amazon no longer supports that call and you have to use their app to clear history.
https://www.google.com/url?sa=t&source=web&cd=&ved=2ahUKEwjds7nBpLKIAxV8MjQIHcV4ORYQFnoECBQQBQ&url=https%3A%2F%2Fwww.amazon.com%2Fgp%2Fhelp%2Fcustomer%2Fdisplay.html%3FnodeId%3DGVLEU55A9NDZRWBU%23%3A~%3Atext%3DOpen%2520More%2520and%2520select%2520Settings%2C%252C%2520device%252C%2520or%2520voice%2520ID.&usg=AOvVaw3rD5SdAps-pRn5oQ5el5zo&opi=89978449
