### ISSUE TITLE
Issue with 2FA when asigning Alexa

### ISSUE THREAD

**Issue by StefanJock** [alandtse/alexa_media_player#2526]
**Describe the bug**

The Alexa Media Player has been updated to the latest version (v.4.12.12) via HACS. This required a new registration, which I had to cancel on Chrome, Edge and Safari with the same problem. I followed the procedure exactly as described in the wiki manual. As a result, the registration of the Media Player as the second application of the 2FA in Amazon is still running smoothly. However, after that, the Alexa website is then accessed via the browser to log in (see above). After entering the email and then the password, the input window for the email appears again. There is no option to enter the OTP. So 2FA is not possible on this site and the player registration will fail.

I have found many tips on the forums. However, my problem is not one of them. Among other things, the CAPTCHA problem is not my problem.

I was able to use the player itself for about 10 months without any problems until the update. I hope you can help me as I really enjoyed using the player. 

**To Reproduce**

1. Go to '2FA in Amazon'
2. Get "Integrated "FA App Key", enter in Media Player confi dialogue
3. Get OTP from Media Player and confirm in Amazon
4. Amazon confirms registration of add app
5. Player opens the Alexa Sign In Website but Sign In Procedure doesn't offer to enter an OTP but e-mail and password only
6. Registration can't be completed, neither on Edge nor Chrome or Safari

**Expected behavior**

I expected in the Alexa Web Login a field to enter the OTP (as shown in the youtube-video)

**Screenshots**

**System details**

- Home Assistant version: 11.4
- alexa_media version (from `const.py` or HA startup log): v4.12.12
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): yes it is enabled
- Amazon Domain: amazon.de

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by joaquincasa** [comment]
+1. Same problem with Amazon Domain amazon.es

**Comment by jamestas** [comment]
This issue has been listed by others, hopefully the author will pick this up.
Here is a workaround from another thread:

....
Through trial and error trying to figure out the flow sequence, I was able to trick it and get to the OTP window.
After you've cycled through name, password and back to name, select the option Create Account New to Amazon?
Fill in a first & last name (anything at all as not going to matter so "Q W" is quick and easy to type!)
Amazon will then inform you that an account with your email already exists.
At that point re-select "Sign in Already a customer?" and proceed with the email and password windows and then the OTP window should appear. By that point though, the integration generated OTP has likely expired but you can just enter your current app generated OTP code and it should work.
If it returns to the integration add window and it just sits and spins and never progresses, that likely means the proxy listening session has expired and you'll have to repeat the process.

**Comment by danielbrunt57** [comment]
Duplicate issue.  See #2514
