### ISSUE TITLE
loop on login page

### ISSUE THREAD

**Issue by platini76** [alandtse/alexa_media_player#2536]
hello, all data are inserted correctly but there is a loop on login page
<img width="484" alt="Screenshot 2024-09-17 alle 15 30 28" src="https://github.com/user-attachments/assets/63a59226-1407-48c7-86b8-67c8103ccfa2">

**Comment by platini76** [comment]
there is nothing to template...

**Comment by codeunifier** [comment]
Also having this issue

**Comment by codeunifier** [comment]
@platini76 I opened an issue [here](https://github.com/alandtse/alexa_media_player/issues/2540) - hopefully someone gets back to us on this.

**Comment by danielbrunt57** [comment]
Duplicate issue!  See #2514
