### ISSUE TITLE
Unable to get pass the alexa signin

### ISSUE THREAD

**Issue by mrpbennett** [alandtse/alexa_media_player#2537]
I have just installed the Alexa Media Player into HA - I am running HA inside a VM within Proxmox

Once I have gone through the setup instructions and been presented with the popup stating:

> This step requires you to visit an external website to be completed.

This opens the URL 

```
http://192.168.7.216:8123/auth/alexamedia/proxy?config_flow_id=01J808Y5SJQDN8RN09W49NTBWE&callback_url=http://192.168.7.216:8123/auth/alexamedia/callback?flow_id%3D01J808Y5SJQDN8RN09W49NTBWE
```

The flow is then the above URL (I then click log in) the next URL is 

```
http://192.168.7.216:8123/auth/alexamedia/proxy/ap/signin
```

After the sign in button is pressed the call goes back to the previous URL

```
http://192.168.7.216:8123/auth/alexamedia/proxy?config_flow_id=01J8092XVA51PD32V0NABDVQQ8&callback_url=http://192.168.7.216:8123/auth/alexamedia/callback?flow_id%3D01J8092XVA51PD32V0NABDVQQ8
```

Therefore I am unable to get pass this section

I am using the latest version v4.13.1

**Comment by danielbrunt57** [comment]
See [my workaround](https://github.com/alandtse/alexa_media_player/issues/2514#issuecomment-2345070532) in issue #2514
