### ISSUE TITLE
Loop on login page

### ISSUE THREAD

**Issue by codeunifier** [alandtse/alexa_media_player#2540]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Putting https://github.com/alandtse/alexa_media_player/issues/2536 into the proper template format since I am experiencing the same thing.

**To Reproduce**

1. Install Alexa Media Player integration through HACS
2. Add the Alexa Media Player integration on the Integration page in HA
3. Enter all credentials and other fields
4. Get routed to an Amazon login page
5. Input email and password
6. [BUG] Get redirected back to the same login page from step 4.

**Expected behavior**

Assuming something with the credentials was incorrect, instead of getting redirected to the login page with no explanation, provide the reason the login was not successful.

**Screenshots**

![Screenshot from 2024-09-17 15-43-58](https://github.com/user-attachments/assets/f732dae3-0d75-4930-bc7b-cddec2bc4e6f)

**System details**

- Home Assistant version: 13.1
- alexa_media version (from `const.py` or HA startup log): 4.13.1
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): n/a
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): no
- Amazon Domain: n/a

**Debug Logs (alexa_media & alexapy)**
n/a

**Additional context**
n/a

**Comment by codeunifier** [comment]
Update: Amazon is now have to input a one-time password (OTP) but because of this loop I don't even have the option of entering the OTP.

**Comment by platini76** [comment]
same problem here

**Comment by losco78** [comment]
Same problem

**Comment by danielbrunt57** [comment]
Duplicate issue See #2514 and my solution there...
