### ISSUE TITLE
Alexa asks for re-authentication with TuneIn.

### ISSUE THREAD

**Issue by Xoordak** [alandtse/alexa_media_player#2545]
Describe the bugs

Once Alexa Media Player is installed and all devices are correctly configured. Using 2FA, it is amazon.it.
Alexa stays connected until TuneIn is used by calling it with Alexa, 'Alexa, play Radio Radio.' After that, it disconnects, and the procedure needs to be done from scratch. This happens every time.

Screenshots
![IMG_3836](https://github.com/user-attachments/assets/6cd923de-4aaf-4613-8014-dc0badf15add)

Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 8:38:25 PM (1 occurrences)
Last logged: 8:38:25 PM

Error setting up entry XXXXXXX@icloud.com - amazon.it for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 361, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
  File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 713, in login
    self._site = await self._process_page(await post_resp.text(), site)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 1506, in _process_page
    error_message += list_item.find("span").string
TypeError: can only concatenate str (not "NoneType") to str

System details

Home Core
2024.9.2
Supervisor
2024.09.1
Operating System
13.1
Frontend
20240909.1
Alexa Media Player
v4.13.1

**Comment by sherkan-666** [comment]
Same for me.

**Comment by BobMac57** [comment]
Same shit here.... this is getting frustrating.

**Comment by tbkon3** [comment]
same for me ...

**Comment by katino97** [comment]
Same for me

**Comment by sherkan-666** [comment]
I update Alexa Media Player in 4.13.2, restart HA and now it's OK, no error.

**Comment by Xoordak** [comment]
I keep getting the same error. I have uninstalled and reinstalled everything. How do I access the media player interface, and whenever I touch any command, it disconnects everything.

**Comment by Xoordak** [comment]
I solved it!
homeassistant runs on a raspberry pi5.
updating the Rasb firmware
