### ISSUE TITLE
Configurazione non riuscita e Action notify.alexa_media not found

### ISSUE THREAD

**Issue by millenniumy2k** [alandtse/alexa_media_player#2547]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Registratore: homeassistant.config_entries
Fonte: config_entries.py:604
Prima occorrenza: 11:37:33 (3 occorrenze)
Ultima registrazione: 11:44:50

Error setting up entry me@lucafiori.com - amazon.it for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 361, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
  File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 713, in login
    self._site = await self._process_page(await post_resp.text(), site)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 1506, in _process_page
    error_message += list_item.find("span").string
TypeError: can only concatenate str (not "NoneType") to str

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**

- Home Assistant version: 2024.9.2
- alexa_media version (from `const.py` or HA startup log): 4.13.1
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): 4.13.1
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): y
- Amazon Domain: amazon.it

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

Error setting up entry me@lucafiori.com - amazon.it for alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 361, in async_setup_entry
    await login.login(cookies=await login.load_cookie())
  File "/usr/local/lib/python3.12/site-packages/alexapy/helpers.py", line 137, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 713, in login
    self._site = await self._process_page(await post_resp.text(), site)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alexapy/alexalogin.py", line 1506, in _process_page
    error_message += list_item.find("span").string
TypeError: can only concatenate str (not "NoneType") to str

**Comment by MarQua** [comment]
The same for me

**Comment by felmatrix** [comment]
The same for me

**Comment by mauriziomontanaro** [comment]
The same also for me

**Comment by katino97** [comment]
Same

**Comment by morrys79** [comment]
The same also for me

**Comment by atiburzi** [comment]
The same

**Comment by maxacampora** [comment]
The same for me

**Comment by millenniumy2k** [comment]
now the notify.alexa_media Action is recognized, but like all Echos they don't speak...

**Comment by cansado2930** [comment]
I have the same problem, my account is amazon.es

**Comment by millenniumy2k** [comment]
Is there any news on a possible resolution date?

**Comment by johnreind** [comment]
The same for me. I think the addon has become so unstable lately that it's become useless. Maybe it will be integrated directly into Home Assistant, but as it's becoming now, it's not really usable. It's a shame because it used to work well before.

**Comment by diegobattistuzzi** [comment]
Same issue

**Comment by millenniumy2k** [comment]
Is there any news on a possible resolution date? THX!

**Comment by stephensalex** [comment]
I too am having this issue

**Comment by danielbrunt57** [comment]
The original issue cited was fixed several alexapy releases ago.  The issue was:
```
error_message += list_item.find("span").string
TypeError: can only concatenate str (not "NoneType") to str
```
