### ISSUE TITLE
While assistant integration can't install. Loop on Amazon login

### ISSUE THREAD

**Issue by elz64** [alandtse/alexa_media_player#2550]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

No idea of how describing. But never been able to setup this correctly 

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**

- Home Assistant version:
- alexa_media version (from `const.py` or HA startup log):
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n):
- Amazon Domain:

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by dustardly** [comment]
same bug, can't log in in amazon.it

**Comment by nstyqz** [comment]
Here https://github.com/alandtse/alexa_media_player/issues/2514) there is a halfway solution... 😅

**Comment by nstyqz** [comment]
Here https://github.com/alandtse/alexa_media_player/issues/2514 there is a halfway solution...

**Comment by Mec0808** [comment]
Anche io ho lo stesso problema, in fase di integrazione, nel mio caso metto amazon.it, mi si apre la finestra di login, ma anche se le credenziali sono corrette il login si ripete all'infinito.
C'è una soluzione?

**Comment by nstyqz** [comment]
Open the link of number **#2514**  you'll find the solution there

**Comment by stamandr** [comment]
I can't get by this continuous loop. The work around does not work for me

**Comment by mattia93cz** [comment]
To resolve the authentication loop:
instead of entering the data and logging in, just go to register new account and by entering the data the error "user already registered" will be returned.
Once this step has been carried out, simply log in by entering the correct data and everything will work correctly.

**Comment by Joeslinky** [comment]
https://github.com/alandtse/alexa_media_player/issues/2554#issuecomment-2381869404 Is your firewall blocking the API?

**Comment by DOlivier4444** [comment]
> To resolve the authentication loop: instead of entering the data and logging in, just go to register new account and by entering the data the error "user already registered" will be returned. Once this step has been carried out, simply log in by entering the correct data and everything will work correctly.

life savior, thanks man

**Comment by danielbrunt57** [comment]
Duplicate issue [#2514](https://github.com/alandtse/alexa_media_player/issues/2514)
