### ISSUE TITLE
Included Device Not Working

### ISSUE THREAD

**Issue by adamriley13** [alandtse/alexa_media_player#2556]
**Describe the bug**

When typing in the devices to include via the UI it wipes out all my Alexa devices and doesn't include the device that I asked it to include. When I clear the 'included device' field and update the configuration the devices have still disappeared. The only way for me to get them back is to completely wipe the Alexa media player account and start again by configuring the account again.

**To Reproduce**

To produce this bug I just need to add a device in the 'included device' text box via the UI

**Expected behavior**

I would assume that adding a device in the 'included device' text box would include just that device on the Alexa app and I would also assume it wouldn't get rid of all my Alexa devices within home assistant. In addition I would also assume if I cleared the 'included device' text box then all my devices would return but they don't even after a reconfiguration or home assistant restart.

**System details**

- Home Assistant version: 2024.9.2
- alexa_media version (from `const.py` or HA startup log): 4.13.2
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): /
- Is Amazon [2FA/2SV enabled]: Y
- Amazon Domain: Amazon co.uk

**Comment by FS1961** [comment]
I have the same issue, Echo Show 5, 8, and Echo Pop. I only have the power button available.
Amazon Domain: Amazon.com
Alex_media_version: 4.13.2
HA version: 2024.9.3

Is this a gen issue with the devices?

**Comment by itsaniket12** [comment]
Hello  adamriley
I have tried to provide you a better solution for this issue.
[issue2.docx](https://github.com/user-attachments/files/17246343/issue2.docx)
[issue1.docx](https://github.com/user-attachments/files/17246345/issue1.docx)


When attempting to add a device through the "included device" field in the UI, all Alexa devices are removed from Home Assistant, and the newly added device is not included. Clearing the field does not restore the removed devices, requiring a complete reconfiguration of the Alexa Media Player integration.

Changes Made:

Updated the Commitizen tool version from v3.28.0 to v3.29.1.
Updated the Bandit tool version from 1.7.9 to 1.7.10.
These version updates aim to resolve issues and ensure better functionality and security in the project's toolchain.

**Comment by yettavr6** [comment]
Same issue….

**Comment by yorb** [comment]
@adamriley13 It seems like you are reporting two issues:
1. Include/Exclude does not work the way you think it should.
2. Once you have set the Include/Exclude fields, clearing them out does not stick.

For the first one, check the documentation to make sure you're using it correctly. In particular:
>NOTE: include_devices only loads devices that have been listed and functions like a deny list.

The second issue appears to be a legitimate bug, where once there is text in either the include or exclude fields, you can't clear it out through the UI. Deleting everything and clicking Submit appears to work but if you open Configure again you'll see the values are still there. The workaround I used is to edit the `config/.storage/core.entity_config` file directly. Just search for "alexa" to find the right line, then leave only an empty string (`""`) for `include_devices` and/or `exclude_devices`.

@itsaniket12 I'm not sure what you're trying to provide but your message look like spam. I'm certainly not clicking your docx links. If you want to contribute, submit a PR or reach out to the maintainer.

**Comment by danielbrunt57** [comment]
> I would assume that adding a device in the 'included device' text box would include just that device on the Alexa app and I would also assume it wouldn't get rid of all my Alexa devices within home assistant.

If you choose to populate `include_devices` then you have to specify each and every device that now should be included.  If you only specify one device then _**only**_ that device is loaded.

So...
If you have more included devices than excluded, use `exclude_devices `and list all devices to be excluded.
If you have more excluded devices than included one, use `include_devices` and specify all of the devices you want included.

For me, I am 50/50 and I use `exclude_devices`: `Nightstand Lamp 1,Nightstand Lamp 2,Bedroom,Daniel's Fire,Echo Auto,Main floor,Mach-E SYNC,Norton Court,Office,Living Room,This Device` (qty 10)  which leaves me with my desired 10 echo devices that are added.

**Comment by danielbrunt57** [comment]
> When attempting to add a device through the "included device" field in the UI, all Alexa devices are removed from Home Assistant, and the newly added device is not included.

You cannot use `include_devices` to _**add**_ a device since `include_devices` operates as _**only**_ this or these devices.
Also, `exclude_devices` **_only_** processes _**after**_ testing if `include_devices` was specified so `include_devices` has to be empty for `exclude_devices` to work.

The relevant code in `helpers.py`:
```
    for device in devices:
        if (
            include_filter
            and device.name not in include_filter
            or exclude_filter
            and device.name in exclude_filter
        ):
            _LOGGER.debug("%s: Excluding device: %s", account, device)
            continue
        new_devices.append(device)
```
There is an `or` between include_filter and exclude_filter so include_filter is checked first and if `True` (there is a list of `include_devices`) **_AND_** device name is not in the `include_devices` list then that device name is `excluded`.
` exclude_devices` is only checked if `include_devices` is empty.

**Comment by iricigor** [comment]
> 2. Once you have set the Include/Exclude fields, clearing them out does not stick.   
> 
> The second issue appears to be a legitimate bug, where once there is text in either the include or exclude fields, you can't clear it out through the UI. Deleting everything and clicking Submit appears to work but if you open Configure again you'll see the values are still there. The workaround I used is to edit the config/.storage/core.config_entries file directly. Just search for "alexa" to find the right line, then leave only an empty string ("") for include_devices and/or exclude_devices.

I've tried to edit the config/.storage/core.config_entries file directly, but the previous configuration is reappearing somehow. I have tried disabling integration, verified the config file is updated, but neither helped.

Anyway, is it legitimate to open a separate bug for the second issue, or it can be handled here?

**Comment by iricigor** [comment]
> 2. Once you have set the Include/Exclude fields, clearing them out does not stick.   
> 
> The second issue appears to be a legitimate bug, where once there is text in either the include or exclude fields, you can't clear it out through the UI. Deleting everything and clicking Submit appears to work but if you open Configure again you'll see the values are still there. The workaround I used is to edit the config/.storage/core.config_entries file directly. Just search for "alexa" to find the right line, then leave only an empty string ("") for include_devices and/or exclude_devices.

I've tried to edit the config/.storage/core.config_entries file directly, but the previous configuration is reappearing somehow. I have tried disabling integration, verified the config file is updated, but neither helped.

Anyway, is it legitimate to open a separate bug for the second issue or it can be handled here?

**Comment by danielbrunt57** [comment]
> 1\. `include_devices` ONLY loads devices that have been listed and functions like a deny list.
> 2\. Once you have set the Include/Exclude fields, clearing them out does not stick.
> The second issue appears to be a legitimate bug, where once there is text in either the include or exclude fields, you can't clear it out through the UI. Deleting everything and clicking Submit appears to work but if you open Configure again you'll see the values are still there. The workaround I used is to edit the `config/.storage/core.config_entries` file directly. Just search for "alexa" to find the right line, then leave only an empty string (`""`) for `include_devices` and/or `exclude_devices`.

It's not a bug but a limitation of HA config flow.  Those fields are type 'str' and the only way to "empty" them seems to be by submitting a <space>. I've added debug lines to the `OptionsFlowHandler` in `config_flow.py` and after erasing the field and clicking submit, the previous entry remains.  If I enter <space> in the field then it sets it to ' '.
My first try by simply deleting the contents from the field and clicking submit:
```
2024-12-14 19:21:30.700 DEBUG (MainThread) [custom_components.alexa_media.config_flow] CONF_INCLUDE_DEVICES in user_input: 'Bedroom,Daniel's Fire,Echo Auto,Main floor,Mach-E SYNC,Norton Court,Office,Living Room,This Device'

2024-12-14 19:21:30.702 DEBUG (MainThread) [custom_components.alexa_media.config_flow] data: {'exclude_devices': "Bedroom,Daniel's Fire,Echo Auto,Main floor,Mach-E SYNC,Norton Court,Office,Living Room,This Device", 'scan_interval': 120, 'queue_delay': 1.5, 'extended_entity_discovery': True, 'debug': False, 'include_devices': "Bedroom,Daniel's Fire,Echo Auto,Main floor,Mach-E SYNC,Norton Court,Office,Living Room,This Device", 'url': 'amazon.ca',
```
Note: the integration does not initiate a reconfiguration/reload as it saw no change in values.

2nd try after entering <space>:
```
2024-12-14 19:21:53.600 DEBUG (MainThread) [custom_components.alexa_media.config_flow] CONF_INCLUDE_DEVICES in user_input: ' '
2024-12-14 19:21:53.600 DEBUG (MainThread) [custom_components.alexa_media.config_flow] self.config_entry: <ConfigEntry entry_id=01JF1QZWSDNKJVP6Z5HCX14WY7 version=1 domain=alexa_media title=daniel@brunt.ca - amazon.ca state=ConfigEntryState.LOADED unique_id=daniel@brunt.ca - amazon.ca>
2024-12-14 19:21:53.600 DEBUG (MainThread) [custom_components.alexa_media.config_flow] data: {'include_devices': ' ', 'exclude_devices': "Bedroom,Daniel's Fire,Echo Auto,Main floor,Mach-E SYNC,Norton Court,Office,Living Room,This Device", 'scan_interval': 120, 'queue_delay': 1.5, 'extended_entity_discovery': True, 'debug': False, 'url': 'amazon.ca',
```
The integration then proceeds to reconfigure/reload and the entry in `core.config_entries` is updated:
```
{"created_at":"2024-12-14T04:49:22.733999+00:00","data":{"debug":false,"email":"<redacted>","exclude_devices":"Bedroom,Daniel's Fire,Echo Auto,Main floor,Mach-E SYNC,Norton Court,Office,Living Room,This Device","extended_entity_discovery":true,"include_devices":" ",
```

**Comment by danielbrunt57** [comment]
> @danielbrunt57 Did you check to see if your configuration with the space loaded the expected devices? I tried saving a space too, but then the integration loaded nothing. That makes sense to me because the include list is populated, so it is in effect, but the contents don't match any devices.
> 
> Regardless, if this behavior is in fact a core issue, it seems like it would have come up before. This is the only thing I found, which was closed without resolution: [home-assistant/core#34490](https://github.com/home-assistant/core/issues/34490). Is there some way AMP should be handling this case?

I'm not sure now what it showed after reconfigure.  I'd retest it but I'm deep into modifying the whole legacy aspect of include_devices or exclude_devices to be a single unified list with a selector to either include or exclude from the complete list of possible devices & entities.

**Comment by danielbrunt57** [comment]
@yorb See my [suggested fix](https://github.com/alandtse/alexa_media_player/issues/2751#issuecomment-2548631092) for when `include_devices` or `exclude_devices` has leading/trailing space(s).

Here's where I'm at so far on a revised method to replace `include_devices` and `exclude_devices`:

![image](https://github.com/user-attachments/assets/81e01a66-7c4a-470a-89c1-d58b949ffded)

![image](https://github.com/user-attachments/assets/03a11918-372e-4095-8e67-89ce5419bffe)

![image](https://github.com/user-attachments/assets/2e467ac7-dcca-417e-b587-707ba12e71bd)
