### ISSUE TITLE
Keep looping in Amazon Proxy page

### ISSUE THREAD

**Issue by raoulteeuwen** [alandtse/alexa_media_player#2557]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

I found out my Echo Dot was 'unavailable' as media player. Tried lots of stuff. Also removed the integration, rebooted, reinstalled the integration, but when i now try to 'activate' the integration, it keeps looping in the Amazon Proxy login page ('Welcome
 / [Create account New to Amazon?] / [Sign in Already a customer?] > Email or phone number
').

I did check whether my email address & pwd was correct, and it works when i sign in at my national Amazon site. I use a pwd-manager, so copy/paste email & pwd.

**To Reproduce**

1. Install integration
2. try to sign in
3. enter email and password
4. repeat

**Expected behavior**

Succesfully sign in after 1 attempt, integration recognizing Echo Dot as media player.

**Screenshots**

**System details**

- Home Assistant version: Core 2024.9.2, Supervisor 2024.09.1, Operating System 13.1, Frontend 20240909.1
- alexa_media version (from `const.py` or HA startup log): __version__ = "4.13.2"
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): can't do pip, don't see info in log (maybe due to fact integration is not getting installed?)
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): y
- Amazon Domain: .nl

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

Since integration is not getting installed, no option to toggle debugging mode?!

**Additional context**

**Comment by nstyqz** [comment]
Here https://github.com/alandtse/alexa_media_player/issues/2514 there is a halfway solution...

**Comment by raoulteeuwen** [comment]
Thank you, the solution described at https://github.com/alandtse/alexa_media_player/issues/2514#issuecomment-2359695740 worked for me. Now i'm back to a situation where the integration is present, but my Echo Dot is still unavailable... But i guess i need to open a new ticket for that / have been searching and trying stuff for hours for this before i totally lost the integration without joy for now

**Comment by stamandr** [comment]
I can't get by this continuous loop. The work around does not work for me

**Comment by dwellexity** [comment]
I too have the same issue.

**Comment by raoulteeuwen** [comment]
> I can't get by this continuous loop. The work around does not work for me

Please report as reply in https://github.com/alandtse/alexa_media_player/issues/2514 if you haven't done that. I will close this ticket, since it overlaps with https://github.com/alandtse/alexa_media_player/issues/2514 (which i initially didn't find when looking for my problem)

**Comment by danielbrunt57** [comment]
> I can't get by this continuous loop. The work around does not work for me

The only thing that would cause this if you've gotten to the combined email & password screen followed by the OTP screen is that your email & password + OTP code are failing to log in thus sending you back to the first screen.
