### ISSUE TITLE
Cannot bind my Amazon Alexa account

### ISSUE THREAD

**Issue by Starlord0006** [alandtse/alexa_media_player#2561]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

The install is going fine until the end, but when going for the last login on the Alexa page, it's looping Username/Password

I go through the entire process including the 2FA which is adding a new APP (the counter is increasing by 1)

I always have the "Open Website" prompt and the only way to pass it is to press the "X" and the integration is not installing.

**To Reproduce**

1. Go to 'Integration'
2. Type 'Alexa'
3. Install 'Alexa_Media_Player'

**Expected behavior**

After install "OPEN WEBSITE' should go away

**Screenshots**

![image](https://github.com/user-attachments/assets/ee085976-f4fd-4dd6-9735-32603f9f0bff)
![image](https://github.com/user-attachments/assets/1de9f17e-a3bd-4bfc-89fe-a01c598d2653)
![image](https://github.com/user-attachments/assets/5044662a-d83f-4012-8764-7083ee12c2ba)
![image](https://github.com/user-attachments/assets/209dca60-fa96-4228-9ca2-22bd139bab84)
![image](https://github.com/user-attachments/assets/a3a3adbc-ccbf-4856-b7d0-04bf83209f3f)
![image](https://github.com/user-attachments/assets/4898e29b-bcfe-42ff-af13-2b65d21e2fc2)

**System details**

- Home Assistant version: 2024.9.2
- alexa_media version (from `const.py` or HA startup log): 4.13.2 from HACS
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): y
- Amazon Domain: amazon.ca

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by r3pek** [comment]
Same for me. Also, for some reason, instead of using the public URL for the instance, it's using its private IP. :thinking:

**Comment by heyitsfredster** [comment]
Same here, stuck in the endless loop. Also unable find the option to use "legacy mode"

**Comment by heyitsfredster** [comment]
Actually, finally got it to work! Follow the steps here: https://github.com/alandtse/alexa_media_player/issues/2514#issuecomment-2345070532

**Comment by Starlord0006** [comment]
Fixed with this solution Thanks!

Actually, finally got it to work! Follow the steps here: https://github.com/alandtse/alexa_media_player/issues/2514#issuecomment-2345070532
