### ISSUE TITLE
Tuya sockets is displayed 10 times too high

### ISSUE THREAD

**Issue by thorstensd** [alandtse/alexa_media_player#2565]
The power consumption display of Tuya sockets is displayed 10 times too high. Example: current power consumption according to the Tuya app 431 watts. Display in Home assistant 4310 watts.

“W” was selected as the default display setting. However, the incorrect calculation also remains incorrect under the "KW" setting.

Thanks and best regards

Thorsten

![grafik](https://github.com/user-attachments/assets/3722f97a-2edb-477c-98ef-40b8f43fe485)

Pi4 Version
Core 2024.9.3
Supervisor 2024.09.1
Operating System 13.1
Frontend 20240909.1

**Comment by jamesonuk** [comment]
@thorstensd I think you raised this in the wrong place....  this is for Alexa Media Player integration not  Tuya
