### ISSUE TITLE
Impossible to login 

### ISSUE THREAD

**Issue by TioBundy** [alandtse/alexa_media_player#2567]
With the latest version of Alexa Media Player, include the previous versions +two weeks ago at least), it's impossible to login in the complement.

The integration can't relogin or fail to some checks to the account, and then not it's possible to recharge and not possible to re login again after uninstall the integration.

In the login web of Amazon, the login it's OK, but when I return to HA, the integration of AMP shows "FAIL", without any information.

![Uploading Screenshot_20240930-172549.png…]()

Please, check this, I need this integrations and love it.

**Comment by trickiegt** [comment]
Check dns blocking api.amazonalexa.com 
That was my problem
