### ISSUE TITLE
LogIn Problem

### ISSUE THREAD

**Issue by AleGhia** [alandtse/alexa_media_player#2571]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**after you write your email, password, amazon domain, auth key and press Send u will receive a problem on the alexa page login. You will receive a callback url and the page go back to the login email alexa page. This is in loop, i have try with google chrome and safari and to configure it with iphone and companion HA and via web on Windows Pc**

**To Reproduce**

1. Go to 'Open it from HACS'
2. Fill in data 'email, pass, amazon domain .it and auth 2fa'
3. Press Send
4. Compile the alexa login page email and then password
5. Press login and it will go back to the email login page in loop
**Expected behavior**

**Screenshots**

**System details**

- Home Assistant version: Core 2024.9.3 Supervisor 2024.09.1
- alexa_media version (from `const.py` or HA startup log): 4.13.2
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): i think last one
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): Yes
- Amazon Domain: Amazon.it

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

i'm not able to deactivate proxy access from the initial integration page

**Comment by ChavasRegal** [comment]
Same issue here, Integration stopped working a few days ago after trying to re add the account it just loops on the login page

**Comment by MaGicApr80** [comment]
I have the same issue for Amazon.de
I have to reinstall the integration after a ha restore. After entering the password the website loops to the site to enter the email address.

**Comment by stephenmetzger** [comment]
Issue is affecting me as well. Recently updated to the beta of HassOS 2024.10.

**Comment by srodighiero** [comment]
Known issue, on the login page try to register a new account with the same email, once received the error/message saying that the email it's already registered, than select again the option of already registered, and at this poitn the login should work.

**Comment by Fullmojjo** [comment]
Same i'am on the login loop. New user not working.

**Comment by AleGhia** [comment]
The @srodighiero method works

**Comment by AleGhia** [comment]
.

**Comment by stephenmetzger** [comment]
I can confirm this worked for me.

**Comment by michelgre** [comment]
Thanks to @srodighiero I finally could make it. After having tried I don't know how many times.
Also, when the login form is finally accepted, an OTP code is asked and the field is filled by an outdated code !
So what I did is both enroll my OTP application (with the QRCode) and this plugin, so that I could have the correct code... 
I am not sure, but this doesn't seem to be very reliable.

**Comment by DarthSonic** [comment]
Workaround to login works, but integration will not show up.

**Comment by TonyJr1** [comment]
I also see the same issue, using the workaround though produces a 400 server error from HA on the call back.

**Comment by TioBundy** [comment]
I have problems adding the integration:
The verification failed when everything worked, I uninstalled following tutorials that said it would solve the problem but nothing fixed it or directly, after being able to add the integration, it failed again but this time after the account verification process, which works. It is when returning to HA where it caused the error, although recently it now gives me error 500.

Neither the old versions, nor restarting, or deleting the yaml code that objectively provided a solution to the integration re-login work, nothing works to be able to add AMP back to my HA instance.
I'm getting by with Node Red, but it is much more difficult to do the things you want, which for now are few.

**Comment by protege323** [comment]
> Known issue, on the login page try to register a new account with the same email, once received the error/message saying that the email it's already registered, than select again the option of already registered, and at this poitn the login should work.

got the same login loop thanks your workaround was perfect

**Comment by gouthamravee** [comment]
I'm having the same problem, and the work around doesn't work. I get past login without any errors on the Amazon proxy page, but back in HA all I see is an empty modal with the title "Error" and no integration entry is added.

**Comment by JoeyGE0** [comment]
> Known issue, on the login page try to register a new account with the same email, once received the error/message saying that the email it's already registered, than select again the option of already registered, and at this poitn the login should work.

this worked thankyou!
