### ISSUE TITLE
Alexa Eco Don't update alarm

### ISSUE THREAD

**Issue by rbaptista1995** [alandtse/alexa_media_player#2572]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Hello so the problem is with last version 4.13.2 and home assistant core 2024.9.2/ Operating system 13.0 / Supervisor 2024.09.1

the next alarm don't automaticli update. So the next alarm only stay corret when manually i press relload.
With before version of home assistant i don't have this issues but with this automatic update don't work

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**

- Home Assistant version:
- alexa_media version (from `const.py` or HA startup log):
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n):
- Amazon Domain:

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by LeoeLeoeL** [comment]
Same for me

**Comment by AlexW75** [comment]
Same Problem HA automatically restarts after giving a command over alexa

**Comment by LeoeLeoeL** [comment]
Is it an issue for 3 people only?

**Comment by BlackHawk1912** [comment]
I have the same problem.

**Comment by ErikGei** [comment]
+1

**Comment by Maxzhao1999** [comment]
I'm having the same issue. Nothing suspicious in the logs though it just does not update

**Comment by LeoeLeoeL** [comment]
It's very strange developer can't solve this issue.

**Comment by rbaptista1995** [comment]
In this time they work for me with this specs:

CORE: 2024.12.2
Supervisor: 2024.11.4
Operating system: 14.0
Frontend: 20241127.7

Alexa Media Player: 5.0.3

Amazon Without MFA

Still work good with Echo DOT GEN5
