### ISSUE TITLE
Announcements on kids echo

### ISSUE THREAD

**Issue by vaderag** [alandtse/alexa_media_player#2585]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

I have an announcement that is working perfectly fine if I select a non-kids device, but the moment I change the target to a kids device it does nothing

Is this expected behavior? Is this a known issue?

I have double checked and communications are enabled and dnd is not on

**To Reproduce**

Send a tts announcement to a kids echo device

**Expected behavior**

Announcement works as it does if the target is a standard echo 

**Screenshots**

N/A

**System details**

- Home Assistant version: 2024.9.3
- alexa_media version (from `const.py` or HA startup log):
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n):
- Amazon Domain:

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by Jimbo222** [comment]
I have seen the same thing on non-amazon alexa enabled devices.  I have a samsung soundbar with the exact same behaviour.

**Comment by JamesMarcum** [comment]
Same issue here, since upgrading to HA 2024.6 - works fine until I have it announce something over one of my Alexa devices.  It announces once, then needs reintegration before it will announce again.
