### ISSUE TITLE
An error occurred accessing AlexaAPI: An exception of type TypeError occurred. Arguments: ('can only concatenate str (not "NoneType") to str',)

### ISSUE THREAD

**Issue by StefanoGiu** [alandtse/alexa_media_player#2598]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

2024-10-07 13:03:12.232 WARNING (MainThread) [alexapy.helpers] alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7f393e9c6480>,), {'cookies': {}}): An error occurred accessing AlexaAPI: An exception of type TypeError occurred. Arguments:
('can only concatenate str (not "NoneType") to str',)

The integration is not working since months... it authenticates properly, but then it requires re-authentication. I have the latest version of HA and of this component.

Please fix this!

**To Reproduce**

Wait the component to disconnect, try to re-authenticate

**Expected behavior**

**Screenshots**

**System details**

- Home Assistant version: 2024.10.0
- alexa_media version (from `const.py` or HA startup log): 4.13.4
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): 1.29.2
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): y
- Amazon Domain: amazon.it

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by danielbrunt57** [comment]
Duplicate issue [#2515](https://github.com/alandtse/alexa_media_player/issues/2515)

**Comment by cagnulein** [comment]
@StefanoGiu did you solve it?
