### ISSUE TITLE
Login not possible, login again after entering password

### ISSUE THREAD

**Issue by ImhotepDE** [alandtse/alexa_media_player#2601]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

After logging in, I am redirected back to the login page. It seems that the login is no longer working. I've tried it in several browsers, but the issue persists across all of them. Does anyone have any ideas?

**To Reproduce**

Settings → Devices & services → Add integration

from top to bottom:
- My Amazon email and below the password
- Amazon region I set to Amazon.de
- Insert Home Assistant URL (prefilled)
- integrated 2FA app key: Go to my Amazon account and under 2 way authentication I add a new app → press “I can't scan the QR code - > copy the long string in Homeassistant into the line above
- send

A small window opens with a six-digit number and a checkbox.

I paste the number into Amazon, press continue and the number of apps increases by one.

I check the box in Homeassistant to confirm that everything has worked and press send.

An Amazon window opens where I have to log in, after entering the password I end up back at the login page. I can repeat this as often as I like.

**Expected behavior**

no login possible 

**Screenshots**
1)
![image](https://github.com/user-attachments/assets/a646a4f5-a28a-4119-8e21-ee7ce00008a4)

2.)
![image](https://github.com/user-attachments/assets/a382f69c-38bf-4c37-b62c-627bd6fc1df8)

3.)
![image](https://github.com/user-attachments/assets/a646a4f5-a28a-4119-8e21-ee7ce00008a4)

**System details**

- Home Assistant version:
Core: 2024.10.1
Supervisor: 2024.09.1
Operating System: 13.1
Frontend: 20241002.2
- alexa_media version v4.13.4
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) Yes
- Amazon Domain: amazon.de

**Debug Logs (alexa_media & alexapy)**
It does not appear in the logs

**Comment by Phelton** [comment]
I have the same problem with my Amazon.it account.

**Comment by apedroneto** [comment]
I have the same problem.

**Comment by WJMarlow** [comment]
I have the same problem with my Amazon.co.uk account
