### ISSUE TITLE
Implement Alexa Motion Sensors

### ISSUE THREAD

**Issue by rlippmann** [alandtse/alexa_media_player#2602]
**NOTE: For a feature to be created it has to be doable in the Amazon app because we are basically replicating the app for HA. If you can't find it in the app, we probably can't create it here.**

**Is your feature request related to a problem? Please describe.**
I know there have been previous feature requests for this, and they have been closed.  But it looks like there is an [Alexa API for motion detection.](https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-motionsensor.html)

**Describe the solution you'd like**
Expose the motion sensors on Alexa devices with that capability.

**Describe alternatives you've considered**
The workarounds involve having Alexa set an input boolean on the HA side, but Alexa will only mark an "unoccupied" state after 30 minutes.  Looking at the documentation, it appears a 30 second poll interval might be achievable.

**Additional context**

**Comment by danielbrunt57** [comment]
I fail to see why a _media player_ integration needs to or should support motion sensors. AMP is already overworked, and under paid!  Personally, I have no desire for this capability thus no plan to work on it.

**Comment by rlippmann** [comment]
> I fail to see why a _media player_ integration needs to or should support motion sensors. AMP is already overworked, and under paid! Personally, I have no desire for this capability thus no plan to work on it.

Well, you can make the same argument as to why a media player needs to or should support temperature sensors :)

I don't mind working on it.  I just don't know much about all the internals of Alexa.  So, before I go down the road of implementing it, I just want to know if, given the API I've shown above, it is possible and/or difficult?

**Comment by danielbrunt57** [comment]
> Well, you can make the same argument as to why a media player needs to or should support temperature sensors :)

I agree with you on that one! :)
As for Alexa `motion sensors`, are you referring to the motion detection capabilities of echo devices?  The Echo Show uses its camera to detect when people are present or not.  Select echo dots use ultrasonic detection via their microphones.  With what I know about AMP and the undocumented API it uses to discover Alexa devices, I don't think those motion detecting mechanisms in those devices are reported as a capability when AMP discovers them...

**Comment by rlippmann** [comment]
> > Well, you can make the same argument as to why a media player needs to or should support temperature sensors :)
> 
> I agree with you on that one! :) but the temp sensors are a physical entity in echo devices whereas Alexa `motion sensors` in echo devices are just motion detection capabilities. The Echo Show uses its camera to detect when people are present or not. Select echo dots use ultrasonic detection via their microphones. With what I know about AMP and the undocumented API it uses to discover Alexa devices, I don't think the motion detecting mechanisms in those devices are reported as a capability when AMP discovers them...

I was thinking the ultrasonic detection (because that's what I have).

I know my alexa app has an "ultrasonic detection capable" field (which you need to enable).

AMP doesn't use the documented APIs?  They appear to be just http requests.  Admittedly, I haven't delved into the internals of what alexapy does.

**Comment by danielbrunt57** [comment]
> AMP doesn't use the documented APIs? They appear to be just http requests. Admittedly, I haven't delved into the internals of what alexapy does.

No, there's no documented API for what it's able to do but yes, they are just http(s) requests except for HTTP2 which is a push connection with Amazon.  Most of the groundwork came from elsewhere...
https://github.com/Apollon77/alexa-remote
http://blog.loetzimmer.de/2017/10/amazon-alexa-hort-auf-die-shell-echo.html
https://github.com/thorsten-gehrig/alexa-remote-control
https://github.com/openhab/openhab2-addons/blob/f54c9b85016758ff6d271b62d255bbe41a027928/addons/binding/org.openhab.binding.amazonechocontrol
https://github.com/noelportugal/alexa-reminders/blob/master/alexa-reminders.js#L75
https://github.com/openhab/openhab2-addons/blob/f54c9b85016758ff6d271b62d255bbe41a027928/addons/binding/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/Connection.java#L829

**Comment by rlippmann** [comment]
Yeah, I saw similar in my echo 5 logs.

So, technically we can do "glass break" and "baby cry" sensors, lol (I can see glass break, but baby cry and dog bark sensors, not so much).

Which do you have enabled?

**Comment by amandaworkman1988** [comment]
Id love this to be available in home assistant

**Comment by danielbrunt57** [comment]
> I assume since it's http2 it will push updates?

Amazon only issues the following HTTP2 push commands:

> PUSH_DOPPLER_CONNECTION_CHANGE
> PUSH_BLUETOOTH_STATE_CHANGE
> PUSH_AUDIO_PLAYER_STATE
> PUSH_MEDIA_QUEUE_CHANGE
> PUSH_MEDIA_CHANGE
> PUSH_MEDIA_PROGRESS_CHANGE
> PUSH_VOLUME_CHANGE
> PUSH_CONTENT_FOCUS_CHANGE
> PUSH_EQUALIZER_STATE_CHANGE
> PUSH_ACTIVITY  // no longer issued!
> PUSH_TODO_CHANGE // does not exist?
> PUSH_LIST_CHANGE // does not exist?
> PUSH_LIST_ITEM_CHANGE
> PUSH_MICROPHONE_STATE
> PUSH_DELETE_DOPPLER_ACTIVITIES
> PUSH_DEVICE_SETUP_STATE_CHANGE
> NotifyNowPlayingUpdated
> NotifyMediaSessionsUpdated

**Comment by danielbrunt57** [comment]
I'm playing around with the node-red-contrib-alexa-remote2-applestrudel (v5.0.50) in Node-RED and I can only poll for my Echo temperature sensor once every 6 minutes.  If I try 5 minutes I get the infamous "Too Many Requestes" error.

The motion detection capability of an Echo is not pushed anywhere except to internal Alexa routines.  And with what I see for polling temperature updates, the best that you might see is a new person detection update once every 6 minutes, which is okay since the ultrasonic person detection does not determine vacancy until the signals are not detected for up to 30 minutes.

I created an `input_boolean` helper that I exposed to Alexa as a switch and created two routines based on my Echo's "People are detected"/"not detected" to turn that switch on/off but I  am not seeing those routines trigger.  I'll leave my switch on and see if it maybe turns off overnight or not...

**Comment by rlippmann** [comment]
I've noticed that the presence detection is somewhat flaky dependent upon where the device is, how hard you actually step, etc.

The workaround triggering a switch exposed to alexa might be a better solution.  I was just hoping that somehow could make it more accurate than 30 minutes for "not detected".

**Comment by danielbrunt57** [comment]
> make it more accurate than 30 minutes for "not detected"?

That's an Amazon internal setting for the person detection mechanism in the echo and is not open for configuration.

FWIW, my helper is working though:

![image](https://github.com/user-attachments/assets/eec5e529-34c2-4d26-8263-de9e5983bf85)

**Comment by danielbrunt57** [comment]
I've been playing around with [node-red-contrib-alexa-remote2-applestrudel](https://flows.nodered.org/node/node-red-contrib-alexa-remote2-applestrudel) and I've been able to set up the presence detection but it still has the 30 minute no-activity to deactivate, which personally I perceive as not very usable, for my needs.  I'm going to rely on my $20 CR2450-powered Aqara motion sensors for my motion detection...

**Comment by danielbrunt57** [comment]
Not terribly useful!

**Comment by rlippmann** [comment]
Agreed.

**Comment by rlippmann** [comment]
FWIW, I opened a feature request on the HA core side:

[topic link](https://community.home-assistant.io/t/add-audio-presence-detection-to-alexa-integration/787337)
