### ISSUE TITLE
on 4.13.4, it works for a while after re-loading, but then stops announcing

### ISSUE THREAD

**Issue by ik0adr** [alandtse/alexa_media_player#2603]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

On 4.13.4, it works for a while after re-loading, but then stops announcing

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System details**

- Home Assistant version:
- alexa_media version (from `const.py` or HA startup log):
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n):
- Amazon Domain:

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by ps915** [comment]
after upgrading to 4.13.4, my TTS Notifys and also announcements wont work. I can hear, that Alexa lowers the volume while playing music, but it wont speak out loud the message anymore!

**Comment by danielbrunt57** [comment]
Home Assistant version: ### _unanswered_
alexa_media version (from const.py or HA startup log): **4.13.4**
alexapy version (from pip show alexapy in homeasssistant container or HA startup log): **1.29.2 ?**
Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): <_unanswered_>
Amazon Domain: ### _unanswered_
Debug Logs (alexa_media & alexapy): ### _not provided_

### Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).
