### ISSUE TITLE
Error affer successfully login 

### ISSUE THREAD

**Issue by radeon79** [alandtse/alexa_media_player#2606]
Hello  I am getting this error after successful login after a few hours:

Registratore: alexapy.helpers
Fonte: custom_components/alexa_media/__init__.py:361
Integrazione: Alexa Media Player ([documentazione](https://github.com/alandtse/alexa_media_player/wiki), [problemi](https://github.com/alandtse/alexa_media_player/issues))
Prima occorrenza: 04:12:25 (1 occorrenze)
Ultima registrazione: 04:12:25

alexalogin.login((<alexapy.alexalogin.AlexaLogin object at 0x7f3411602ed0>,), {'cookies': {}}): An error occurred accessing AlexaAPI: An exception of type TypeError occurred. Arguments: ('can only concatenate str (not "NoneType") to str',)

**Comment by danielbrunt57** [comment]
That error is from an Amazon error box window that AMP cannot process during its reauthentication process indicating there's likely a problem with your email + password + OTP secret.  Delete the integration, restart HA, clear browser cookies, log into Amazon with your email + password + OTP code, then re-add the integration with email + password + OTP secret.

**Comment by radeon79** [comment]
I did what was indicated, we'll see in the next few hours.
Thanks


Il giorno mer 9 ott 2024 alle ore 08:56 Daniel ***@***.***>
ha scritto:
