### ISSUE TITLE
problem with configuring 

### ISSUE THREAD

**Issue by Nash738850** [alandtse/alexa_media_player#2613]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Cant configure when it opens the alexa page

**To Reproduce**

1. Go to alexa media player
2. Click on configure
3. Scroll down to OTP continue

**Expected behavior**

When you sign in to the page it just is stuck in a loop trying to sign in, I just keep clicking sign in and it changed from username to password.

**Screenshots**

**System details**

- Home Assistant version: Core
2024.10.1
Supervisor
2024.10.0
Operating System
13.1
Frontend
20241002.2
- alexa_media version (from `const.py` or HA startup log): 4.13.4
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): idk
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): y
- Amazon Domain: amazon.com

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by rhysleach** [comment]
Same issue here

**Comment by TheBengaBenga** [comment]
Read this:
https://github.com/alandtse/alexa_media_player/issues/2514

In particular a post from danielbrunt57 on 12th September 2024 - dead easy fix (workaround)
