### ISSUE TITLE
Endless loop during setup.

### ISSUE THREAD

**Issue by MorreMor** [alandtse/alexa_media_player#2615]
Endless loop during setup. I enter OTP, etc., everything works. Finally, I confirm that OTP was entered, click OK -> website opens. Login, email address, password -> and then back to the beginning: email address, password…

**Comment by bkarakashev** [comment]
I got the same issue @MorreMor have you solve this issue some how?

**Comment by thordy** [comment]
I'm also having the same issue currently, and not sure how to get past this

**Comment by thordy** [comment]
@bkarakashev FYI following these instructions solved it for me https://github.com/alandtse/alexa_media_player/issues/2592#issuecomment-2408568673
