### ISSUE TITLE
cant install Alexa_media_player

### ISSUE THREAD

**Issue by pokusamigus** [alandtse/alexa_media_player#2621]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

I was using an old version of the add on via HACS (i think 4.8.1), I had to upgrade the Home Assistant to the current version, and that broke the AMP extension.
So I remove everything and started to scratch.
Once I've done that, I keep getting stuck on the install/authorization phase. which keeps itself on a loop. After I type the user name and password, on the Alexa login screen, it keep moving back, so I go from a user/email login --> password --> user/mail login --> password --> user/mail login --> password --> and so on...

**To Reproduce**

1) download the AMP in HACS (any version of AMP)
2) type the initial setup screen, with user name, password, 2FA token, region, etc.
3) the next step opens a new browser window for the username
4) the next step ask for the password
5) no error happens, but it moves back to step 3 above

**Expected behavior**
I would expect the next screen to be able to load the integration on the system.

**System details**

Core 2024.10.2
Supervisor 2024.10.0
Operating System 13.1
Frontend 20241002.3

- Home Assistant version:
- alexa_media version (from `const.py` or HA startup log): 4.13.4
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): 1.29.2 --> from manifest.json
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): YES
- Amazon Domain: amazon.co.uk

**Additional context**

I am not sure if related, but i do have a passkey activated on my computer for the amazon access.

**Comment by z-master42** [comment]
Duplicate of #2514

See comment: https://github.com/alandtse/alexa_media_player/issues/2514#issuecomment-2378133423

**Comment by pokusamigus** [comment]
> Duplicate of #2514
> 
> See comment: [#2514 (comment)](https://github.com/alandtse/alexa_media_player/issues/2514#issuecomment-2378133423)

that is perfect and worked. many thanks!
