### ISSUE TITLE
Unable to install alexapy module, possible dependency conflicts

### ISSUE THREAD

**Issue by Viv-Rajkumar** [alandtse/alexa_media_player#2629]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

After updating homeassistant(managed via linuxserver.io container) image to 2024.10.2 and the latest alexa_media HACS integration to 4.13.4 saw the integration was not loaded error in homeassistant.

Logs indicated module not found `alexapy`. Tried reinstalling the HACS alexa_media module, downgrading and so on with same issue.

Logging into the container, in `/usr/local/lib/python3.12/site-packages/` could only see `alexapy-1.29.2.dist-info` and not `alexapy` directory. 

To temporarily resolve (if helpful for any1 else running into it):
From Host: `docker exec -u abc -it homeassistant pip install --force-reinstall alexapy`

`abc` is the user inside the container the linuxserver.io image uses. Had to pass --force-reinstall or it wasnt resolved. Running with force reinstall did then resolve it. It is temporary tho as recreating the docker container puts it in initial state with this folder not being a typical bind mounted volume.

**To Reproduce**

N/A

**Expected behavior**

Dependency modules installed successfully

**Screenshots**

**System details**

- Home Assistant version: 2024.10.2
- alexa_media version (from `const.py` or HA startup log): 4.13.4
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): 1.29.2
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): y
- Amazon Domain: co.uk

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

Logs for force reinstall and dependency conflict if helpful:

```
...
Attempting uninstall: alexapy
    Found existing installation: AlexaPy 1.29.2
    Uninstalling AlexaPy-1.29.2:
      Successfully uninstalled AlexaPy-1.29.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
surepy 0.9.0 requires rich<11.0.0,>=10.1.0, but you have rich 13.9.2 which is incompatible.
weheat 2024.9.23 requires urllib3<2.1.0,>=1.25.3, but you have urllib3 2.2.3 which is incompatible.
python-linkplay 0.0.15 requires aiofiles>=24.1.0, but you have aiofiles 23.2.1 which is incompatible.
zhong-hong-hvac 1.0.12 requires attrs<24.0.0,>=23.1.0, but you have attrs 24.2.0 which is incompatible.
matrix-nio 0.25.2 requires aiofiles~=24.1, but you have aiofiles 23.2.1 which is incompatible.
homeassistant 2024.10.2 requires aiohttp==3.10.8, but you have aiohttp 3.10.10 which is incompatible.
homeassistant 2024.10.2 requires attrs==23.2.0, but you have attrs 24.2.0 which is incompatible.
homeassistant 2024.10.2 requires urllib3<2,>=1.26.5, but you have urllib3 2.2.3 which is incompatible.
homeassistant 2024.10.2 requires yarl==1.13.1, but you have yarl 1.15.3 which is incompatible.
meteofrance-api 1.3.0 requires urllib3<2.0.0,>=1.26.18, but you have urllib3 2.2.3 which is incompatible.
freebox-api 1.1.0 requires urllib3<2.0.0,>=1.26.6, but you have urllib3 2.2.3 which is incompatible.
uiprotect 6.1.0 requires aiofiles>=24, but you have aiofiles 23.2.1 which is incompatible.
plugp100 5.1.3 requires urllib3<2,>=1.26.5, but you have urllib3 2.2.3 which is incompatible.
Successfully installed aiofiles-23.2.1 aiohappyeyeballs-2.4.3 aiohttp-3.10.10 aiosignal-1.3.1 alexapy-1.29.2 anyio-4.6.2.post1 attrs-24.2.0 authcaptureproxy-1.3.2 backoff-2.2.1 beautifulsoup4-4.12.3 certifi-2024.8.30 cffi-1.17.1 charset-normalizer-3.4.0 click-8.1.7 cryptography-43.0.1 frozenlist-1.4.1 h11-0.14.0 h2-4.1.0 hpack-4.0.0 httpcore-1.0.6 httpx-0.27.2 hyperframe-6.0.1 idna-3.10 markdown-it-py-3.0.0 mdurl-0.1.2 multidict-6.1.0 propcache-0.2.0 pycparser-2.22 pygments-2.18.0 pyotp-2.9.0 requests-2.32.3 rich-13.9.2 shellingham-1.5.4 simplejson-3.19.3 sniffio-1.3.1 soupsieve-2.6 typer-0.12.5 typing-extensions-4.12.2 urllib3-2.2.3 yarl-1.15.3

```

**Comment by figorr** [comment]
I found exactly the same problem last monday when I updated Hikvision addon.

After restarting HA (Core 2024_7_4) ... Alexa Media Player failed to load and the log was showing no alexapy module was found. I restored a previous backup ... because I though it was a conflict with the Hikvision addon update ... but after restoring the backup ... same error, no alexapy module found.

Then, as I am running HA in a virtual machine, I decided to restore a snapshot from the last sunday. With no luck. Same error.

I run "pip show alexapy", and It was showing that alexapy 1.29.2 was already installed. So I decided to compile alexapy locally, including the last pending merge requests from Danielbrunt57 and Jens Leinenbach (version 1.30.0). I updated manifest.json to download the new alexapy from my GitHub repository instead of installing AlexaPy from PyPi.org. And after restarting HA with these new changes ... Alexa Media Player installed alexapy version 1.30.0 and the integration loaded without errors. So I thought It was a temporary problem of PyPi. But as you forced pip install and the problem was solved ... it is not a problem with PyPi.

**Comment by Viv-Rajkumar** [comment]
Going to mark this as closed. Latest [lsio release](https://github.com/linuxserver/docker-homeassistant/releases) seems to resolve this.

```
$ docker inspect -f '{{ index .Config.Labels "build_version" }}' homeassistant
Linuxserver.io version:- 2024.10.2-ls36 Build-date:- 2024-10-16T02:01:38+00:00
```
