### ISSUE TITLE
Config entry for alexa_media.media_player has already been setup - every 10 minutes after update to 4.13.6

### ISSUE THREAD

**Issue by Pirol62** [alandtse/alexa_media_player#2658]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Every 10 Minutes I receive a setup error 
Obviously AMP tries to configure my echo devices which are already be there

**Expected behavior**
No error
**System details**

- Home Assistant version: 2024.8.3
- alexa_media version (from `const.py` or HA startup log): 413.6
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): y
- Amazon Domain:
.de
**Debug Logs (alexa_media & alexapy)**
````
Logger: homeassistant.config_entries
Quelle: config_entries.py:604
Erstmals aufgetreten: 17:01:33 (2 Vorkommnisse)
Zuletzt protokolliert: 17:11:38

Error setting up entry xx@xxx.de - amazon.de for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 442, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 184, in async_setup_entry
    raise ValueError(
ValueError: Config entry xx@xx.de - amazon.de (9299908871ea811a2f1c2747cc46dc20) for alexa_media.media_player has already been setup!
````

**Additional context**

tts or announce seem to work as normal

**Comment by attila-szucs** [comment]
Exactly the same thing is happening here.

**Comment by Pirol62** [comment]
Already updated to 2024.10.4. Since then no new errors detected. I will watch until tomorrow and close this, when no errors appeared.

**Comment by attila-szucs** [comment]
I am on 2024.10.4 and still receive this error.

**Comment by Pirol62** [comment]
OK, just for info. After two days running this config no more errors noticed. Maybe the order of activities was relevant: I kept 2024.8.4 and AMP 4.13.2 until the relogin issues had been solved. Then I updated first to AMP 4.13.6 and received these errors. Last step was to update to 2024.10.4. No more errors detected.

**Comment by attila-szucs** [comment]
I have installed AMP 4.13.7 over 4.13.6, restarted and these error messages are now gone.

**Comment by Pirol62** [comment]
Does anybody still have this error? Otherwise I will close this ticket.

**Comment by Pirol62** [comment]
Close this as solved
