### ISSUE TITLE
Alexa Media Player NOT LOADED

### ISSUE THREAD

**Issue by heftved** [alandtse/alexa_media_player#2683]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**
After updating to Home Assistant 2024.11.2 and Alexa Media Player 4.13.8. I now get a "Not Loaded" error for the add-on.
Public URL is correct

Deleted Add on and re-installed add on. Add on loaded all entities as before, once authenticated through amazon.com.. Restarted home assistant to same failure.

Failure to load

Copy of the error logs

Logger: homeassistant.setup
Source: setup.py:416
First occurred: 10:28:36 AM (1 occurrences)
Last logged: 10:28:36 AM

Error during setup of component alexa_media
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/alexa_media/__init__.py", line 159, in async_setup
    CONF_PUBLIC_URL: account[CONF_PUBLIC_URL],
                     ~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'public_url'

**To Reproduce**

<!---Steps to reproduce the behavior:--->

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**

<!---A clear and concise description of what you expected to happen.--->

**Screenshots**
![IMG_1544](https://github.com/user-attachments/assets/96902782-1263-4ae1-9caa-eda7f313bb33)


<!---If applicable, add screenshots to help explain your problem.--->

**System details**

- Home Assistant version: 2024.11.2
- alexa_media version (from `const.py` or HA startup log): 4.13.8
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) <!---We will not debug login issues if unanswered---> (y/n):y
- Amazon Domain:

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**
Deleted configuration file, downloaded previous version 4.13.7, installed previous version, and now working again.
<!---Add any other context about the problem here.--->

**Comment by smokedropp23** [comment]
same for me

**Comment by danielbrunt57** [comment]
known issue.  Do not use 4.13.8.  It is being reverted...

**Comment by danielbrunt57** [comment]
> same for me

@smokedropp23 Please use the smiley face button & a thumbs up rather than cluttering issues with "same for me".  If you have anything useful to provide, that's different but in a long-winded issue, if 98 users post "same for me" it really clutters an issue as you can imagine.
