### ISSUE TITLE
Authentication needs to be repeated after every HA restart - DO NOT USE 4.13.8! Solution: Revert to 4.13.7

### ISSUE THREAD

**Issue by ThiloAm** [alandtse/alexa_media_player#2687]
**Describe the bug**

After restarting Home Assistant, authentication needs to be performed again and remains valid only until the next restart.

**To Reproduce**

Every restart of Homeassistant causes the error.

**Expected behavior**

One-time Login

**Screenshots**

**System details**

- Home Assistant version: 2024.11.2
- alexa_media version (from `const.py` or HA startup log) -  **4.13.8**
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): 1.29.4
- Is Amazon [2FA/2SV enabled](y/n): y
- Amazon Domain: amazon.de

**Debug Logs (alexa_media & alexapy)**
debug button not available - Extract from the general log.

```
Logger: homeassistant.components.media_player
Quelle: helpers/entity_platform.py:365
Integration: Mediaplayer (Dokumentation, Probleme)
Erstmals aufgetreten: 12:56:07 (1 Vorkommnisse)
Zuletzt protokolliert: 12:56:07

Error while setting up jellyfin platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/src/homeassistant/homeassistant/components/jellyfin/media_player.py", line 46, in async_setup_entry
    handle_coordinator_update()
  File "/usr/src/homeassistant/homeassistant/components/jellyfin/media_player.py", line 40, in handle_coordinator_update
    entity: MediaPlayerEntity = JellyfinMediaPlayer(coordinator, session_id)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/jellyfin/media_player.py", line 60, in __init__
    super().__init__(coordinator, session_id)
  File "/usr/src/homeassistant/homeassistant/components/jellyfin/entity.py", line 47, in __init__
    self.device_name: str = self.session_data["DeviceName"]
                            ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'DeviceName'
```

**Additional context**

**Comment by danielbrunt57** [comment]
I'm thinking the error you posted is a _**result**_ of the re-auth required after restart rather than the **_cause_** of it...

**Comment by ThiloAm** [comment]
Thank you for your response. Is it normal behavior for a re-authentication to be required after restarting Home Assistant?  
If so, is there an "easy" way to perform the re-authentication?

**Comment by danielbrunt57** [comment]
> Thank you for your response. Is it normal behavior for a re-authentication to be required after restarting Home Assistant?

No. For the periods when I'm not developing and breaking things, if I restart HA, it restarts just fine without reauth. Reauth occurs when token sign in fails then it tries using stored cookie login, then it tries stored credentials and fails, and that should not occur. Are you using OTP?  Are you using legacy YAML config?
I just noticed now you indicated you're using 4.13.8. That's a bad version and a PR has been merged into Dev to undo it. Until there's a new version released, use 4.13.7.

**Comment by ThiloAm** [comment]
I went back to version **4.13.7**. Now it works again.

Thank you for your help.

**Comment by MohanRatiram** [comment]
> I went back to version **4.13.7**. Now it works again.
> 
> Thank you for your help.

How do we roll back to 4.13.7 ? Thank you in advance for your 8

**Comment by danielbrunt57** [comment]
> How do we roll back to 4.13.7 ? Thank you in advance for your help

Via redownload in HACS.

![image](https://github.com/user-attachments/assets/f4a91fd2-36c9-4696-b2a0-63ed752f1994)

![image](https://github.com/user-attachments/assets/420983bb-39bc-4f17-9102-fb07a3f1e6d8)

**Comment by way-lo** [comment]
Can someone confirm this is fixed with v5.0?

**Comment by ThiloAm** [comment]
I have successfully installed version 5.0.0. After restarting, no reauthentication was required, which is exactly how I prefer it. Everything is working smoothly from my perspective

**Comment by ThiloAm** [comment]
Thank you for your support

**Comment by danielbrunt57** [comment]
I don't encounter reauthentications (but then again, I never have)!
