### ISSUE TITLE
Audible Details No Longer Showing

### ISSUE THREAD

**Issue by kurtdwarwick** [alandtse/alexa_media_player#2694]
**Describe the bug**

The integration used to show the currently playing audible content, including the book name and book cover as the entity image. I am not sure after which update it stopped showing this information, but it is no longer showing. 

Music does, however, still works as expected.

**To Reproduce**

1. Play any audible book through an alexa device (I am only using Echos)

**Expected behavior**

The currently playing book title and cover should be showing as state and entity picture for the specific device.

**Screenshots**

Nothing much to show, but here is a device that is "reading" a book:

![image](https://github.com/user-attachments/assets/0faa9865-02e2-4195-a321-c6ef5e1a5598)

and the state information (where you can see that the last request was to read a book)

![image](https://github.com/user-attachments/assets/3c9841aa-ca97-4b6c-9cf9-cd8718625c2b)

**System details**

- Home Assistant version: 2024.11.1
- alexa_media version (from `const.py` or HA startup log): 4.13.8
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): 1.29.4
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) : yes
- Amazon Domain: amazon.com

**Debug Logs (alexa_media & alexapy)**

There are no logs - things seem to working just fine.

**Additional context**

None

**Comment by Combatchuck** [comment]
If you open the Alexa app, then your device, you will see that when audible is playing it no longer shows the audio book playing. This is an echo issue and not a integration issue.

**Comment by kurtdwarwick** [comment]
Thanks @Combatchuck 

I didn't notice that. I find it strange to have removed this feature. We used it quite often since my kids listen to books, and we have a table devide that displays the book they're listening up on the wall. 

Anyways, I will close this issue!

I really hope it will return at some point in the future.

Cheers
