### ISSUE TITLE
TOTP code don't work 

### ISSUE THREAD

**Issue by PrzemekSkw** [alandtse/alexa_media_player#2695]
Hello, I install from HACS. When I try to add integration and put my credentials it shows me that 2FA code is wrong. I try many times and do this very fast. There's no problem to login on my Amazon account.
Regards.

**Comment by danielbrunt57** [comment]
Does the `otp_secret` you are entering look like this?
`6O5L VKJ2 WE2V 4XAV EJVF OHN2 55SE K5TG HRJM DYOH 3IC4 FLIO TTWA`

**Comment by PrzemekSkw** [comment]
Thanks, I have to add new 2FA app and use that long code.
Regards

**Comment by danielbrunt57** [comment]
> Thanks, I have to add new 2FA app and use that long code. Regards

Yes. The 52-character "secret" app key is what AMP uses to generate the 6-git TOTP code from.
