### ISSUE TITLE
Beta 2024.12.0b0 breaks AMP

### ISSUE THREAD

**Issue by Bergasha** [alandtse/alexa_media_player#2697]
Integration does not load on the latest beta, Error below.

Unable to install package alexapy==1.29.4: × No solution found when resolving dependencies: ╰─▶ Because alexapy==1.29.4 depends on aiofiles>=23.1.0,<24.0.0 and aiofiles>=24.1.0, we can conclude that alexapy==1.29.4 cannot be used. And because you require alexapy==1.29.4, we can conclude that your requirements are unsatisfiable.

**Comment by danielbrunt57** [comment]
`alexapy` issue posted: 
[Error loading Alexa Media Player integration on the latest HA beta release 2024.12.0b0 which requires aiofiles>=24.1.0](https://gitlab.com/keatontaylor/alexapy/-/issues/33)

**Comment by danielbrunt57** [comment]
@alandtse: `alexapy` issue posted: 
[Error loading Alexa Media Player integration on the latest HA beta release 2024.12.0b0 which requires aiofiles>=24.1.0](https://gitlab.com/keatontaylor/alexapy/-/issues/33)
