### ISSUE TITLE
Duplicated entities when using Home-Assistant-Matter-Hub custom Add-on

### ISSUE THREAD

**Issue by digiolin** [alandtse/alexa_media_player#2709]
**Describe the bug/issue**

I started to use the custom add-on [Home-Assistant-Matter-Hub](https://github.com/t0bst4r/home-assistant-matter-hub/) which creates a Matter Hub whereby HA devices can be controlled via Alexa without using the [Alexa via Home Assistant Cloud](https://www.home-assistant.io/cloud/alexa/) via Nabu Casa or the manually created [Amazon Alexa Smart Home Skill](https://www.home-assistant.io/integrations/alexa.smart_home/) (very slick!)

The Alexa Media Player application has logic already to handle devices added via the official [Alexa Integration](https://www.home-assistant.io/integrations/alexa.smart_home/) when using `Include devices connected via Echo`.

I duplicated [this issue](https://github.com/t0bst4r/home-assistant-matter-hub/issues/245) here so it can be a combined effort to find a good solution!

Here an example of a debug logs from a switch device:

```
{
    "applianceId": "AAA_SonarCloudService_<void>",
    "endpointTypeId": "",
    "driverIdentity": {
        "namespace": "AAA",
        "identifier": "SonarCloudService"
    },
    "manufacturerName": "TestVendor",
    "friendlyDescription": "TestVendor smart device",
    "modelName": "",
    "deviceType": "",
    "version": "0",
    "friendlyName": "Camara",
    "friendlyNameModifiedAt": 1733084691197,
    "capabilitiesModifiedAt": 1733084691197,
    "ipAddress": "",
    "port": "",
    "entityId": "<void>",
    "applianceNetworkState": {
        "reachability": "REACHABLE",
        "lastSeenAt": 1733130114179,
        "createdAt": 1733084691197,
        "lastSeenDiscoverySessionId": {
            "value": "<void>"
        }
    },
    "tags": {
        "tagNameToValueSetMap": {}
    },
    "additionalApplianceDetails": {
        "additionalApplianceDetails": {}
    },
    "firmwareVersion": "0",
    "actions": [],
    "capabilities": [
        {
            "capabilityType": "AVSInterfaceCapability",
            "type": "AlexaInterface",
            "version": "3",
            "properties": {
                "supported": [
                    {
                        "name": "powerState"
                    }
                ],
                "proactivelyReported": true,
                "retrievable": true,
                "readOnly": false
            },
            "interfaceName": "Alexa.PowerController"
        },
        {
            "capabilityType": "AVSInterfaceCapability",
            "type": "AlexaInterface",
            "version": "3",
            "properties": {
                "supported": [
                    {
                        "name": "connectivity"
                    }
                ],
                "proactivelyReported": true,
                "retrievable": true,
                "readOnly": false
            },
            "interfaceName": "Alexa.EndpointHealth"
        }
    ],
    "applianceTypes": [
        "SMARTPLUG"
    ],
    "isEnabled": true,
    "aliases": [],
    "connectedVia": "Echo Comedor",
    "alexaDeviceIdentifierList": [],
    "applianceKey": "<void>",
    "identifiers": {},
    "applianceDriverIdentity": {
        "namespace": "AAA",
        "identifier": "SonarCloudService"
    },
    "ipaddress": "",
    "applianceLambdaControlled": true,
    "mergedApplianceIds": [
        "AAA_SonarCloudService_<void>"
    ]
}
```
Maybe an option to exclude a likst of manufacturers or any other specific key will be useful.

1. Setup new matther hub using https://github.com/t0bst4r/home-assistant-matter-hub/
2. Enable `Include devices connected via Echo`
3. Duplicated instances will show up all over the place

**Expected behavior**

**Screenshots**

**System details**

- Home Assistant version: latest
- alexa_media version (from `const.py` or HA startup log): latest
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): latest
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): y
- Amazon Domain: es

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by danielbrunt57** [comment]
I had a similar issue with my TP-Link devices (2 smart light bulbs) as I have the TP-Link skill in Alexa as well as the TP-Link Integration in HA and AMP was re-adding Nightstand Lamp 1 and Nightstand Lamp 2.

Since I only had 2, I excluded them:
![image](https://github.com/user-attachments/assets/8fe29b0a-2900-473c-963e-933a4f398d11)

I've just had a look at the Matter Hub add-on and installed it but haven't configured a bridge yet.

I'm wondering what info if any uniquely identifies these Matter Hub devices connected via Echo?
Here?
```
    "applianceId": "AAA_SonarCloudService_<void>",
    "endpointTypeId": "",
    "driverIdentity": {
        "namespace": "AAA",
        "identifier": "SonarCloudService"
    },
```
or...
```
    "applianceDriverIdentity": {
        "namespace": "AAA",
        "identifier": "SonarCloudService"
    },
```
My two TP-Link lights appear in AMP debug logs as:

```
"light":[
   {
      "id":"a8e7ea9b-bddf-450e-a102-9416ca634834",
      "appliance_id":"AAA_SonarCloudService_fd0ff205-efa9-4be1-8581-eac04293d011:f0c6f807e5d6b2ba0395e2580b8623d6",
      "name":"Nightstand Lamp 1",
      "is_hue_v1":false,
      "brightness":true,
      "color":true,
      "color_temperature":true
   },
   {
      "id":"a58e580c-4d4a-4b27-82cf-0f175fa80a38",
      "appliance_id":"AAA_SonarCloudService_fd0ff205-efa9-4be1-8581-eac04293d011:2a24c46615e5ebb145d96becc457233b",
      "name":"Nightstand Lamp 2",
      "is_hue_v1":false,
      "brightness":true,
      "color":true,
      "color_temperature":true
   }
]
```
I'll add a bridge for just those two lights and have a look at resulting debug logs...

**Comment by danielbrunt57** [comment]
**Home Assistant Smart Home Skill (via `alexa: smart_home:`)**
(these are not "Discover devices connected via Echo")
Nightstand Lamp 2:
```
"SKILL_eyJza2lsbElkIjoiYW16bjEuYXNrLnNraWxsLmRkMWIyMjU5LTE4MTgtNDQ3OS1iOGVmLWJmOWE3ZDkxZTgyOCIsInN0YWdlIjoiZGV2ZWxvcG1lbnQifQ==_light#nightstand_lamp_2":{
   "applianceId":"SKILL_eyJza2lsbElkIjoiYW16bjEuYXNrLnNraWxsLmRkMWIyMjU5LTE4MTgtNDQ3OS1iOGVmLWJmOWE3ZDkxZTgyOCIsInN0YWdlIjoiZGV2ZWxvcG1lbnQifQ==_light#nightstand_lamp_2",
   "endpointTypeId":"",
   "driverIdentity":{
      "namespace":"SKILL",
      "identifier":"eyJza2lsbElkIjoiYW16bjEuYXNrLnNraWxsLmRkMWIyMjU5LTE4MTgtNDQ3OS1iOGVmLWJmOWE3ZDkxZTgyOCIsInN0YWdlIjoiZGV2ZWxvcG1lbnQifQ=="
   },
   "manufacturerName":"Home Assistant",
   "friendlyDescription":"light.nightstand_lamp_2 via Home Assistant",
   "modelName":"",
   "deviceType":"CLOUD_DISCOVERED_DEVICE",
   "version":"0",
   "friendlyName":"Nightstand Lamp 2",
   "friendlyNameModifiedAt":1715989459116,
   "capabilitiesModifiedAt":1715989459116,
   "ipAddress":"",
   "port":"",
   "entityId":"3edebc66-7e84-4142-8ec7-191529e6c014",
   "applianceNetworkState":{
      "reachability":"REACHABLE",
      "lastSeenAt":1733138322052,
      "createdAt":1715989459116,
      "lastSeenDiscoverySessionId":{
         "value":"7d22d25c-a36a-4b14-81d8-8f7e4e421579"
      }
   },
```

**TP-Link Skill**
Nightstand Lamp 2:
```
"AAA_SonarCloudService_fd0ff205-efa9-4be1-8581-eac04293d011:2a24c46615e5ebb145d96becc457233b":{
   "applianceId":"AAA_SonarCloudService_fd0ff205-efa9-4be1-8581-eac04293d011:2a24c46615e5ebb145d96becc457233b",
   "endpointTypeId":"",
   "driverIdentity":{
      "namespace":"AAA",
      "identifier":"SonarCloudService"
   },
   "manufacturerName":"TP-LINK",
   "friendlyDescription":"TP-LINK smart device",
   "modelName":"",
   "deviceType":"",
   "version":"0",
   "friendlyName":"Nightstand Lamp 2",
   "friendlyNameModifiedAt":1715380591165,
   "capabilitiesModifiedAt":1733138084512,
   "ipAddress":"",
   "port":"",
   "entityId":"a58e580c-4d4a-4b27-82cf-0f175fa80a38",
   "applianceNetworkState":{
      "reachability":"REACHABLE",
      "lastSeenAt":1733138322052,
      "createdAt":1715380591165,
      "lastSeenDiscoverySessionId":{
         "value":"7d22d25c-a36a-4b14-81d8-8f7e4e421579"
      }
   },
```

**Matter Hub**
Nightstand Lamp 1:
```
"AAA_SonarCloudService_6efb805b-4d08-39ad-b0bd-282250ea5299#3":{
   "applianceId":"AAA_SonarCloudService_6efb805b-4d08-39ad-b0bd-282250ea5299#3",
   "endpointTypeId":"",
   "driverIdentity":{
      "namespace":"AAA",
      "identifier":"SonarCloudService"
   },
   "manufacturerName":"TestVendor",
   "friendlyDescription":"TestVendor smart device",
   "modelName":"",
   "deviceType":"",
   "version":"0",
   "friendlyName":"Nightstand Lamp 1",
   "friendlyNameModifiedAt":1733138228207,
   "capabilitiesModifiedAt":1733138228207,
   "ipAddress":"",
   "port":"",
   "entityId":"84f6f292-959d-4e72-8bbc-6e50f51964fa",
   "applianceNetworkState":{
      "reachability":"REACHABLE",
      "lastSeenAt":1733138322052,
      "createdAt":1733138228207,
      "lastSeenDiscoverySessionId":{
         "value":"89543536-9013-42c2-b6a8-efdc57608bf1"
      }
   },
```
Nightstand Lamp 2:
```
"AAA_SonarCloudService_6efb805b-4d08-39ad-b0bd-282250ea5299#4":{
   "applianceId":"AAA_SonarCloudService_6efb805b-4d08-39ad-b0bd-282250ea5299#4",
   "endpointTypeId":"",
   "driverIdentity":{
      "namespace":"AAA",
      "identifier":"SonarCloudService"
   },
   "manufacturerName":"TestVendor",
   "friendlyDescription":"TestVendor smart device",
   "modelName":"",
   "deviceType":"",
   "version":"0",
   "friendlyName":"Nightstand Lamp 2",
   "friendlyNameModifiedAt":1733138228209,
   "capabilitiesModifiedAt":1733138228209,
   "ipAddress":"",
   "port":"",
   "entityId":"c7899879-e9b8-4309-8553-118bbd9e8351",
   "applianceNetworkState":{
      "reachability":"REACHABLE",
      "lastSeenAt":1733138322052,
      "createdAt":1733138228209,
      "lastSeenDiscoverySessionId":{
         "value":"89543536-9013-42c2-b6a8-efdc57608bf1"
      }
   },
```

I managed to spot this is the logs also:
```
"AAA_SonarCloudService_6efb805b-4d08-39ad-b0bd-282250ea5299":{
   "applianceId":"AAA_SonarCloudService_6efb805b-4d08-39ad-b0bd-282250ea5299",
   "endpointTypeId":"",
   "driverIdentity":{
      "namespace":"AAA",
      "identifier":"SonarCloudService"
   },
   "manufacturerName":"t0bst4r",
   "friendlyDescription":"t0bst4r smart device",
   "modelName":"",
   "deviceType":"",
   "version":"0",
   "friendlyName":"Test Bridge",
   "friendlyNameModifiedAt":1733138228209,
   "capabilitiesModifiedAt":1733138228209,
   "ipAddress":"",
   "port":"",
   "entityId":"b3fd978e-92b8-4053-aae6-403f5fbc7fd0",
   "applianceNetworkState":{
      "reachability":"REACHABLE",
      "lastSeenAt":1733138322052,
      "createdAt":1733138228209,
      "lastSeenDiscoverySessionId":{
         "value":"89543536-9013-42c2-b6a8-efdc57608bf1"
      }
   },
   "tags":{
      "tagNameToValueSetMap":{
         
      }
   },
   "additionalApplianceDetails":{
      "additionalApplianceDetails":{
         
      }
   },
   "firmwareVersion":"0",
   "actions":[
      
   ],
   "capabilities":[
      {
         "type":"AlexaInterface",
         "version":"1.0",
         "properties":{
            "supported":[
               
            ],
            "proactivelyReported":false,
            "retrievable":false,
            "nonControllable":false
         },
         "capabilityType":"AlexaEndpointCapabilityInstance",
         "interfaceName":"Alexa.Commissionable"
      },
      {
         "type":"AlexaInterface",
         "version":"1.0",
         "properties":{
            "supported":[
               
            ],
            "proactivelyReported":false,
            "retrievable":false,
            "nonControllable":false
         },
         "capabilityType":"AlexaEndpointCapabilityInstance",
         "interfaceName":"Alexa.Matter.NodeOperationalCredentials.FabricManagement"
      },
      {
         "capabilityType":"AVSInterfaceCapability",
         "type":"AlexaInterface",
         "version":"3",
         "properties":{
            "supported":[
               {
                  "name":"connectivity"
               }
            ],
            "proactivelyReported":true,
            "retrievable":true,
            "readOnly":false
         },
         "interfaceName":"Alexa.EndpointHealth"
      }
   ],
   "applianceTypes":[
      "HUB"
   ],
   "isEnabled":true,
   "aliases":[
      
   ],
   "connectedVia":"Kitchen Echo Dot",
   "alexaDeviceIdentifierList":[
      
   ],
   "applianceKey":"b3fd978e-92b8-4053-aae6-403f5fbc7fd0",
   "identifiers":{
      "networkInterfaceIdentifiers":[
         {
            "identifierType":"MatterNetworkInterfaceIdentifier",
            "type":"MATTER",
            "matterVendorId":"65521",
            "matterProductId":"32768",
            "matterDiscriminator":"0"
         }
      ]
   },
   "applianceDriverIdentity":{
      "namespace":"AAA",
      "identifier":"SonarCloudService"
   },
   "ipaddress":"",
   "applianceLambdaControlled":true,
   "mergedApplianceIds":[
      "AAA_SonarCloudService_6efb805b-4d08-39ad-b0bd-282250ea5299"
   ]
}
```
All of the above is in the single, multi-page log entry from the `get_network_details`:
```
2024-12-02 03:18:42.212 DEBUG (MainThread) [alexapy.alexaapi] d****l@b******a: static GET: https://alexa.amazon.ca/api/phoenix returned 200:OK:application/json
2024-12-02 03:18:42.212 DEBUG (MainThread) [alexapy.alexaapi] api_calls: 4
2024-12-02 03:18:42.258 DEBUG (MainThread) [alexapy.alexaapi] d****l@b******a: get_network_details response:
```

It will take some analyzing/debugging to track down where the logic is that handles devices added via the official [Alexa Integration](https://www.home-assistant.io/integrations/alexa.smart_home/) when using Include devices connected via Echo...

**Comment by digiolin** [comment]
IMO the exclude and include in AMP can be improved, it should be something regex compatible or at least a yaml on which we can specify any key and value to include/exclude.

As soon as @t0bst4r changes the manufacturer in its code: https://github.com/t0bst4r/home-assistant-matter-hub/issues/245#issuecomment-2511231226

We can just filter out by manufacturer and that's it, I think that it will be better to give to users the freedom and choose by their own what to include/exclude other than harcoding it 🤔

**Comment by digiolin** [comment]
@danielbrunt57 I thought that I added the link of the code wher this logic is implemented. 

https://github.com/alandtse/alexa_media_player/blob/master/custom_components/alexa_media/alexa_entity.py

**Comment by danielbrunt57** [comment]
> To solve this, there needs to be a way to tell `alexa_media` which ones to exclude.

There is but it is a comma separated list of friendly names to be excluded, which is not feasible if you are using Matter Hub to provide Alexa with all desired devices!

![image](https://github.com/user-attachments/assets/592e0a97-548c-4ad1-bd62-1b3232fc565a)

**Comment by danielbrunt57** [comment]
> @danielbrunt57 I thought that I added the link of the code wher this logic is implemented.
> 
> https://github.com/alandtse/alexa_media_player/blob/master/custom_components/alexa_media/alexa_entity.py

Thanks but I had already looked there straight away and found it.
It simply excludes if `connectedVia` is blank and `connectedVia` is _only_ blank for the Alexa Smart Home skill.
```
    if appliance.get("connectedVia"):
        # connectedVia is a flag that determines which Echo devices holds the connection. Its blank for
        # skill derived devices and includes an Echo name for zigbee and local devices.
        return True
```
The comment needs to be corrected as it is inaccurate and very misleading!

**Comment by danielbrunt57** [comment]
My first thought is:
The user needs to somehow specify the name of the bridge to exclude.
That `friendlyName` is here:
```
"AAA_SonarCloudService_6efb805b-4d08-39ad-b0bd-282250ea5299":{
   "applianceId":"AAA_SonarCloudService_6efb805b-4d08-39ad-b0bd-282250ea5299",
   "endpointTypeId":"",
   "driverIdentity":{
      "namespace":"AAA",
      "identifier":"SonarCloudService"
   },
   "manufacturerName":"t0bst4r",
   "friendlyDescription":"t0bst4r smart device",
   "modelName":"",
   "deviceType":"",
   "version":"0",
   "friendlyName":"Test Bridge",
```
From there, if we can get the `applianceId` for the bridge, then perhaps we can exclude devices with that `applianceId` prefix?
Bridge: `"applianceId":"AAA_SonarCloudService_6efb805b-4d08-39ad-b0bd-282250ea5299"`
Nightstand Lamp 2: `"applianceId":"AAA_SonarCloudService_6efb805b-4d08-39ad-b0bd-282250ea5299#4"`

**Comment by danielbrunt57** [comment]
> or at least a yaml on which we can specify any key and value to include/exclude.

FYI, AMP YAML Configuration has/is being deprecated and 5.0.0 now issues a warning to that effect.
Alan failed to provide me with version numbers for the warning so my PR says v4.14.0 will eliminate it but he jumped from 4.13.8 to 5.0.0 on the latest merge/release!  I'm not sure now which next version will totally ignore it but it definitely will be gone soon.

**Comment by digiolin** [comment]
> My first thought is: The user needs to somehow specify the name of the bridge to exclude. That `friendlyName` is here:
> 
> ```
> "AAA_SonarCloudService_6efb805b-4d08-39ad-b0bd-282250ea5299":{
>    "applianceId":"AAA_SonarCloudService_6efb805b-4d08-39ad-b0bd-282250ea5299",
>    "endpointTypeId":"",
>    "driverIdentity":{
>       "namespace":"AAA",
>       "identifier":"SonarCloudService"
>    },
>    "manufacturerName":"t0bst4r",
>    "friendlyDescription":"t0bst4r smart device",
>    "modelName":"",
>    "deviceType":"",
>    "version":"0",
>    "friendlyName":"Test Bridge",
> ```
> 
> From there, if we can get the `applianceId` for the bridge, then perhaps we can exclude devices with that `applianceId` prefix? Bridge: `"applianceId":"AAA_SonarCloudService_6efb805b-4d08-39ad-b0bd-282250ea5299"` Nightstand Lamp 2: `"applianceId":"AAA_SonarCloudService_6efb805b-4d08-39ad-b0bd-282250ea5299#4"`

That makes complete senses, I see all devices named like with `<applianceId of matter-hub>#<int>`

As a user we can control the name of the hub that it shows as friendlyName, this can lead us to find a way to filter out by hub, but this needs a new logic that is still not in place right?

**Comment by danielbrunt57** [comment]
> As a user we can control the name of the hub that it shows as friendlyName, this can lead us to find a way to filter out by hub, but this needs a new logic that is still not in place right?

Correct!  In addition to that, the user will need a way to somehow input that "skill" friendly name exclusion into AMP UI config.
Currently, `exclude_devices` is the friendly name but only the friendly name of the device.

**Comment by danielbrunt57** [comment]
Looking now at the above, I think I need to modify the 
`_LOGGER.debug("manufacturerName: %s", appliance.get("manufacturerName"))`
to
`_LOGGER.debug("manufacturerName: %s, connectedVia: %s", appliance.get("manufacturerName"), appliance.get("connectedVia"))`
to track down my TP-LINK lights...

**Comment by digiolin** [comment]
@danielbrunt57 checking your logs 👀 I don't see the `connectedVia` in any of the Lamps (in all skills and matter hub 🤷‍♂️ ), have you excluded it from the Logs or is actually not showing up?

**Comment by danielbrunt57** [comment]
Unless a `_LOGGER_debug` statement has been modified to specifically print it out, the only place I think you'll see it is in the multi-page, single log entry:
`2024-12-04 03:29:08.552 DEBUG (MainThread) [alexapy.alexaapi] d****l@b******a: get_network_details response:`

That is in my `alexaapi.py` that logs that entry:
```
    @staticmethod
    @_catch_all_exceptions
    async def get_network_details(login: AlexaLogin) -> Optional[dict[str, Any]]:
        """Get the network of devices that Alexa is aware of. This is the same as calling get_guard_details().

        Args:
        login: (AlexaLogin): Successfully logged in AlexaLogin

        Returns json
        """
        network_detail = await AlexaAPI.get_guard_details(login)
        if login._debug:
            _LOGGER.debug(
                "%s: get_network_details response: %s",
                hide_email(login.email),
                network_detail,
            )
        return network_detail
```
I think I modified that to use `login.debug` to conditionally log the entry, which is this configuration flag: 

![image](https://github.com/user-attachments/assets/9a1abe80-c13c-4e5d-ae06-6427ad81f000)

**Comment by danielbrunt57** [comment]
For the Matter Hub devices, this should exclude them, albeit hard-coded (for now):

```
def is_local(appliance: dict[str, Any]) -> bool:
    """Test whether locally connected via Echo device.

    This was originally written to prevent duplication/loops with the official Alexa integration.
    Things have evolved since then and more checks now need to be done.
    There might be better ways to process this as times change.
    """

    ### Some devices are connected to cloud via Echo devices but they already exist in HA and
    ### we do not want to duplicate them. The "t0bst4r" Matter Hub Add-on is the current known
    ### use-case and its devices currently have "manufacturerName": "TestVendor"

    if (
        appliance.get("manufacturerName") == "TestVendor"
    ):
        _LOGGER.debug("Excluding %s, manufacturerName: %s as not locally connected",
            appliance.get("friendlyName"),
            appliance.get("manufacturerName"),
        )
        return False

    if appliance.get("connectedVia"):
        # connectedVia is a flag that determines which Echo device holds the connection.
        # If it's not blank then we assume it is a device connected locally via an  Echo device.
        return True

    # Continue processing when connectedVia is empty.

    # This catches addtional Echo/AVS devices where connectedVia does not have
    # the Echo device since only the first appears to get that set.
    if "ALEXA_VOICE_ENABLED" in appliance.get("applianceTypes", []):
        if TP_LINK:
            _LOGGER.debug("alexa_entity TP-LINK being processed with: not is_skill(appliance) = %s", not is_skill(appliance))
        return not is_skill(appliance)

    # Ledvance/Sengled bulbs connected via bluetooth are hard to detect as locally connected
    # There is probably a better way, but this works for now.
    if (
        appliance.get("manufacturerName") == "Ledvance"
        or appliance.get("manufacturerName") == "Sengled"
    ):
        return not is_skill(appliance)

    # Zigbee devices are guaranteed to be locally connected via Echo devices and
    # have a particular pattern of id like "AAA_SonarCloudService_6E:FB:80:5B:4D:08"
    zigbee_pattern = re.compile(
        "AAA_SonarCloudService_([0-9A-F][0-9A-F]:){5}[0-9A-F][0-9A-F]", flags=re.I
    )

# Here is where we return either False (not a local device) or True if it's a Zigbee device that's connected to Alexa Echo w/Zigbee Hub since their connectedVia is empty (for some "Amazon" reason):
    return zigbee_pattern.fullmatch(appliance.get("applianceId", "")) is not None
```

**Comment by digiolin** [comment]
@danielbrunt57 I think that hard-coded is ok by now, I see that this ID is something than manufacturers use while testing their devis still not approved.

If @t0bst4r keeps that setting this will work flawless. 

Can I run your branch in my HA just for testing it?

**Comment by danielbrunt57** [comment]
I don't have a development branch but here is my live code...
[alexa_entity.zip](https://github.com/user-attachments/files/18012919/alexa_entity.zip)

**Comment by digiolin** [comment]
@danielbrunt57 it works fine 💅 

```
2024-12-05 17:24:19.175 DEBUG (MainThread) [custom_components.alexa_media.alexa_entity] alexa_entity: Camara, manufacturerName: TestVendor, connectedVia: None
2024-12-05 17:24:19.175 DEBUG (MainThread) [custom_components.alexa_media.alexa_entity] namespace: AAA, driverIdentity: None, deviceType: None
2024-12-05 17:24:19.175 DEBUG (MainThread) [custom_components.alexa_media.alexa_entity] alexa_entity: Camara, manufacturerName: TestVendor is_local? False
2024-12-05 17:24:19.175 DEBUG (MainThread) [custom_components.alexa_media.alexa_entity] alexa_entity: Camara, manufacturerName: TestVendor, connectedVia: None
2024-12-05 17:24:19.175 DEBUG (MainThread) [custom_components.alexa_media.alexa_entity] namespace: AAA, driverIdentity: None, deviceType: None
2024-12-05 17:24:19.175 DEBUG (MainThread) [custom_components.alexa_media.alexa_entity] alexa_entity: Camara, manufacturerName: TestVendor is_local? False
2024-12-05 17:24:19.175 DEBUG (MainThread) [custom_components.alexa_media.alexa_entity] alexa_entity: Camara, manufacturerName: TestVendor, connectedVia: None
2024-12-05 17:24:19.175 DEBUG (MainThread) [custom_components.alexa_media.alexa_entity] namespace: AAA, driverIdentity: None, deviceType: None
2024-12-05 17:24:19.175 DEBUG (MainThread) [custom_components.alexa_media.alexa_entity] alexa_entity: Camara, manufacturerName: TestVendor is_local? False
2024-12-05 17:24:19.175 DEBUG (MainThread) [custom_components.alexa_media.alexa_entity] alexa_entity: Camara, manufacturerName: TestVendor, connectedVia: None
2024-12-05 17:24:19.175 DEBUG (MainThread) [custom_components.alexa_media.alexa_entity] namespace: AAA, driverIdentity: None, deviceType: None
2024-12-05 17:24:19.175 DEBUG (MainThread) [custom_components.alexa_media.alexa_entity] alexa_entity: Camara, manufacturerName: TestVendor is_local? False
2024-12-05 17:24:19.175 DEBUG (MainThread) [custom_components.alexa_media.alexa_entity] Found unsupported device Camara
```

**Comment by danielbrunt57** [comment]
I'll do a quick-and-dirty PR with the `manufacturerName`: `TestVendor` hard-coded.
If @t0bst4r changes that, it'll have to be revised...

**Comment by danielbrunt57** [comment]
> I will check why the manufacturer is "TestVendor" instead of "t0bst4r"

Any luck in figuring this out on your end?
Is this related in any way?
https://sellercentral.amazon.com.mx/seller-forums/discussions/t/0c0a68be-6c5b-4d31-a4ef-4d2b03860feb

**Comment by t0bst4r** [comment]
Yes, I forgot to set the vendor details for every device. Instead I only set it for the bridge. 
I’ve changed that and will release it tomorrow.

**Comment by danielbrunt57** [comment]
> Yes, I forgot to set the vendor details for every device. Instead I only set it for the bridge. I’ve changed that and will release it tomorrow.

Thanks.  I'll revise by PR from "TestVendor" to "tobst4r".

**Comment by kennylevinsen** [comment]
It is unfortunately not correct for a matter bridge to report the bridge's vendor for on bridged devices. The vendor information there is meant to be that of the bridged device, e.g. "Philips" for a Hue bulb, *not* that of the bridge. The bridge vendor is only meant to be set on its own device node.

@danielbrunt57's idea of  getting the ID of the bridge device (which would still have the `t0bst4r` vendor, and also detail that it is a matter hub if one wanted to filter those out more generically) and checking an appliance ID prefix seems like a more viable long-term approach on first glance...
