### ISSUE TITLE
Setup failed for custom integration 'alexa_media': Requirements for alexa_media not found: ['alexapy==1.29.4']

### ISSUE THREAD

**Issue by fernandolcardoso** [alandtse/alexa_media_player#2712]
Integration stopped working with new Home Assistant version 2024.12

`
Registrador: homeassistant.setup
Fonte: setup.py:269
Ocorreu pela primeira vez: 16:37:25 (1 ocorrências)
Último registro: 16:37:25

Setup failed for custom integration 'alexa_media': Requirements for alexa_media not found: ['alexapy==1.29.4'].
`

**Comment by danielbrunt57** [comment]
Check the known issues **_before_** posting!

**Comment by domdomegg** [comment]
Duplicate of https://github.com/alandtse/alexa_media_player/issues/2720
