### ISSUE TITLE
Integration not loading on latest HA Code 2024.12.0

### ISSUE THREAD

**Issue by sayam93** [alandtse/alexa_media_player#2713]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

The integration stopped loading after upgrading to the latest HA Core version 2024.12.0. I am running HAOS 14 on RPi 4B

**To Reproduce**

1. Update HA Core to 2024.12.0

**Expected behavior**

Integration should load

**System details**

- Home Assistant version: 2024.12.0
- alexa_media version (from `const.py` or HA startup log): 5.0.0
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): 1.29.4

**Debug Logs (alexa_media & alexapy)**

```
Logger: homeassistant.util.package
Source: util/package.py:152
First occurred: 1:03:47 AM (3 occurrences)
Last logged: 1:03:52 AM

Unable to install package alexapy==1.29.4: × No solution found when resolving dependencies: ╰─▶ Because alexapy==1.29.4 depends on aiofiles>=23.1.0,<24.0.0 and aiofiles>=24.1.0, we can conclude that alexapy==1.29.4 cannot be used. And because you require alexapy==1.29.4, we can conclude that your requirements are unsatisfiable.
```

```
Logger: homeassistant.setup
Source: setup.py:269
First occurred: 1:03:52 AM (1 occurrences)
Last logged: 1:03:52 AM

Setup failed for custom integration 'alexa_media': Requirements for alexa_media not found: ['alexapy==1.29.4'].
```

**Comment by Pilchie** [comment]
Seeing this as well.

**Comment by theadlee** [comment]
Same here

**Comment by blaxsn0w** [comment]
Problems here too. Can't integreate it to my HA -> 500 Internal Server Error Server got itself in trouble

**Comment by sayam93** [comment]
Seems like this has been mentioned before and has been an issue since the beta.

https://github.com/alandtse/alexa_media_player/issues/2698

I am closing this one.
