### ISSUE TITLE
Invalid config error in 2024.12.0

### ISSUE THREAD

**Issue by oneseventhree** [alandtse/alexa_media_player#2715]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

Upgrading to the new HA gives me his error:
<img width="489" alt="image" src="https://github.com/user-attachments/assets/bf1204e0-d8a7-4c0d-875c-5919261ab0d1">

<img width="816" alt="image" src="https://github.com/user-attachments/assets/c38a8dcf-1bde-4cbc-8aae-3e95ea7b6698">

**To Reproduce**

1. Upgrade to latest HA version
2. Error shows up in notifcations

**Expected behavior**

To work as previous versions 

**Screenshots**

As above

**System details**

- Home Assistant version: 2024.12.0
- alexa_media version (from `const.py` or HA startup log): 5.0.0
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): 1.29.4
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): yes
- Amazon Domain:

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

**Comment by poudenes** [comment]
With a Dump in first post means you have same issue

**Comment by garfieldjsmith** [comment]
Me too. Everyone's seeing this issue. Seems it got reported in the beta release but wasn't picked up.

**Comment by bditter** [comment]
Also receiving the exact same error.

**Comment by oneseventhree** [comment]
Just saw this is a double up of: https://github.com/alandtse/alexa_media_player/issues/2713

**Comment by danielbrunt57** [comment]
> Me too. Everyone's seeing this issue. Seems it got reported in the beta release but wasn't picked up.

I picked it up, and fixed it, last week. Stumbling block is @alandtse...

**Comment by alandtse** [comment]
> I picked it up, and fixed it, last week. Stumbling block is @alandtse...

@danielbrunt57 I'm not sure why you're sniping at me or how this is productive.

**Comment by danielbrunt57** [comment]
> @danielbrunt57 I'm not sure why you're sniping at me or how this is productive.

My apologies!  I'm frustrated, tired and under a lot of stress in my life.  Please forgive and forget.  I'll try and refrain from such comments in the future. 😊
