### ISSUE TITLE
Unable to install package alexapy after upgrade to HA 2024.12

### ISSUE THREAD

**Issue by aberenguel** [alandtse/alexa_media_player#2718]
**Describe the bug**

After upgrade to Home Assistant 2024.12, the integration stopped to work. 

The log shows:
```
Logger: homeassistant.setup
Source: setup.py:269
First occurred: 21:33:11 (1 occurrences)
Last logged: 21:33:11

Setup failed for custom integration 'alexa_media': Requirements for alexa_media not found: ['alexapy==1.29.4'].
```

and 

```
Logger: homeassistant.util.package
Source: util/package.py:152
First occurred: 21:33:08 (3 occurrences)
Last logged: 21:33:11

Unable to install package alexapy==1.29.4: × No solution found when resolving dependencies: 
╰─▶ Because alexapy==1.29.4 depends on aiofiles>=23.1.0,<24.0.0 and aiofiles>=24.1.0, 
we can conclude that alexapy==1.29.4 cannot be used. 
And because you require alexapy==1.29.4, we can conclude that your requirements are unsatisfiable.
```

**To Reproduce**

Upgrade to Home Assistant 2024.12

**Expected behavior**

Integration continues to work 

**Screenshots**

<img width="489" alt="image" src="https://github.com/user-attachments/assets/3d850968-0e28-4222-93cd-1e561267b17c">

**System details**

- Home Assistant version: 2024.12
- alexa_media version (from `const.py` or HA startup log): 5.0.0
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): failed to install apparently 
- Is Amazon [2FA/2SV enabled]: yes
- Amazon Domain: amazon.com.br

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Comment by Dzoker2** [comment]
Same here after 2024.12 update

**Comment by johnjoemorgan** [comment]
System check gives:

Configuration warnings
 Platform error 'notify' from integration 'alexa_media' - Requirements for alexa_media not found: ['alexapy==1.29.4']

**Comment by dietmar68** [comment]
Same here

**Comment by danielbrunt57** [comment]
Duplicate issue

**Comment by domdomegg** [comment]
Duplicate of https://github.com/alandtse/alexa_media_player/issues/2720
