### ISSUE TITLE
AMP Does not start after update to HASS Core_2024.11.3

### ISSUE THREAD

**Issue by daknightuk** [alandtse/alexa_media_player#2722]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

AMP Does not start after updating to HASS Core_2024.11.3

**To Reproduce**

Update to Core_2024.11.3
Reboot
AMP Shows - Not started in integrations and no option to start

**Expected behavior**

AMP Should have started 

**Screenshots**

Not available as reverted to backup prior to Core_2024.11.3 update

**System details**

- Home Assistant version: 
Core_2024.11.3

- alexa_media version (from `const.py` or HA startup log):

Alexa Media Player
5.0.0

- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account) Yes 2FA is turned on
- Amazon Domain:

amazon.co.uk

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

**Additional context**

Issue occurred immediately after Core_2024.11.3 update

**Comment by Petro31** [comment]
Please search before making an issue.

https://github.com/alandtse/alexa_media_player/issues/2698
