### ISSUE TITLE
HAOS fails to load after restart

### ISSUE THREAD

**Issue by shiftylilbastrd** [alandtse/alexa_media_player#2747]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

Following the update that fixed the AlexaPy compatibility issue #2723 anytime HAOS restarts it causes HAOS to fail to boot. Will successfully restart after a hard power cycle.

**To Reproduce**

1. Restart HAOS via webui

**Expected behavior**

Normal start of HAOS

**Screenshots**

**System details**

- Home Assistant version: 2024.12.2
- alexa_media version: 5.0.4
- alexapy version: 1.29.5"
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): N
- Amazon Domain: amazon.com

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).
[home-assistant_2024-12-12T19-23-03.779Z.log](https://github.com/user-attachments/files/18116524/home-assistant_2024-12-12T19-23-03.779Z.log)

**Additional context**

**Comment by shiftylilbastrd** [comment]
This seems to be an issue with the HA Core update

**Comment by cmsj** [comment]
@shiftylilbastrd is there a link to somewhere discussing that?

**Comment by shiftylilbastrd** [comment]
> @shiftylilbastrd is there a link to somewhere discussing that?

Google search actually bring up a lot of them [Search](https://www.google.com/search?q=ha+core+12.4+causing+rpi+not+to+restart&rlz=1C1RXQR_enUS1127US1127&oq=&gs_lcrp=EgZjaHJvbWUqCQgAEEUYOxjCAzIJCAAQRRg7GMIDMgkIARBFGDsYwgMyCQgCEEUYOxjCAzIJCAMQRRg7GMIDMgkIBBBFGDsYwgMyCQgFEEUYOxjCAzIJCAYQRRg7GMIDMgkIBxBFGDsYwgPSAQkxOTA3ajBqMTWoAgiwAgE&sourceid=chrome&ie=UTF-8)
