### ISSUE TITLE
500 Internal Server Error Server got itself in trouble - 2024.12.3 docker

### ISSUE THREAD

**Issue by lpercetti** [alandtse/alexa_media_player#2750]
Issue has been solved. Closing the issue

**Comment by altjx** [comment]
@lpercetti how'd you resolve the issue?

**Comment by lpercetti** [comment]
Hello @altjx,

I closed the issue because it's not strictly related to this integration, but more generally to Home Assistant Docker edition.

The solution I used is to overload the official homeassistant docker image using a Dockerfile that is preinstalling the python module.

Regards,
