### ISSUE TITLE
Amazon Air Quality Monitor Entities missing after upgrade to 5.1.0

### ISSUE THREAD

**Issue by johnwaynesn** [alandtse/alexa_media_player#2756]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

After upgrading the alexa_media_player HACS integration to version 5.1.0 most of the entities from my Amazon Air Quality Monitors disappeared. Only the temperature entity still is beeing published by the integration. Reloading the integration does not help.

**To Reproduce**

Upgrade to version 5.1.0 and restart HA afterwards. Even after reloading the integration after these steps, only the "First Air Quality Monitor Temperature" entity for each Amazon Air Quality Monitor is available.

**Expected behavior**

With Version 5.0.5 there are 6 entities published by the integration for each Amazon Air Quality Monitor:
- First Air Quality Monitor Carbon Monoxide
- First Air Quality Monitor Humidity
- First Air Quality Monitor Indoor Air Quality
- First Air Quality Monitor Particulate Matter
- First Air Quality Monitor Temperature
- First Air Quality Monitor Volatile Organic Compounds

**Screenshots**

![image](https://github.com/user-attachments/assets/a54a32bc-b41e-4947-8e36-d4aa8f67f294)

**System details**

- Home Assistant version: 2024.12.3
- alexa_media version (from `const.py` or HA startup log): 5.1.0
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log): 1.29.5
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): y
- Amazon Domain: amazon.de

**Debug Logs (alexa_media & alexapy)**
Please provide [logs](https://github.com/alandtse/alexa_media_player/wiki/FAQ#how-do-i-enable-debug-logging-for-the-component).

Too much sensitive data to remove from the log. If there are specific entries you need, let me know.

**Additional context**

**Comment by giogua** [comment]
Same issue for me.
Even tried deleting and re-adding the integration. Same result

**Comment by nephrotranz** [comment]
Same here. I went back to 5.0.5 and it's working again.

**Comment by giogua** [comment]
for me going back to 5.0.5 fixed the issue

**Comment by Homeassi-s** [comment]
> for me going back to 5.0.5 fixed the issue

I tried 5.0.5 and lower. still no more air quality

**Comment by knuti1960** [comment]
The fix from @alams154 works for me, thanks!

**Comment by SebNania** [comment]
Hi,
Same here, AQI dead from alexa media player since 9 of december, i think after 5.0.2 update and never back since.
I've tryed to return before and tested every 5.0.x versions => it does not work
I've made today the last 5.1 update announced to adresse this issue but no change for me

**Comment by alams154** [comment]
> Hi, Same here, AQI dead from alexa media player since 9 of december, i think after 5.0.2 update and never back since. I've tryed to return before and tested every 5.0.x versions => it does not work I've made today the last 5.1 update announced to adresse this issue but no change for me HA 2024.12.4 but same issue before with 2024.12.3 and 2024.12.2

AMP 5.0.5 seems to work for others so I think it might be a "caching" issue.  AMP seems to do something weird with the include devices option:
![image](https://github.com/user-attachments/assets/dd9b516c-4600-486f-8594-e8e6fe2e4f48)

One thing I like to try is disabling the include option and then submitting and then going back to the configure screen and re-enabling the include option, again submitting.

**Comment by Celexi** [comment]
> > Hi, Same here, AQI dead from alexa media player since 9 of december, i think after 5.0.2 update and never back since. I've tryed to return before and tested every 5.0.x versions => it does not work I've made today the last 5.1 update announced to adresse this issue but no change for me HA 2024.12.4 but same issue before with 2024.12.3 and 2024.12.2
> 
> AMP 5.0.5 seems to work for others so I think it might be a "caching" issue. AMP seems to do something weird with the include devices option ([HA URL]/config/integrations/integration/alexa_media -> Configure): ![image](https://private-user-images.githubusercontent.com/31905246/396659998-dd9b516c-4600-486f-8594-e8e6fe2e4f48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0OTg3MzUsIm5iZiI6MTczNDQ5ODQzNSwicGF0aCI6Ii8zMTkwNTI0Ni8zOTY2NTk5OTgtZGQ5YjUxNmMtNDYwMC00ODZmLTg1OTQtZThlNmZlMmU0ZjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA1MDcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNzM4ZjBlNzMxZTY3NTM1MDcyMGI4YWRiODEyOWZhNmE3M2EzMjYyMTg0NGRlNGUxMDY0MzQ2OWNhYWRkYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dJxzFerFEzc5hoRPV-5_3euSHBVuhaL4mxJXQSUU8is)
> 
> One thing I like to try is disabling the include option and then submitting and then going back to the configure screen and re-enabling the include option, again submitting.

that fixed it for me, thanks!

**Comment by johnwaynesn** [comment]
Issue is fixed for me aswell with https://github.com/alandtse/alexa_media_player/pull/2758. Everything works fine again. Thank you @alams154 for the very quick fix :) I'll leave the issue open until merged.

**Comment by gianky69** [comment]
> > Hi, Same here, AQI dead from alexa media player since 9 of december, i think after 5.0.2 update and never back since. I've tryed to return before and tested every 5.0.x versions => it does not work I've made today the last 5.1 update announced to adresse this issue but no change for me HA 2024.12.4 but same issue before with 2024.12.3 and 2024.12.2
> 
> AMP 5.0.5 seems to work for others so I think it might be a "caching" issue. AMP seems to do something weird with the include devices option ([HA URL]/config/integrations/integration/alexa_media -> Configure): ![image](https://private-user-images.githubusercontent.com/31905246/396659998-dd9b516c-4600-486f-8594-e8e6fe2e4f48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDY1NDgsIm5iZiI6MTczNDUwNjI0OCwicGF0aCI6Ii8zMTkwNTI0Ni8zOTY2NTk5OTgtZGQ5YjUxNmMtNDYwMC00ODZmLTg1OTQtZThlNmZlMmU0ZjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA3MTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNTA3YzRkNTEzZGM2NmE4NGNhOWZjZTY2YjM4MjBmYzU3ODg2ZGM4NzdkNmRlZmZmMWYwZDBiMGFjZGMzMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5kBBnf6DrVrW9lsVXHCNCHOWXBitXeRkhHTbClxwB60)
> 
> One thing I like to try is disabling the include option and then submitting and then going back to the configure screen and re-enabling the include option, again submitting.

Not working for me; going back to 5.0.5 and Air Monitor works again...

**Comment by SebNania** [comment]
Hi,
I'm back on last version and apply correction in [#2758](https://github.com/alandtse/alexa_media_player/pull/2758) AQI have not the message inexistant but data does not update, i've "unknow" as value

**Comment by gioxx** [comment]
Issue is also fixed for me (https://github.com/alandtse/alexa_media_player/pull/2758). Thanks @alams154 👍🏻

**Comment by HaraldGithub** [comment]
> Issue is also fixed for me (#2758). Thanks @alams154 👍🏻

Doesn't work for me, I'll waiting until a new AMP-Release (5.1.1? or so) is published.
I've have only on AQM and other devices for air quality observation.

**Comment by askarsat** [comment]
Fix in [#2758] worked for me as well to fix 5.1.0 release. Thank you @alams154!

**Comment by JasonBSteele** [comment]
I had to go back to 5.0.5 to get mine working again

**Comment by SebNania** [comment]
> Fix in [#2758] worked for me as well to fix 5.1.0 release. Thank you @alams154!

It's crazy, i've réinstall 5.1.0 and apply the correction in the commit #2758 and it does not work.
I'm happy for who it as solved the issue but it's really strange that it work for some users and not for all.

**Comment by daviddesmet** [comment]
The fix from https://github.com/alandtse/alexa_media_player/pull/2758 didn't work for me. I had to revert to 5.0.5 to get it working again.

**Comment by danielbrunt57** [comment]
> Reverting fixed it for me. Pretty annoying how this breaks every month or two, honestly. Is the dev in an arms race with Amazon, with them trying to block it maybe?

The dev isn't developing, only reviewing and merging pull requests that we the users/contributors submit.

**Comment by danielbrunt57** [comment]
It's really going to take someone who has these sensors to debug the current code...

**Comment by rodalpho** [comment]
Thanks for your ongoing efforts, much appreciated!

Maybe regular updates should be designated betas for a week then promoted to GA release if nobody complains? HACS does look to support release channels.

**Comment by kenwiens** [comment]
Fix 2758 - How do I apply a fix like this?  I've not applied a custom fix before.  Can someone please point me at documentation for how to interpret this and how / where to apply it (and what exactly do I apply?) :-)

thanks

**Comment by danielbrunt57** [comment]
Normally you'd just wait for that fix (which is a pull request) to be merged and released in a new version, which this one has. But if you see a PR and want to apply it before it it's released, I'd be happy to pass along my knowledge. I'm on my phone right now or I'd be more specific but after clicking the link to the PR, you want to look at "files changed" which is like tab 3 or 4 and it shows the original code on the left, new fcode on the right with minuses and plusses as to what was changed for each file. Above you can can see pull requests. Open have not been merged yet. Closed have been merged but may not be released as a new version yet, and new versions are packaged up as a zip file for HACS to process, which shows as current vrelease on the right side of the main code tab for this repository. I apologize in advance if my memory of it all is inaccurate or incorrect!

**Comment by SebNania** [comment]
Hi all,
Is it ok for who have trying to modify manually and it has not worked?
In my case, i've tryed everything (after 5.2.0 update), install again reboot homeassistant, inactivate AQI entitées and active them again, it is not in not recognized but every data of the AQI are "unknow" in place of the humidity, co temperature etc

**Comment by knuti1960** [comment]
> ... reboot homeassistant...

Did you try to reboot the whole system already?

**Comment by SebNania** [comment]
> > ... reboot homeassistant...
> 
> Did you try to reboot the whole system already?

Yes, i've tryed to restart from developers tools and system restart from parameters/system.
The sensors seams to be ok :
![image](https://github.com/user-attachments/assets/1f93b981-7884-4b98-823a-2ad961c568f6)

But not because they all return "unknow" as data :
![image](https://github.com/user-attachments/assets/ed0dd136-0315-4cb1-b329-bb03a501c997)
![image](https://github.com/user-attachments/assets/214756f2-ecd9-4e95-9541-4ac68abac629)

**Comment by eXtorian** [comment]
> Hi all, Is it ok for who have tryed to modify manually before 5.2 update and it has not worked? In my case, i've tryed everything (after 5.2.0 update), install again reboot homeassistant, inactivate AQI entitées and active them again, it is not in not recognized but every data of the AQI are "unknow" in place of the humidity, co temperature etc

I _thought_ I had the same issue, but I was just being impatient. The Air Quality Monitors only update every few minutes (I think it's 5 minutes in the Alexa app?). All the Air Quality Monitor sensors (including Temperature, that still worked in the previous update) were showing as "Unknown", but while writing this reply they've now all appeared. My HA Uptime is 11 minutes so just wait a while and it should be fine.

**Comment by SebNania** [comment]
On the screenshot i've tryed to reboot again the system to be sure, but i was be powered on since 5 hours.
I've not reboot or change anything since my message (2 hours ago) and it's still in unknow :(

**Comment by Homeassi-s** [comment]
Hi, since update to 5.1 AQM entities doesnt show. tried everthing here been told. After Update to 5.20 it still not show AQM etities.

when I roll back to an old backup with 5.05 it workes fine. (but too many changes I made in these time to go back)

**Comment by dougroutledge** [comment]
I haven't gotten data from my 7 air quality sensors for many updates now.  It is too bad, because they are among the most useful HA items.

**Comment by danielbrunt57** [comment]
I recently acquired an AQM to facilitate testing.  I added it to Alexa and it showed up fine in HA.  That said, I'm currently running an unorthodox version of AMP: still the v5.0.4 release that I've modified with the additional pull requests (I think!).  What I'll have to do is save my modified version and install the full vanilla version of AMP to see what I get for AQM.  Before I do that though, I need to finish submitting a PR for a new service I've added: `Alexa Media Player: Restore Previous Volume` which piggybacks onto the last feature I added `previous_volume`...

**Comment by dougroutledge** [comment]
Do you get any data readings from it?  My 7 AQM devices show up fine, but the integration stopped reporting their data months ago.  I have tried to turn the polling interval down, and removed and re-added the integration in hopes of restoring their function.
![image](https://github.com/user-attachments/assets/1ca9d83a-5394-46c9-a2c0-6d76fbfdb477)

**Comment by SebNania** [comment]
Same here, no matter the version i have AQI doesn't report data since exactly 10 days (2024/12/16 morning)

**Comment by eXtorian** [comment]
Well, all I can tell you is the latest version is definitely working fine for me. So it CAN work, and this suggests must be something different about out setups.

- I've got the latest updates of everything.
- Several Amazon Echos of various ages.
- Several Amazon AQMs.
- UK based (that can make a difference, but I doubt it here).

I've noticed sometimes you have to toggle the "Include devices connected via Echo" off, Save (reboot?) and on for AQMs to work correctly, but haven't had to do this in the past several months.

I've also noticed that AQMs don't always report immediately. I suspect it's only ever 5 or 10 minutes, and even then I suspect they only report IF there's a change. This seems to correlate with how the data is reported in the Amazon app too. If you reboot HA, the AQM sensors are Unknown until they report something.

**Comment by danielbrunt57** [comment]
My new AIAQM sensor was only giving me the temperature sensor.  After adding appropriate _LOGGER.debug commands, I determined that this code was preventing the additional sensors:
`alexa_entity.py`:
```
    manufacturerNames = ["Ledvance", "Sengled", "Amazon"]
    if appliance.get("manufacturerName") in manufacturerNames:
        _LOGGER.debug("is_local: Returning %s for %s", not is_skill(appliance), appliance.get("friendlyDescription"))
        return not is_skill(appliance)
```
"Amazon" was added recently and after removing it from the above code I got the additional sensors.
![image](https://github.com/user-attachments/assets/9399c5e4-1260-47a0-b808-4c5df3833905)

I now have to figure out why "Amazon" was added...

**Comment by adamsfarley** [comment]
Make sure you are connecting to the correct amazon.com or amazon.co.uk when adding the configuration

**Comment by dougroutledge** [comment]
> Make sure you are connecting to the correct amazon.com or amazon.co.uk when adding the configuration - this was the cause to my issue and now AQMs are working as expected.

The rest of it works, this is not the issue.

**Comment by dougroutledge** [comment]
I do see this on each attempt to start, it does eventually load. 

Logger: alexapy.helpers
Source: custom_components/alexa_media/alexa_entity.py:347
integration: Alexa Media Player ([documentation](https://github.com/alandtse/alexa_media_player/wiki), [issues](https://github.com/alandtse/alexa_media_player/issues))
First occurred: 6:56:46 AM (3 occurrences)
Last logged: 7:04:54 AM

alexaapi.get_entity_state((<alexapy.alexalogin.AlexaLogin object at 0x7fcda3a363c0>,), {'entity_ids': ['ccf4cc1a-4647-4c4b-9273-5a3ac829a459', '8e39cd58-1e3b-46b3-aa4a-c21c4ac6b802', '1a29e318-72f3-4783-bb5f-b84322e38a5c', '5ed604fe-b2ed-437d-8d75-12c6a2599525', '581a0b46-1470-420a-9366-c17d25813584', 'd421dd7b-09ff-42ba-a2dd-fe3e0f287d62', 'd8ac5c6e-ebd7-4eca-80d5-3b95f32401c0', 'ed4a3585-bb37-46d6-be5b-7c892bb31ebb', 'dfbcda4b-77c5-4727-9db0-c1150721022c', '931217b5-d3ef-486e-9ae1-a9cc3e8791b3', '8e96b2ef-a0f1-4201-9c40-8c132d4d2a7e', '1f9d58cd-a9ce-426e-88c3-11dc7ca4c18c', '8f0170da-e44d-4ead-9201-151804dddf98', '611a12ec-2c30-43f6-9ec3-ecb36dff7c4f', '4d79fac1-c20e-4bde-aee7-2ad76d0d74f3', 'f0164cd8-af6a-499d-b2ef-19b854bc362e', '841d9d5e-4c63-4ee7-83a0-54577481a6ed', '783ce5fa-7620-476b-b9f1-f8557365215c', '5a2ebd11-acf3-4616-b4d3-45e0cfa1da96', 'b90eba82-ac35-479b-86a3-904e4a11a534', 'b6b08a76-b89a-4b5f-b8b1-83ef1b5b9951', '79f7e12d-3a64-46cb-abee-18ea86829064', '29ba710a-a5b3-49e9-ad9e-6e70872ccfb0', '4ec1df92-1243-4520-95ef-34fe661de726', '00be974d-4723-4e79-9364-86f21a7fff8b', '81971406-f087-4084-9156-3273e4c187cf', '3490edc2-6700-4a79-b5ef-5b7b8826bb5f', '1c34f6f5-6ff3-4e41-a6a5-0ee2d4710ffe', 'b4c7bb7b-8713-459b-9d29-623636fb8949', 'df45f393-ed27-4bce-b04a-4b9b2bb8a1fb', '37683cc0-2f77-4661-9498-705162173948', 'eef445bb-dd5d-4da8-a014-88b2238490f7', '6c1931cc-4658-4107-bcb5-3b6ad8715cf3', '45629b96-f63e-4729-b996-415489ddee1e', 'a4c4f8e3-0d47-4423-90fb-a345d6c515e1', 'ee1184a9-aa30-4248-a082-a37244051635', 'd8f385f8-9ff3-4d9b-b445-2ed79b9a5761', '25b655f1-6183-4c28-98e4-a77c19aebae9', 'c6f50012-473a-48e9-a108-a3afaf195197', '1555c0ea-4194-4d37-819a-85a9747df202', 'fe1de052-04ee-4ea1-9a5c-ad40268c933f', '36d2b740-84e9-47c8-b257-1590775b1b07', '163c57ca-943d-496c-b7f4-617229f7641d', '3cc2d5d5-07b9-462c-b174-07f6d34f1713', '9abb87d4-3e54-4637-a07f-ac1b9e788630', '4ee52eaa-b0c7-4b4f-ba9b-a37573fc95db', '45df1f61-736a-429b-8f8f-1cc46818de87', '73465e71-5762-4962-9a2f-1960a75e58fb', '8348dbcc-ad50-40da-83ae-d64655b4a80d', '8c6f3180-7d6a-4bd3-b72a-9b54b1862b15', 'd25d676d-495f-4243-8754-3ec574501a81', '8d3c97b6-2535-4b44-85e1-6a8ebe15023b', '187e7ea4-b22c-4cb5-9bcb-dd3bc2ccc069', 'b800be2e-d016-47c1-a9c2-6f374545b019', '7efce604-8dda-4a37-9e7d-8d9a69856f09', 'a0f02010-f858-451d-ab2e-2cb459757d2d', '0839a269-af0f-44ad-8936-7e0014990a4a', 'b8733bb0-bfe6-458b-92e0-1bd8c937689c', '8d915412-c638-484d-ba0e-bcf1dce51802', '7d2d4ad7-f105-48d9-8b8a-17d9bf9ecb00', '77fc1206-9ca3-432f-b6d4-1b71fdb0e0ad', '903d4be6-de6e-4ed4-b7e4-2bff1eac8e70', '9cb216a6-d949-485d-a279-b79bce769487']}): Timeout error occurred accessing AlexaAPI: An exception of type CancelledError occurred. Arguments: ()
alexaapi.get_entity_state((<alexapy.alexalogin.AlexaLogin object at 0x7fcd985bb890>,), {'entity_ids': ['ccf4cc1a-4647-4c4b-9273-5a3ac829a459', '8e39cd58-1e3b-46b3-aa4a-c21c4ac6b802', '1a29e318-72f3-4783-bb5f-b84322e38a5c', '5ed604fe-b2ed-437d-8d75-12c6a2599525', '581a0b46-1470-420a-9366-c17d25813584', 'd421dd7b-09ff-42ba-a2dd-fe3e0f287d62', 'd8ac5c6e-ebd7-4eca-80d5-3b95f32401c0', 'ed4a3585-bb37-46d6-be5b-7c892bb31ebb', 'dfbcda4b-77c5-4727-9db0-c1150721022c', '931217b5-d3ef-486e-9ae1-a9cc3e8791b3', '8e96b2ef-a0f1-4201-9c40-8c132d4d2a7e', '1f9d58cd-a9ce-426e-88c3-11dc7ca4c18c', '8f0170da-e44d-4ead-9201-151804dddf98', '611a12ec-2c30-43f6-9ec3-ecb36dff7c4f', '4d79fac1-c20e-4bde-aee7-2ad76d0d74f3', 'f0164cd8-af6a-499d-b2ef-19b854bc362e', '841d9d5e-4c63-4ee7-83a0-54577481a6ed', '783ce5fa-7620-476b-b9f1-f8557365215c', '5a2ebd11-acf3-4616-b4d3-45e0cfa1da96', 'b90eba82-ac35-479b-86a3-904e4a11a534', 'b6b08a76-b89a-4b5f-b8b1-83ef1b5b9951', '79f7e12d-3a64-46cb-abee-18ea86829064', '29ba710a-a5b3-49e9-ad9e-6e70872ccfb0', '4ec1df92-1243-4520-95ef-34fe661de726', '00be974d-4723-4e79-9364-86f21a7fff8b', '81971406-f087-4084-9156-3273e4c187cf', '3490edc2-6700-4a79-b5ef-5b7b8826bb5f', '1c34f6f5-6ff3-4e41-a6a5-0ee2d4710ffe', 'b4c7bb7b-8713-459b-9d29-623636fb8949', 'df45f393-ed27-4bce-b04a-4b9b2bb8a1fb', '37683cc0-2f77-4661-9498-705162173948', 'eef445bb-dd5d-4da8-a014-88b2238490f7', '6c1931cc-4658-4107-bcb5-3b6ad8715cf3', '45629b96-f63e-4729-b996-415489ddee1e', 'a4c4f8e3-0d47-4423-90fb-a345d6c515e1', 'ee1184a9-aa30-4248-a082-a37244051635', 'd8f385f8-9ff3-4d9b-b445-2ed79b9a5761', '25b655f1-6183-4c28-98e4-a77c19aebae9', 'c6f50012-473a-48e9-a108-a3afaf195197', '1555c0ea-4194-4d37-819a-85a9747df202', 'fe1de052-04ee-4ea1-9a5c-ad40268c933f', '36d2b740-84e9-47c8-b257-1590775b1b07', '163c57ca-943d-496c-b7f4-617229f7641d', '3cc2d5d5-07b9-462c-b174-07f6d34f1713', '9abb87d4-3e54-4637-a07f-ac1b9e788630', '4ee52eaa-b0c7-4b4f-ba9b-a37573fc95db', '45df1f61-736a-429b-8f8f-1cc46818de87', '73465e71-5762-4962-9a2f-1960a75e58fb', '8348dbcc-ad50-40da-83ae-d64655b4a80d', '8c6f3180-7d6a-4bd3-b72a-9b54b1862b15', 'd25d676d-495f-4243-8754-3ec574501a81', '8d3c97b6-2535-4b44-85e1-6a8ebe15023b', '187e7ea4-b22c-4cb5-9bcb-dd3bc2ccc069', 'b800be2e-d016-47c1-a9c2-6f374545b019', '7efce604-8dda-4a37-9e7d-8d9a69856f09', 'a0f02010-f858-451d-ab2e-2cb459757d2d', '0839a269-af0f-44ad-8936-7e0014990a4a', 'b8733bb0-bfe6-458b-92e0-1bd8c937689c', '8d915412-c638-484d-ba0e-bcf1dce51802', '7d2d4ad7-f105-48d9-8b8a-17d9bf9ecb00', '77fc1206-9ca3-432f-b6d4-1b71fdb0e0ad', '903d4be6-de6e-4ed4-b7e4-2bff1eac8e70', '9cb216a6-d949-485d-a279-b79bce769487']}): Timeout error occurred accessing AlexaAPI: An exception of type CancelledError occurred. Arguments: ()
alexaapi.get_entity_state((<alexapy.alexalogin.AlexaLogin object at 0x7fcd952c9e50>,), {'entity_ids': ['ccf4cc1a-4647-4c4b-9273-5a3ac829a459', '8e39cd58-1e3b-46b3-aa4a-c21c4ac6b802', '1a29e318-72f3-4783-bb5f-b84322e38a5c', '5ed604fe-b2ed-437d-8d75-12c6a2599525', '581a0b46-1470-420a-9366-c17d25813584', 'd421dd7b-09ff-42ba-a2dd-fe3e0f287d62', 'd8ac5c6e-ebd7-4eca-80d5-3b95f32401c0', 'ed4a3585-bb37-46d6-be5b-7c892bb31ebb', 'dfbcda4b-77c5-4727-9db0-c1150721022c', '931217b5-d3ef-486e-9ae1-a9cc3e8791b3', '8e96b2ef-a0f1-4201-9c40-8c132d4d2a7e', '1f9d58cd-a9ce-426e-88c3-11dc7ca4c18c', '8f0170da-e44d-4ead-9201-151804dddf98', '611a12ec-2c30-43f6-9ec3-ecb36dff7c4f', '4d79fac1-c20e-4bde-aee7-2ad76d0d74f3', 'f0164cd8-af6a-499d-b2ef-19b854bc362e', '841d9d5e-4c63-4ee7-83a0-54577481a6ed', '783ce5fa-7620-476b-b9f1-f8557365215c', '5a2ebd11-acf3-4616-b4d3-45e0cfa1da96', 'b90eba82-ac35-479b-86a3-904e4a11a534', 'b6b08a76-b89a-4b5f-b8b1-83ef1b5b9951', '79f7e12d-3a64-46cb-abee-18ea86829064', '29ba710a-a5b3-49e9-ad9e-6e70872ccfb0', '4ec1df92-1243-4520-95ef-34fe661de726', '00be974d-4723-4e79-9364-86f21a7fff8b', '81971406-f087-4084-9156-3273e4c187cf', '3490edc2-6700-4a79-b5ef-5b7b8826bb5f', '1c34f6f5-6ff3-4e41-a6a5-0ee2d4710ffe', 'b4c7bb7b-8713-459b-9d29-623636fb8949', 'df45f393-ed27-4bce-b04a-4b9b2bb8a1fb', '37683cc0-2f77-4661-9498-705162173948', 'eef445bb-dd5d-4da8-a014-88b2238490f7', '6c1931cc-4658-4107-bcb5-3b6ad8715cf3', '45629b96-f63e-4729-b996-415489ddee1e', 'a4c4f8e3-0d47-4423-90fb-a345d6c515e1', 'ee1184a9-aa30-4248-a082-a37244051635', 'd8f385f8-9ff3-4d9b-b445-2ed79b9a5761', '25b655f1-6183-4c28-98e4-a77c19aebae9', 'c6f50012-473a-48e9-a108-a3afaf195197', '1555c0ea-4194-4d37-819a-85a9747df202', 'fe1de052-04ee-4ea1-9a5c-ad40268c933f', '36d2b740-84e9-47c8-b257-1590775b1b07', '163c57ca-943d-496c-b7f4-617229f7641d', '3cc2d5d5-07b9-462c-b174-07f6d34f1713', '9abb87d4-3e54-4637-a07f-ac1b9e788630', '4ee52eaa-b0c7-4b4f-ba9b-a37573fc95db', '45df1f61-736a-429b-8f8f-1cc46818de87', '73465e71-5762-4962-9a2f-1960a75e58fb', '8348dbcc-ad50-40da-83ae-d64655b4a80d', '8c6f3180-7d6a-4bd3-b72a-9b54b1862b15', 'd25d676d-495f-4243-8754-3ec574501a81', '8d3c97b6-2535-4b44-85e1-6a8ebe15023b', '187e7ea4-b22c-4cb5-9bcb-dd3bc2ccc069', 'b800be2e-d016-47c1-a9c2-6f374545b019', '7efce604-8dda-4a37-9e7d-8d9a69856f09', 'a0f02010-f858-451d-ab2e-2cb459757d2d', '0839a269-af0f-44ad-8936-7e0014990a4a', 'b8733bb0-bfe6-458b-92e0-1bd8c937689c', '8d915412-c638-484d-ba0e-bcf1dce51802', '7d2d4ad7-f105-48d9-8b8a-17d9bf9ecb00', '77fc1206-9ca3-432f-b6d4-1b71fdb0e0ad', '903d4be6-de6e-4ed4-b7e4-2bff1eac8e70', '9cb216a6-d949-485d-a279-b79bce769487']}): Timeout error occurred accessing AlexaAPI: An exception of type CancelledError occurred. Arguments: ()

**Comment by SebNania** [comment]
Good day all,
From my side i've the latest version up to date.
As last try i've deleted the integration entry and replay the configuration, selected the great domain (amazon.fr) done all the configuration without issue, all entities came back on this new configuration, the AQI entries are here to, but does not update, it stay as "unknow" the data does not come.
