### ISSUE TITLE
Amazon air quality sensor entities non longer provided

### ISSUE THREAD

**Issue by giogua** [alandtse/alexa_media_player#2757]
**IMPORTANT: Please search the issues, including closed issues, and the [FAQ](https://github.com/alandtse/alexa_media_player/wiki/FAQ) before opening a new issue. The template is mandatory; failure to use it will result in issue closure.**

**Describe the bug**

After updating to version 5.1.0, Amazon air quality sensor entities are no longer provided by the integration.

Out of the 6 initially provided entities (AQI, Temperature, humidity, CO, COV, PM) only temperature remains available

**To Reproduce**

1. Update Alexa Media Player integration to version 5.1.0
2. Air quality entities appears in HA as no longer provided by the integration

**Expected behavior**

Amazon air quality sensor entities should be provided by the integration (as it was prior update to version 5.1.0)

**System details**

- Home Assistant version: 2024.12.3
- alexa_media version (from `const.py` or HA startup log): 5.1.0
- alexapy version (from `pip show alexapy` in homeasssistant container or HA startup log):
- Is Amazon [2FA/2SV enabled](https://github.com/alandtse/alexa_media_player/wiki/Configuration#enable-two-factor-authentication-for-your-amazon-account)  (y/n): y
- Amazon Domain: amazon.it

**Comment by giogua** [comment]
Closing as duplicate of https://github.com/alandtse/alexa_media_player/issues/2756

**Comment by dougroutledge** [comment]
These have not worked in some time, and sadly they are some of the most useful things in HA.
