### ISSUE TITLE
I am missing an easy way to control volume level

### ISSUE THREAD

**Issue by bachmarc** [alandtse/alexa_media_player#2764]
I have seen that the the media player provides devices and assigned entities to HA.
The only thing I really miss is a simple way to control the volume level.

I know there is a service (which i failed to call from appdaemon due to nested unknown parameters) but even when I use it in yaml automations it feels like a tumor attached oddly to the other components.
I call the service to set it but cannot read the original volume level to return to it after I pushed the notification.

I would like to find an entity that controls the volume of a device in the integration. Or a parameter to the notify service...

**Comment by bachmarc** [comment]
so be it ...

**Comment by danielbrunt57** [comment]
@bachmarc 
Rather than creating a "bug" report, you could have created a "feature request" or more appropriately, opened a "new discussion".  You could also post a question over in the HA Community Forum.  I'll move this to discussions for you..
