### ISSUE TITLE
Notifications broken with recent updates

### ISSUE THREAD

**Issue by rtho782** [alandtse/alexa_media_player#2768]
**Describe the bug**

Recent versions have broken previously working doorbell notifications. I have tried recreating the automation action, but no sound is played from any device.

**To Reproduce**

Have an automation that includes a notification:
![image](https://github.com/user-attachments/assets/3c2e573f-9274-4712-861e-121eee32d243)

alias: Doorbell announcement
description: ""
triggers:
  - type: occupied
    device_id: b8bbf005cb31eccca417c1cb2e4fb674
    entity_id: 8539fc0da13e64704c1f7a6055f0aa19
    domain: binary_sensor
    trigger: device
conditions: []
actions:
  - action: notify.alexa_media_everywhere
    metadata: {}
    data:
      message: There's somebody at the door
mode: single

**Expected behavior**

The message should play through all Echos

**System details**

- Home Assistant version: 2024.12.5
- alexa_media version: 5.1.0
- alexapy version : 1.29.5
- Is Amazon [2FA/2SV enabled] (y/n): y
- Amazon Domain: amazon.co.uk

**Debug Logs (alexa_media & alexapy)**
[home-assistant_alexa_media_2024-12-20T14-17-47.058Z.log](https://github.com/user-attachments/files/18211808/home-assistant_alexa_media_2024-12-20T14-17-47.058Z.log)

**Additional context**

Not much else to say, I have looked through the various examples but I can't make anything play.

**Comment by danielbrunt57** [comment]
If you say "Alexa, play music everywhere", does that work?
There's another issue posted about the same issue so I think this is a duplicate.  That aside, after reading the other issue I had a look to see if I had notify.alexa_media_everywhere and I did not. But I'd never used everywhere so googled a bit, poked around in the app and found nothing about everywhere.  Then for WTH, I said "Alexa, play SiriusXM everywhere" and she did. I happily listened to Country Christmas as I work on new laminate in my kitchen. Then I went to watch TV and my ambient TV lighting did not turn on. Restarted the Pi3B+, still could not turn it on in HA. Restarted HyperHDR integration which indignantly told me I had to restart HA, which I did. A little later I was thinking and checked HA Dev Tools for notify.alexa_media_everywhere and I now have that service...

**Comment by rtho782** [comment]
Yes, I can play things everywhere by interacting with alexa through voice (e.g. radio stations). There is a speaker group named everywhere in the AMP config.

I did try to look for other similar issues before posting but possibly I am blind! Will look again.

**Comment by danielbrunt57** [comment]
I also now see media_player.everywhere...
![Screenshot_20241221_022447_Home Assistant](https://github.com/user-attachments/assets/c61f63b0-b5c8-4957-a2c7-e065fd2353a9)

But you don't see the notify counterpart??
I'll have another look in your debug log in the morning on my desktop. Totally not doable on my phone!!!

**Comment by rtho782** [comment]
I see the notify component, that's what I'm using in the automation:
![image](https://github.com/user-attachments/assets/c91515f5-9969-4236-8250-154edebe645b)


It just doesn't work!! :D

**Comment by danielbrunt57** [comment]
Ah, got it. I never tried using it! Ok, my curiosity is piqued....pausing TV and getting off the couch to go check...

**Comment by rtho782** [comment]
I've since realised the obvious and set up individual actions to send a notification to each echo, which works for now, so it's now a minor issue from my perspective!! 

Happy to assist in any way I can with logs etc?

**Comment by danielbrunt57** [comment]
I tried notify using TTS and got silence.  Reviewed the wiki as I'd remembered something about WHA and found this:

[TTS](https://github.com/alandtse/alexa_media_player/wiki/Configuration%3A-Notification-Component#tts) - This is the older media_player.alexa_tts functionality. Alexa will speak using Alexa's Simon says skill and will not sync between devices. This does not work with an Alexa Whole House Audio group (WHA). This does allow messages to phone apps which the Announce function does not. Canned_TTS can be sent as of 2.8.0 (e.g., alexa.cannedtts.speak.curatedtts-category-goodmorning/alexa.cannedtts.speak.curatedtts-random)
[Announce](https://github.com/alandtse/alexa_media_player/wiki/Configuration%3A-Notification-Component#announce) - This functionality will result in a beep prior to speaking. It can also allow display on Echo Shows/Spots (currently untested). WHA groups are supported. Unfortunately, it does not appear to sync across devices.

"Everywhere" would be the WHA "Alexa Whole House Audio group".  I changed `type: tts` to `type: announce` and I did hear the kitchen echo say "testing" but my office left & office right (paired), living room left & living room right (paired) and echo (in the living room at the moment) were silent.  No idea about garage or bedroom pair.  I then said "Alexa, play SiriusXM everywhere" and the house was alive with music!  But at 3 am I immediately said "Alexa, cancel"!

I see nothing out of the ordinary in my logs.  I suspect it's Amazon falling down on the job (yet again?)???
The integration performs amazing trickery, deception and feats of magic but only when Amazon cooperates!

It looks like WHA can only (reliably) be used for music.

PS - Yes, I like "stereo"!

**Comment by danielbrunt57** [comment]
> It looks like WHA can only (reliably) be used for music.

And that's probably due to code changes within Amazon as they are constantly tinkering and revising what the app does or does not do...

**Comment by rtho782** [comment]
So, it did work for me, up until HA did that update that broke AMP a couple of months back, then when AMP updated, it had stopped working. That was why I assumed it was changes AMP side, but it sounds like not!

I am not too fussed by just addressing them individually (sync doesn't need to be perfect, they are different rooms) so happy to close then :)

**Comment by danielbrunt57** [comment]
I tried creating a routine: when I say - "announce visitor" but the "everywhere" group was not an option for it to speak via.

I was able though to create a routine based on a smart home device change though.
I wasn't picky and just selected the first HA device "Air Pump", state "closes".  
My test routine in Alexa looks like this:

![Screenshot_20241221_001548_Home Assistant](https://github.com/user-attachments/assets/96db0544-070f-44c5-86ce-d85ccb20f130)

You could trigger that Alexa routine based on an appropriate entity state in HA that's exposed to Alexa.
I did not test it any further than that but it might be a good alternative to hard coding individual Alexa devices in HA?

**Comment by danielbrunt57** [comment]
The HA entity could be something like `binary_sensor.announce_front_door`, which you'd have to toggle `on`, delay a second, and then toggle back `off'.

**Comment by rtho782** [comment]
That could be perfect actually, I will have a go, thanks!

Honestly as soon as Nabu Casa get hardware as good as echo out, I will burn all my amazon devices :D
